### ISSUE TITLE
Updating to 4.6.1

### ISSUE THREAD

**Issue by labhollow** [ionic-team/ionic-native-google-maps#1]
Hi @wf9a5m75 I just tried updating the plugin and it appears to install 4.6 and not 4.6.1. Not sure if it's the way I'm updating or not.
The steps I took to update:
cordova plugin rm cordova-plugin-googlemaps
cordova plugin rm com.googlemaps.ios
npm install @ionic-native/core @ionic-native/google-maps
cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_IOS="xxx" 

After install:
+ @ionic-native/core@4.6.0
+ @ionic-native/google-maps@4.6.0

Thank you.

**Comment by wf9a5m75** [comment]
```
npm install @ionic-native/google-maps@4.6.1
```

**Comment by labhollow** [comment]
Ugh, Thank you!
