### ISSUE TITLE
Can't drag the map when a div overflow above

### ISSUE THREAD

**Issue by Cinnz** [ionic-team/ionic-native-google-maps#10]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ x ] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.2.9 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.6.0",
"@ionic-native/google-maps": "^4.7.0"
```

**Current behavior:**

can not drag the map when scroll a long div overflow above the map(the overflow part not cover the map view). I think the touch events stick with DOM

**Expected behavior:**

- This case works normally
![screenshot_20180420-184403](https://user-images.githubusercontent.com/14054017/39049284-21f30460-44cb-11e8-8803-17f3bd9c0856.jpg)

- I can't drag a part of the map in this case
![screenshot_20180420-184415](https://user-images.githubusercontent.com/14054017/39049349-569862c8-44cb-11e8-85ee-fe672fc66a06.jpg)

**Comment by Cinnz** [comment]
I created a demo repo here: https://github.com/Cinnz/demo-googlemaps-bug

**Comment by wf9a5m75** [comment]
Did you check the list dimension with chrome dev tool?

**Comment by Cinnz** [comment]
oh what's wrong with the list's dimension?.I've just let it bigger than the container div to get overflow effect.Do you know how to fix it?

**Comment by wf9a5m75** [comment]
I haven't run your project, but the dimension is probably the reason.

The maps plugin recognizes the correct z-index order. If the map div receives the touch event, then the map view is manipulated.

Check the list dimension with Chrome Dev Tools through `chrome://inspects`

**Comment by Cinnz** [comment]
I'm sorry but which is the correct order?. The map div stay above or the other one?

**Comment by wf9a5m75** [comment]
Please manipulate as normal HTML. Do you expect that the map div receive the touch event if it is under the list?

**Comment by wf9a5m75** [comment]
Ok, I caught up to you. I run your project, and reproduced it.

But this is already fixed problem.
Please reinstall the `cordova-plugin-googlemaps@2.3.0-rc1`.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add cordova-plugin-googlemaps@2.3.0-rc1 --variable API_KEY_FOR_ANDROID="(your api key)"  --variable API_KEY_FOR_IOS="(your api key)" 

$> cordova clean

$> ionic cordova run adroid
```

**Comment by Cinnz** [comment]
It works fine. Thanks for your help

**Comment by vosecek** [comment]
This problem seems to be back in current version 2.5.3. Only for Android. iOS and Browser work.

Scrolled content from list with height set to 40vh;  pinned via position:absolute; to bottom edge overlaps the map even it is hidded by overflow:hidden; Map is not draggable or touchable. Calling cordova.fireDocumentEvent('plugin_touch'); after scroll end doesnt help.
