### ISSUE TITLE
How to change the map language and region

### ISSUE THREAD

**Issue by MomenSh0** [ionic-team/ionic-native-google-maps#104]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
Can't change the map language and region

**Expected behavior:**
If possible to have and option for it, like on the web (JS API), I can set the language and region in the url query (&language=ar&region=sa).
Is there a way to change them programmatically because I'm working on a multilingual app ?

Thanks.

**Comment by wf9a5m75** [comment]
Good question, however there is no solution.

Although this plugin uses `Google Maps JavaScript v3` on browser platform, `Google Maps SDK for Android/iOS` are used on Android/iOS platforms.

And there is no way to specific language for those native SDKs. These SDKs use system language automatically.

`Google Maps JavaScript v3(browser platform)` detects browser language by default.

**Comment by MomenSh0** [comment]
Thank you for the clarification
