### ISSUE TITLE
Map is blank

### ISSUE THREAD

**Issue by cathypark** [ionic-team/ionic-native-google-maps#110]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/google-maps": "^4.7.0",

**Current behavior:**

I can't create a Map. I checked all issues related problem(API Key, deviceReady, backgroundColor).
My API key has no restraints. `plugin.google.maps.event.MAP_READY` event to work but I still don´t see the map
I have tried again without @ionic-native/google-maps but it was still not working properly.

Please NOTE attached screen-shot. (div's id is "sft-map-container")

**Expected behavior:**

A map is properly generated.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**
![screen shot 2018-10-25 at 8 39 33 pm](https://user-images.githubusercontent.com/21293072/47498189-7b97b000-d897-11e8-88dc-7a626ef9466b.png)

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by wf9a5m75** [comment]
At least, you should use the latest version.
https://www.npmjs.com/package/@ionic-native/google-maps

**Comment by drantunes** [comment]
I'm testing in a fresh ionic 4 project and the map is blank. I strictly followed the tutorial but on Android always gets the white screen. It seems to be a problem related to the getDiv function, as shown in the attached figure.

I'm using Ionic 4 Beta and all the libraries in the latest version.

<img width="1554" alt="screenshot 2018-10-26 12 53 31" src="https://user-images.githubusercontent.com/1202936/47577919-729df180-d91e-11e8-8aa0-5be488336dce.png">

**Comment by drantunes** [comment]
The `ionic cordova run browser` mode works fine.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

And don't jump in to another person's issue.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this thread.
