### ISSUE TITLE
How to add polyline with direction arrows

### ISSUE THREAD

**Issue by jameeshpm** [ionic-team/ionic-native-google-maps#111]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:** Polyline direction 

Is there anyway to add polyline with arrows as 
![image](https://user-images.githubusercontent.com/16596536/47556982-8853ec80-d907-11e8-8101-ab0c1b1e00a8.png)

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
This plugin does not provide the feature.

**Comment by wf9a5m75** [comment]
And no plan to implement direction at this time.
