### ISSUE TITLE
Could not resolve all files for configuration ':app:debugCompileClasspath'

### ISSUE THREAD

**Issue by leanminmachine** [ionic-team/ionic-native-google-maps#121]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-add-swift-support 1.7.2 "AddSwiftSupport"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-fcm-with-dependecy-updated 2.2.6 "Cordova FCM Push Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-qrscanner 2.6.0 "QRScanner"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-telerik-imagepicker 2.2.2 "ImagePicker"
cordova-plugin-uniquedeviceid 1.3.2 "UniqueDeviceID"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.5.0 "Cordova sqlite storage plugin"
cordova.plugins.diagnostic 4.0.10 "Diagnostic"
```

**Current behavior:**
`npm install --save @ionic-native/core@latest @ionic-native/google-maps@latest`
`ionic cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="[redacted]" --variable API_KEY_FOR_IOS="[redacted]" ` 

Running `cordova build` returns 
`Could not resolve all files for configuration ':app:debugCompileClasspath'.`
> Could not find play-services-basement.aar (com.google.android.gms:play-services-basement:15.0.1).
  Searched in the following locations:
      https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar

 https://jcenter.bintray.com/com/google/android/gms/play-services-basement/15.0.1/play-services-basement-15.0.1.aar returns a 404. 

**Expected behavior:**
Build should be successful.

**Comment by wf9a5m75** [comment]
`play-services-basement-15.0.1.aar` is not this plugin.

**Comment by leanminmachine** [comment]
@wf9a5m75 I think its a version conflict with another plugin but i found this https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/troubleshootings/conflict_with_other_plugins/README.md. 

Closing this issue
