### ISSUE TITLE
Xcode error "Thread 1: signal SIGABRT" when running in iOS emulator with latest (master branch)

### ISSUE THREAD

**Issue by goldman94** [ionic-team/ionic-native-google-maps#124]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ x ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
The plugin was working this morning but I removed and re-added the cordova plugin and then I started getting this error in Xcode as soon as the app opens in the emulator. I then tried adding it to a fresh starter project and got the same error.

**Expected behavior:**
There should be no Xcode error.

**Screen capture or video record:**
<img width="832" alt="screen shot 2018-11-07 at 12 41 57 pm" src="https://user-images.githubusercontent.com/35706971/48152925-b54eba80-e28a-11e8-9d1e-2e6932d04c1a.png">

**Related code, data or error log (please format your code or data):**

I can upload the mostly empty starter app if needed, but I don't believe it will be necessary in this case. It seems like the latest update was not tested on iOS.

**Comment by wf9a5m75** [comment]
Please share the project files on github.

**Comment by battika** [comment]
I have seen this one (SIGABRT) recently every now and then on IOS and very unexpectedly. I did two things, updated wkwebview to the latest version (v2.2.x) and replaced animateCamera() with moveCamera() everywhere in my code a I believe animateCamera() can cause issues when something happens before the animation has been completed. It significantly lowered crashing  and unfortunately ditched support for IOS 9 as latest version of wkwebview dropped support of it. I am not sure if you have the same issue but something that might worth trying.

**Comment by wf9a5m75** [comment]
Good see you, @battika.

Do you use the multiple_maps branch?
Could you make an example project files that reproduce your issue?

**Comment by battika** [comment]
Hello Masashi, good to see you too :) I am using the latest released version 2.4.6.

I was going to see if I can reproduce the issue with a basic project. Hope to have some time soon to create a sample project.

In the meantime, hope the creator of this issue can provide the source code.

**Comment by goldman94** [comment]
Here is my repo: https://github.com/goldman94/testMaps

Thank you for the suggestion, @battika. I will try updating wkwebview.

**Comment by wf9a5m75** [comment]
@goldman94 As far as I see your repo, there is no code.
https://github.com/goldman94/testMaps/blob/8a09b9a5d39eddc9e331063b1cf76459ac74f294/src/pages/home/home.ts

**Comment by goldman94** [comment]
Sorry! Updated now.

**Comment by goldman94** [comment]
Oh, I guess I just needed to run "pod install" again. Sorry to waste your time guys. Thanks for the effor though, I appreciate it.
