### ISSUE TITLE
How to use plugin methods

### ISSUE THREAD

**Issue by newtmex** [ionic-team/ionic-native-google-maps#126]
Hi, this is just a question.
How can I use the plugin methods directly.
Say, I want to do this
`
    let directionsDisplay = new plugin.google.maps.DirectionsRenderer();
`
How should I go about it.

My aim is to get the `DirectionsRenderer()` method from the plugin.

Thanks.

**Comment by wf9a5m75** [comment]
Not provided. Please use Google Maps JavaScript v3 directly without this plugin if you want.
