### ISSUE TITLE
The KML file/layer never load and no gets errors

### ISSUE THREAD

**Issue by Hanzofm** [ionic-team/ionic-native-google-maps#13]
I am trying to add a city kml **layer exported via google maps web.**

This is the first file

`https://we.tl/uarWXlY3i7`

And this is the code used to load the kml file (that is called after, maps is ready):

```
addKMLOverlay() {
    console.log("add kml serv")
    return this.map.addKmlOverlay({
      /*'url': 'http://myrally.io/kml/test.kml',   // <-- This file works perfectly*/
      'url': 'assets/kml/gcval.kml',   // <-- .KMZ file is not supported yet!
      'clickable': true,
      'suppressInfoWindows': false
    }).then(kmlOverlay => {
      console.log(JSON.stringify(kmlOverlay));
    }).catch(error => {
      console.error(JSON.stringify(error))
    })
  }
```

When I try to load the first file it not loads never and not returns any error.

What would be the problem with the first file?

```
This is the ionic info

cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0 

local packages:

    @ionic/app-scripts : 3.1.9
    Cordova Platforms  : android 6.4.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    ios-sim           : 6.1.2 
    Node              : v9.9.0
    npm               : 5.7.1 
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145 


```

Ionic native core v.4.7
Ionic native google maps v.4.7
cordova-plugin-googlemaps 2.2.9

**Comment by Hanzofm** [comment]
Sorry I don’t understand,

Do you refer to this?

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.2.0/README.md

**Comment by wf9a5m75** [comment]
Oh, sorry I misunderstand. I thought you asked me about tileLayer. I was so busy this week.

Make sure your url is correct.
The kml is loaded from correct url or path.

If you can't solve the problem by yourself, please share your project files on GitHub

**Comment by wf9a5m75** [comment]
ping

**Comment by Hanzofm** [comment]
Sorry, 

The url is loaded correctly, the file is locally placed on assets file(you can download the file from the link)

Is very strange because it not return any error.

The kml is a polygon that covers a part of a country and is generated via google maps page

Thanks for your time

**Comment by wf9a5m75** [comment]
If you can't solve the problem by yourself, please share your project files on GitHub

**Comment by wf9a5m75** [comment]
ping

**Comment by Hanzofm** [comment]
I think that I have founded the problem.

If i remove the `<tessellate>1</tessellate>` attribute of `<LinearRing>` attribute it works, I don't know if this is the exact problem but it works.

On the other hand it is strange that it not returns any error, if there are a unsupported attribute it should be crash no?

**Comment by wf9a5m75** [comment]
Check out the supportted tags.

https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.0.0/ReleaseNotes/v2.2.0/README.md#welcome-back-the-kmloverlay

**Comment by wf9a5m75** [comment]
>On the other hand it is strange that it not returns any error, if there are a unsupported attribute it should be crash no?

If you have a claim, please send a pull request

**Comment by srinivasarao-d** [comment]
Hi 
The map is not showing it's showing the empty page with Google logo at the bottom, can you please us what could be the problem
Thanks

**Comment by wf9a5m75** [comment]
@srinivasarao-d Do not jump in to not related topics. **It is bad manner.**

The reason of gray map is your api key is not correct.
You did either:
- create the maps api keys **before** enable the maps apis, or
- you didn't specify your api keys.

You need to generate api keys **AFTER** enabling the maps APIs.
https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/api_key/generate_api_key.md

In order to solve the problem, regenerate your api keys, and reinstall the maps plugin.
