### ISSUE TITLE
on scrolling above the map grey  background is shown not the map rotation

### ISSUE THREAD

**Issue by Deliph13** [ionic-team/ionic-native-google-maps#132]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please take a video

**Comment by Deliph13** [comment]
![screenshot-192 168 1 16-8100-2018 12 01-11-15-24](https://user-images.githubusercontent.com/38494425/49324770-a2ae6500-f55a-11e8-8736-48c01ec4f34d.png)

**Comment by wf9a5m75** [comment]
This is not bug. This is default behavior of Google Maps JavaScript v3.
Because you set zoom 0.

**Comment by wf9a5m75** [comment]
You asked only `grey background`, that's why I asked only about that.
