### ISSUE TITLE
Goole Maps Error

### ISSUE THREAD

**Issue by SedkiHergli** [ionic-team/ionic-native-google-maps#139]
Hi there,
I have a problem when i try to show my map, this is the error : 
ERROR Error: [GoogleMaps]You need to execute "$> ionic cordova run browser"."$> ionic serve" is not supported. at Function.push../node_modules/@ionic-native/google-maps/index.js.GoogleMaps.create (index.js:235)

**Comment by wf9a5m75** [comment]
You need to follow the error message.

**Comment by SedkiHergli** [comment]
Thank you :) I resolve it
