### ISSUE TITLE
getMyLocation is never rejected

### ISSUE THREAD

**Issue by TheDuc** [ionic-team/ionic-native-google-maps#14]
When a user declines location permission, the getMyLocation promise is not rejected.
The LocationService has support for this, but the reject function is not passed.

static getMyLocation(options?: MyLocationOptions): Promise<MyLocation> {
    return new Promise<MyLocation>((resolve, reject) => {
      GoogleMaps.getPlugin().LocationService.getMyLocation(options, resolve);
    });
  }

I created a pull request with a fix #15

**Comment by wf9a5m75** [comment]
Thank you for your contribution.
