### ISSUE TITLE
Cannot read property 'getDiv' of undefined

### ISSUE THREAD

**Issue by think4ideas** [ionic-team/ionic-native-google-maps#140]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ X] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.5.0-beta-20181030-1133 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"


**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
<!-- Describe how the bug manifests. -->
Not laoding map anymore

**Expected behavior:**
<!-- Describe what the behavior would be without the bug. -->

**Screen capture or video record:**
<!--
Please take a screen capture or a screen record. You can upload your files with drag & drop up to 10M bytes.
[Android]
$> adb shell screenrecord /sdcard/capture.mp4
$> adb pull /sdcard/capture.mp4 ./
![screenshot from 2018-12-10 15-27-57](https://user-images.githubusercontent.com/4951813/49725432-abf1ad00-fc91-11e8-8f7a-75df6406de32.png)
![screenshot from 2018-12-10 15-27-57](https://user-images.githubusercontent.com/4951813/49725481-c9267b80-fc91-11e8-9faa-60d29d4efe07.png)


[iOS]
Use QuickTimer player on Mac
--->

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Without hints, what can I help you?

**Comment by malsaro** [comment]
Give your div width and height so that some space is allocated for your map to be displayed on.
That should solve your issue.
