### ISSUE TITLE
App Crash on iOS

### ISSUE THREAD

**Issue by tamilvicky17** [ionic-team/ionic-native-google-maps#146]
Hi,
     App crashes while loading google map. I written code in about page.

please help me
https://github.com/tamilvicky17/myApp

**Comment by wf9a5m75** [comment]
You need to follow the implementation guide at least.
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.p

**Comment by wf9a5m75** [comment]
That's not related.

**Comment by tamilvicky17** [comment]
please help me. There is no issue in android with plugin works well in android. I am getting error in IOS only.

**Comment by wf9a5m75** [comment]
Unfortunately I have been super busy these days.

**Comment by wf9a5m75** [comment]
Try following commands:

```

cd platforms/iOS

pod install

```

**Comment by tamilvicky17** [comment]
Thanks for your support. I fixed the issue
