### ISSUE TITLE
Incorrection of info about GoogleMapControlOptions in docs

### ISSUE THREAD

**Issue by ziyaddin** [ionic-team/ionic-native-google-maps#151]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

Hello, I guess there are two mistakes in docs:
1. https://github.com/ionic-team/ionic-native-google-maps/tree/master/documents/googlemapcontroloptions link is intended for info about `GoogleMapControlOptions` but it shows info about `GoogleMapGestureOptions`;
2. https://github.com/ionic-team/ionic-native-google-maps/tree/master/documents/googlemapgestureopitions link refers to the document with incorrect filename and shows info about `GoogleMapControlOptions`. I think this document should be removed and its content should be moved to the document mentioned in first point.

**Comment by wf9a5m75** [comment]
If you find document mistake, please send a pull request

**Comment by ziyaddin** [comment]
Sure, I will.

**Comment by wf9a5m75** [comment]
Thanks
