### ISSUE TITLE
Change position of myLocationButton

### ISSUE THREAD

**Issue by ziyaddin** [ionic-team/ionic-native-google-maps#153]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

Is it possible to change position of myLocationButton over map? For example, putting it on bottom right side of map.

**Comment by wf9a5m75** [comment]
Unfortunately there is no way
