### ISSUE TITLE
map doesn't render on android, using angular 7.x

### ISSUE THREAD

**Issue by cromdev** [ionic-team/ionic-native-google-maps#154]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
    "@ionic-native/core": "5.0.0-beta.22",
    "@ionic-native/google-maps": "5.0.0-beta.22",

**Current behavior:**
After running `ionic cordova run android` (using either emulator or real device) it launches app correctly, but map isn't visible in designated div. No errors visible in console, nor while building.
Other actions, like `GoogleMaps.getMyLocation()`, work fine (it displays current location in console on button tap).
Browser environment works fine.
iOS environment not tested.

**Expected behavior:**
Map rendered correctly in designated div.

**Related code, data or error log (please format your code or data):**
https://github.com/cromdev/ionic-native-google-maps-issue-1
**GoogleMaps API key not included in repo**

**Comment by wf9a5m75** [comment]
Follow the tutorial.

https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000

**Comment by cromdev** [comment]
Unfortunately app created based on this tutorial behaves exactly same as my demo app - works fine in browser but doesn't show map on android emulator nor device.

Thanks for tutorial link though, gives wider view for other features.

If you have repo of working sample based on this tutorial (with `"@angular/common": "~7.1.4"` in package.json), please share.

**Comment by wf9a5m75** [comment]
I confirmed there is no problem if you install `cordova-plugin-googlemaps` from multiple_maps.

![capture](https://user-images.githubusercontent.com/167831/50541806-4abb4c00-0b62-11e9-975e-f291a660d8b6.png)

**Comment by cromdev** [comment]
Problem solved, I can confirm on my side. Works perfectly with `multiple_maps` branch
Thanks for help!
