### ISSUE TITLE
Ionic v1 installation with native google maps

### ISSUE THREAD

**Issue by iChuaNz** [ionic-team/ionic-native-google-maps#155]
After google have increase the price of "google map javascript api" I plan to switch to "Mobile Native Google Map" isit possible to install for ionic1 ? coz my current project is ionic v1.

**Comment by iChuaNz** [comment]
i tried to find any article or guide on ionic mobile native google map. but most of them are ionic 3 or 4. cant really get ionic 1

**Comment by wf9a5m75** [comment]
Some ionic user use cordova-plugin-googlemaps in ionic v1 directly, not ionic-native/google-maps.

**Comment by iChuaNz** [comment]
> Some ionic user use cordova-plugin-googlemaps in ionic v1 directly, not ionic-native/google-maps.

i see I'll gv it a try
