### ISSUE TITLE
Gif Marker Animation

### ISSUE THREAD

**Issue by cchvuth** [ionic-team/ionic-native-google-maps#157]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x] feature request

Would you shed some of your time making gif marker animate? I volunteered to build an app for the public that requires the gif to animate. Thank you so much.

**Comment by wf9a5m75** [comment]
Not possible technically.  Marker icon is drawn as bitmap in the Android/iOS SDKs.

Please ask to Google.

**Comment by LiamKarlMitchell** [comment]
Workaround: Get each frame of the gif as it's own image e.g. png, update marker icon on timeout to each image. But you have no control over the animation speed like that.
