### ISSUE TITLE
White map on iOS

### ISSUE THREAD

**Issue by clodbrasilino** [ionic-team/ionic-native-google-maps#159]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^5.0.0-beta.22",
"@ionic-native/geolocation": "^5.0.0-beta.23",
"@ionic-native/google-maps": "^5.0.0-beta.25",
"@ionic-native/splash-screen": "5.0.0-beta.21",
"@ionic-native/status-bar": "^5.0.0-beta.23",
```
**Current behavior:**
White map problem just as in #94. For Android the steps there solved. In iOS did not work out. I tried a lot of experiences on web inspector changing the css to make it work, but no success. tried setting `--background: transparent !important` and `background: transparent !important` on most of my elements but failed. All that is shown is a white div.

I also checked the API keys working ok (browser and android). They're not restricted yet.

**Expected behavior:**
The map should show up.

**Comment by cosnofski** [comment]
Same problem here. But I had a global style set in app.scss. Commenting it out fixed the issue for me

.fixed-content {
/* background-color: white; */
}

**Comment by clodbrasilino** [comment]
I figured out the reason. I was using a wrong CSS property for changing background.

setting the variable `--ion-background-color` solved the problem.

May this post stay here to help others with the same issue.
