### ISSUE TITLE
ionic native satellite and normal view toggle option

### ISSUE THREAD

**Issue by arghyaExicube** [ionic-team/ionic-native-google-maps#16]
![qp2-map_balloon](https://user-images.githubusercontent.com/34479362/39464838-652b24ea-4d3d-11e8-85ed-4ace7abc50e5.png)
I want this type of toggling between satellite and normal google maps view.
How can I achieve this using ionic native goole maps.
Here is my package.json
"dependencies": {
        "@agm/core": "^1.0.0-beta.2",
        "@angular-redux/form": "^6.7.0",
        "@angular-redux/store": "6.6.0",
        "@angular/animations": "5.2.9",
        "@angular/common": "5.2.9",
        "@angular/compiler": "5.2.9",
        "@angular/compiler-cli": "5.2.9",
        "@angular/core": "5.2.9",
        "@angular/forms": "5.2.9",
        "@angular/http": "5.2.9",
        "@angular/platform-browser": "5.2.9",
        "@angular/platform-browser-dynamic": "5.2.9",
        "@ionic-native/core": "4.6.0",
        "@ionic-native/google-maps": "^4.7.0",
        "@ionic-native/splash-screen": "4.6.0",
        "@ionic-native/status-bar": "4.6.0",
        "@ionic/pro": "1.0.20",
        "@ionic/storage": "2.1.3",
        "@ngx-translate/core": "^9.0.2",
        "@ngx-translate/http-loader": "^2.0.1",
        "@types/redux-persist": "^4.3.1",
        "cordova-android": "^6.2.2",
        "cordova-ios": "4.5.4",
        "cordova-plugin-device": "^2.0.2",
        "cordova-plugin-googlemaps": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#1.3.9",
        "cordova-plugin-ionic-keyboard": "^2.0.5",
        "cordova-plugin-splashscreen": "^5.0.2",
        "cordova-plugin-whitelist": "^1.3.3",
        "ionic-angular": "3.9.2",
        "ionicons": "3.0.0",
        "ramda": "^0.25.0",
        "redux": "3.5.0",
        "redux-logger": "3.0.6",
        "redux-observable": "0.18.0",
        "redux-persist": "^5.9.1",
        "rxjs": "5.5.8",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.20"
    },
    "devDependencies": {
        "@ionic/app-scripts": "3.1.8",
        "typescript": "~2.6.2"
    },
    "description": "An Ionic project",
    "cordova": {
        "plugins": {
            "cordova-plugin-whitelist": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-ionic-keyboard": {}
        },
        "platforms": [
            "android",
            "ios"
        ]
    }
}

my config.xml
<engine name="android" spec="^6.2.2" />
    <engine name="ios" spec="4.5.4" />
    <plugin name="cordova-plugin-device" spec="^2.0.2" />
    <plugin name="cordova-plugin-ionic-keyboard" spec="^2.0.5" />
    <plugin name="cordova-plugin-splashscreen" spec="^5.0.2" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.3" />
Thanks in advance.

**Comment by wf9a5m75** [comment]
Just put image button on the map.

**Comment by wf9a5m75** [comment]
By the way, hiding the Google logo is against the maps apis tos.

**Comment by wf9a5m75** [comment]
Again, **hiding the Google logo is against the maps APIs TOS.**
https://developers.google.com/maps/terms

**Comment by arghya95** [comment]
this is my loadmap function

  loadMap() {
    let options: GoogleMapOptions = {
    
      controls: {
        'compass': true,
        'myLocationButton': true,
        'myLocation': true,   // (blue dot)
        'indoorPicker': true,
        'zoom': true,          // android only
        'mapToolbar': true,     // android only
      },
    
      gestures: {
        scroll: true,
        tilt: true,
        zoom: true,
        rotate: true,
        mapTypeControl:true
      },
    
      styles: [], // https://developers.google.com/maps/documentation/javascript/style-reference
    
      preferences: {
        building: true
      }
    };


    let element = document.getElementById('map');
    let map  = GoogleMaps.create(element, options);
    
    let latlng = new LatLng(22.852833, 88.2548875);
    this.markerName = this.markerdata[0].Title;
    this.markerState = this.markerdata[0].Address;
    this.rec = this.markerdata;
    try{
      if(this.sataliteMap==true){
        console.log("true"+this.sataliteMap)
        this.zone.run(()=>{
          map.setMapTypeId(GoogleMapsMapTypeId.SATELLITE);
        })
       
      }else{
        this.zone.run(()=>{
          map.setMapTypeId(GoogleMapsMapTypeId.NORMAL);
        })
        console.log("false"+this.sataliteMap)
        
      }
    }catch(e){
      console.log(e)
    }


    this.satellite = true;
    map.one(GoogleMapsEvent.MAP_READY).then(() => {
      console.log('Map Is Ready....');

      let position: CameraPosition<Object> = {
          target: latlng,
          zoom: 4,
          tilt: 30
        }
        map.moveCamera(position);



        for(var i=0;i<this.markerdata.length;i++){
          let coordinates: LatLng = new LatLng(this.markerdata[i].LocationX, this.markerdata[i].LocationY);
            let markerOptions: MarkerOptions = {
              position: {
                lat: this.markerdata[i].LocationX,
                lng: this.markerdata[i].LocationY
              },
              title: this.markerdata[i].Title,
              icon: (this.markerdata[i].Risk.Title=='High')?'red':((this.markerdata[i].Risk.Title=='Medium')?'yellow':'green'),
              animation: GoogleMapsAnimation.BOUNCE,
              draggable: false
            };
            map.addMarker(markerOptions)
           
            .then((marker: Marker) => {
  
          marker.addEventListener(GoogleMapsEvent.INFO_CLICK)
          .subscribe((params) => {
            console.log(params[0]);
            console.log(params[0].get('title'));
 
            this.rec = this.markerdata.filter(v=>v.name==params[0].get('title'));
            this.markerName = this.rec[0].Title;
            this.markerState = this.rec[0].Address;
            console.log(this.rec)

            });
        });
      }
      
    });
   

  }


and this is my button for changing  NORMAL to SATELLITE


  change(){
    if(this.sataliteMap==false){
      this.sataliteMap=true;
      this.zone.run(()=>{
        this.loadMap();
      })
      
    }else{
      this.sataliteMap=false;
      this.zone.run(()=>{
        this.loadMap();
      })
    }

  }

and this is HTML

<div id="map">
    <ion-footer>
    <button (click)="change()">change Map type</button>
    </ion-footer>
  </div>

**Comment by arghya95** [comment]
i'm not hiding google logo . don't worry

**Comment by wf9a5m75** [comment]
```typescript
map: GoogleMap;
sataliteMap: boolean = false;

loadMap() {
  options = {...};
  this.map = GoogleMaps.create('map', options);
  this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
    console.log('Map Is Ready....');
    ...
  });
}

change(){
    if (this.sataliteMap) {
      this.map.setMapTypeId(GoogleMapsMapTypeId.NORMAL);
    } else {
      this.map.setMapTypeId(GoogleMapsMapTypeId. SATELLITE);
   }
   this.sataliteMap = !this.sataliteMap;
}
```

**Comment by arghya95** [comment]
not working
@wf9a5m75

**Comment by arghya95** [comment]
now even android  also not working @wf9a5m75

**Comment by wf9a5m75** [comment]
Do your best.

**Comment by wf9a5m75** [comment]
ping
