### ISSUE TITLE
 Uncaught TypeError: Object(...) is not a function in google-maps/index.js

### ISSUE THREAD

**Issue by schetan** [ionic-team/ionic-native-google-maps#166]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [ ] **iOS**
- [ x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.5.0 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.2 "cordova-plugin-ionic-webview"
cordova-plugin-mauron85-background-geolocation 2.3.6 "CDVBackgroundGeolocation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
    "@ionic-native/core": "^5.0.0",
    "@ionic-native/geolocation": "^5.0.0-beta.22",
    "@ionic-native/google-maps": "^4.20.0",
    "@ionic-native/splash-screen": "5.0.0-beta.21",
    "@ionic-native/status-bar": "5.0.0-beta.21",
    "@ionic/angular": "4.0.0-rc.0",
    "@ionic/storage": "^2.2.0",
    "angular": "^1.7.5",
    "cordova-android": "7.1.4",
    "cordova-browser": "5.0.4",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-googlemaps": "2.5.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^2.3.2",
    "cordova-plugin-mauron85-background-geolocation": "^2.3.6",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "cordova-sqlite-storage": "^2.6.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "rxjs-compat": "^6.4.0",
    "zone.js": "~0.8.26"

**Current behavior:**
On following the demo example (of home page),
getting a TypeErrorr from google-maps/index.js 

**Expected behavior:**
should successfully load and display the map.

**Screen capture or video record:**
![selection_007](https://user-images.githubusercontent.com/1989365/52160618-01b96300-26df-11e9-9237-b49a32131a8f.png)

**Related code, data or error log (please format your code or data):**

index.js:152 Uncaught TypeError: Object(...) is not a function
    at index.js:152
    at Module../node_modules/@ionic-native/google-maps/index.js (index.js:182)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/app.module.ts (app.component.ts:14)
    at __webpack_require__ (bootstrap:83)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:83)
    at Object.0 (main.ts:12)
    at __webpack_require__ (bootstrap:83)
    at checkDeferredModules (bootstrap:45)
bootstrap.js:10 
```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by schetan** [comment]
I retried the demo (copied the all of the code instead of mine) and it worked as shown.

Apologies for creating noise here. 
Can i delete or close this issue?

**Comment by wf9a5m75** [comment]
Okay
