### ISSUE TITLE
Maps is not working inside Modals - Element not found error. 

### ISSUE THREAD

**Issue by arihantdaga** [ionic-team/ionic-native-google-maps#172]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x] any problem or bug report
- [ x] feature request

**Current behavior:**
Loading Map in a modal. Currently if `this.map = GoogleMaps.create('map_canvas');` is called inside a modal, it throws an error -` Error: Can not find the element [#map_canvas]` While it is written in corresponding modal HTML file. 
**Expected behavior:**
I suspect it is because TARGET_ELEMENT_FINDING_QUERYS 
 in this line containing only `'ion-router-outlet #', '.show-page #',`. Whilehttps://github.com/ionic-team/ionic-native-google-maps/blob/bb604e0cad658872adb1ab060b9489a9b8ec7e98/src/%40ionic-native/plugins/google-maps/index.ts#L14 
If we can add `.show-modal` in this, i think we can use this in modal as well. 
I might be wrong, but if i am not understanding wrong, there is no harm in using map in Modals, Right ?

**Comment by wf9a5m75** [comment]
This plugin does not work in a modal.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/#how-does-this-plugin-work-android-ios

**Comment by fatma-mohamed** [comment]
I had the same issue. Changing to the below versions and re-installing made it work:
`      
 "@ionic-native/core": "^5.5.0",
"@ionic-native/google-maps": "^5.5.0"
`

**Comment by thepianist2** [comment]
Try remove background color to ion-content, this working for me.
