### ISSUE TITLE
A white screen after install this plugin

### ISSUE THREAD

**Issue by mohamedbrahimi** [ionic-team/ionic-native-google-maps#175]
After the installation of this plugin i try to build my app but i have always a white screen.

**Comment by ndrake** [comment]
Are you running in a browser, simulator or on a real device?  Are you getting any error messages in console?  Did you set your iOS and Android API keys?

**Comment by wf9a5m75** [comment]
@mohamedbrahimi This plugin does not work in a modal.

**Comment by wf9a5m75** [comment]
Ping

**Comment by omkarkhalipe** [comment]
It happens when you create map inside constructor

**Comment by wf9a5m75** [comment]
You have to create a map after platform ready

**Comment by wf9a5m75** [comment]
@mohamedbrahimi ping

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.
