### ISSUE TITLE
 draggable:true not working on android device

### ISSUE THREAD

**Issue by utpaul** [ionic-team/ionic-native-google-maps#178]
I'm using  ionic 3 apps. But marker  draggable is not working.

```
    this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
      this.mapReady = true;
      this.map.addMarker({
        title: 'Ionic',
        icon: 'blue',
        animation: 'DROP',
        draggable:true,
        position: {
          lat: CAMERA_DEFAULT_LAT,
          lng: CAMERA_DEFAULT_LONG
        }
      }).then((marker:Marker)=>{
          marker.showInfoWindow();
          marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
            alert('clicked');
          });
      })
    });
```

**Comment by battika** [comment]
I can see the same thing, my sample project is updated

https://github.com/battika/ionic-gmaps-test

Press the Add marker button on the bottom and try dragging the green marker. It drags the entire map, not the marker.

**Comment by utpaul** [comment]
@battika you are right . Need to fix this . If possible then you resolve it

**Comment by battika** [comment]
Sorry I don't really know the reason, just provided a sample for further investigation.

**Comment by wf9a5m75** [comment]
I have no problem at all.
![capture](https://user-images.githubusercontent.com/167831/53132141-ad5a1400-3523-11e9-9a3a-2c30c3d7af31.gif)

**Comment by wf9a5m75** [comment]
ping

**Comment by utpaul** [comment]
Can you share your code @wf9a5m75

**Comment by wf9a5m75** [comment]
I just run @battika's code

**Comment by battika** [comment]
I guess it will another emulator issue. Masashi, I assume you tried on a real device.

**Comment by utpaul** [comment]
<plugin name="cordova-plugin-googlemaps" spec="2.5.1">
        <variable name="API_KEY_FOR_ANDROID" value="key" />
        <variable name="API_KEY_FOR_IOS" value="key" />
        <variable name="PLAY_SERVICES_VERSION" value="15.0.1" />
        <variable name="ANDROID_SUPPORT_V4_VERSION" value="27.+" />
    </plugin>
    <engine name="android" spec="7.1.4" />

and "@ionic-native/google-maps": "^4.21.0" 
draggable not work 

```
 this.map.one(GoogleMapsEvent.MAP_READY).then(() => {
      this.mapReady = true;
      this.map.addMarker({
        title: 'Ionic',
        icon: 'blue',
        animation: 'DROP',
        draggable:true,
        position: {
          lat: CAMERA_DEFAULT_LAT,
          lng: CAMERA_DEFAULT_LONG
        }
      }).then((marker:Marker)=>{
        marker.showInfoWindow();
        marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
          alert('clicked');
        });

        marker.addEventListener(GoogleMapsEvent.MAP_DRAG).subscribe((event)=>{
          alert('drag');
        })

      })

    });
```

**Comment by wf9a5m75** [comment]
His project uses the same conditions with you.

https://github.com/battika/ionic-gmaps-test/blob/master/package.json

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository. Otherwise we can not help you further ( in that case , I will close this thread).

**Comment by utpaul** [comment]
repo link [](https://github.com/utpaul/google-maps-test) 

i'm testing on nokia 6 version pie

**Comment by wf9a5m75** [comment]
![drag](https://user-images.githubusercontent.com/167831/53291726-c0abf000-376c-11e9-9602-24ee2e6190d4.gif)

**Comment by utpaul** [comment]
i will check it my pie 9 on real device but not work ...

**Comment by wf9a5m75** [comment]
I did test your code and  @battika's  code a lot on both emulator and real device.

I didn't change the code of the property around recently.
If it's real bug, I should receive more craimes.
However only you.
Thus, I don't think this is a bug.

I don't want to waste my private time furthermore for you.
At least you should test another device.

**Comment by utpaul** [comment]
tnx @wf9a5m75 for giving us such a valuable time.
