### ISSUE TITLE
How dows affect this announcement to the plugin?

### ISSUE THREAD

**Issue by Hanzofm** [ionic-team/ionic-native-google-maps#18]
Yesterday, Google announces [this](https://mapsplatform.googleblog.com/2018/05/introducing-google-maps-platform.html?utm_source=em-anncmt&utm_medium=em&utm_campaign=fy18-q2-global-adhoc-email-cs-maps_none_maps_spicestandardplannobilling&utm_content=global%7Cen%7Chybr%7C%7C%7C%7C%7C%7C)

Where is positioned the ionic wrapper of cordova google maps on this price table?

https://cloud.google.com/maps-platform/pricing/sheet/

Mobile Native Dynamic Maps?

Thanks for your time

**Comment by wf9a5m75** [comment]
The maps plugin uses Google Maps Android API v2 and Google Maps SDK for iOS, which have unlimited usage (so far).
It is not affected to this plugin at all.
