### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by NiekvR** [ionic-team/ionic-native-google-maps#181]
**I'm submitting a:**
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**
- [ ] **Android**
- [ ] **iOS**
- [x] **Browser**

**cordova information:**
_com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 2.0.1 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.2.5 "cordova-plugin-googlemaps"
cordova-plugin-ionic 5.3.0 "cordova-plugin-ionic"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.0 "cordova-plugin-ionic-webview"
cordova-plugin-secure-storage 2.6.8 "SecureStorage"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"_

**using:**
"@angular/common": "7.2.6",
    "@angular/compiler": "7.2.6",
    "@angular/compiler-cli": "7.2.6",
    "@angular/core": "7.2.6",
    "@angular/forms": "7.2.6",
    "@angular/http": "7.2.6",
    "@angular/platform-browser": "7.2.6",
    "@angular/platform-browser-dynamic": "7.2.6",
    "@ionic-native/camera": "^5.2.0",
    "@ionic-native/core": "^5.2.0",
    "@ionic-native/geolocation": "5.2.0",
    "@ionic-native/google-maps": "^4.21.0",
    "@ionic-native/secure-storage": "^5.2.0",
    "@ionic-native/splash-screen": "5.2.0",
    "@ionic-native/status-bar": "5.2.0",
    "@ionic/pro": "2.0.4",
    "@ionic/storage": "2.2.0",
    "cordova-android": "^8.0.0",
    "cordova-ios": "^5.0.0",
    "cordova-plugin-camera": "^4.0.3",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-file": "^6.0.1",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-googlemaps": "^2.5.1",
    "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.6.0",
    "cordova-plugin-ionic": "^5.3.0",
    "cordova-plugin-ionic-keyboard": "^2.1.3",
    "cordova-plugin-ionic-webview": "^4.0.0",
    "cordova-plugin-secure-storage": "^3.0.1",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.4",
    "ionicons": "4.5.5",
    "rxjs": "6.4.0",
    "rxjs-compat": "^6.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.29"

**Current behavior:**
Updated application to ionic 5, everything works fine except the @ionic-native/google-maps plugin. Running ionic serve, it runs into an error:
<img width="481" alt="screenshot 2019-02-24 at 18 01 31" src="https://user-images.githubusercontent.com/18706781/53302438-478cc580-385e-11e9-9f1d-8ad901b8cb7b.png">

Console:
Uncaught TypeError: Object(...) is not a function
    at index.js:152 **==>> @Ionic-native/google-maps/index.js**
    at Object.<anonymous> (index.js:182)
    at __webpack_require__ (bootstrap 66a6955fd0e13c7b8511:54)
    at Object.263 (main.js:287)
    at __webpack_require__ (bootstrap 66a6955fd0e13c7b8511:54)
    at Object.149 (main.js:10)
    at __webpack_require__ (bootstrap 66a6955fd0e13c7b8511:54)
    at Object.425 (app.module.ts:81)
    at __webpack_require__ (bootstrap 66a6955fd0e13c7b8511:54)
    at Object.384 (main.ts:5)

When I remove the library I can run the application without a issue.

I thought it might be an issue with rxjs v6, so I installed rxjs-compat, but that did not help.

**Expected behavior:**
My application should run without errors ;-)

I hope you can help me.

Kind regards Niek

**Comment by wf9a5m75** [comment]
Please upgrade this plugin before asking. I don't support older versions.
