### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by damon-leong** [ionic-team/ionic-native-google-maps#182]
Uncaught TypeError: Object(...) is not a function

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-plugin-contacts 3.0.1 "Contacts"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.5.2 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 7.0.0 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
```

using:
"@angular/common": "^7.2.2",
    "@angular/core": "^7.2.2",
    "@angular/forms": "^7.2.2",
    "@angular/http": "^7.2.2",
    "@angular/platform-browser": "^7.2.2",
    "@angular/platform-browser-dynamic": "^7.2.2",
    "@angular/router": "^7.2.2",
    "@ionic-native/contacts": "^5.2.0",
    "@ionic-native/core": "^5.2.0",
    "@ionic-native/facebook": "^5.2.0",
    "@ionic-native/firebase": "^5.2.0",
    "@ionic-native/geolocation": "^5.2.0",
    "@ionic-native/google-maps": "^4.21.0",
    "@ionic-native/google-plus": "^5.2.0",
    "@ionic-native/in-app-browser": "^5.2.0",
    "@ionic-native/sms": "^5.2.0",
    "@ionic-native/social-sharing": "^5.2.0",
    "@ionic-native/splash-screen": "^5.0.0",
    "@ionic-native/status-bar": "^5.0.0",
    "@ionic/angular": "^4.0.0",
    "@ionic/pro": "2.0.4",
    "@ionic/storage": "^2.2.0",
    "@ngx-translate/core": "^9.1.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "angularfire2": "^5.1.1",
    "cordova-plugin-contacts": "^3.0.1",
    "cordova-plugin-facebook4": "^4.2.1",
    "cordova-plugin-firebase": "^2.0.5",
    "cordova-plugin-geolocation": "^4.0.1",
    "cordova-plugin-googlemaps": "^2.5.2",
    "cordova-plugin-googleplus": "^7.0.0",
    "cordova-plugin-inappbrowser": "^3.0.0",
    "cordova-plugin-x-socialsharing": "^5.4.4",
    "cordova-sms-plugin": "^1.0.0",
    "core-js": "^2.5.4",
    "firebase": "^5.8.3",
    "promise-polyfill": "^8.1.0",
    "rxjs": "^6.4.0",
    "rxjs-compat": "^6.4.0",
    "zone.js": "~0.8.29"

**Current behavior:**
there is error when ionic serve start the application

Uncaught TypeError: Object(...) is not a function
    at index.js:152
    at Module../node_modules/@ionic-native/google-maps/index.js (index.js:182)
    at __webpack_require__ (bootstrap:83)
    at Module../src/app/app.module.ts (app.component.ts:15)
    at __webpack_require__ (bootstrap:83)
    at Module../src/main.ts (main.ts:1)
    at __webpack_require__ (bootstrap:83)
    at Object.0 (auth.ts:18)
    at __webpack_require__ (bootstrap:83)
    at checkDeferredModules (bootstrap:45)

Ionic:
   ionic (Ionic CLI)             : 4.10.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.0.2
   @angular-devkit/build-angular : 0.12.4
   @angular-devkit/schematics    : 7.2.4
   @angular/cli                  : 7.2.4
   @ionic/angular-toolkit        : 1.4.0

Cordova:
   cordova (Cordova CLI) : 7.1.0
   Cordova Platforms     : none
   Cordova Plugins       : no whitelisted plugins (1 plugins total)

**Expected behavior:**
should be no error when ionic serve 

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
`"@ionic-native/google-maps": "^4.21.0"` is incorrect.

Use `@ionic-native/google-maps@5.x` for ionic4

**Comment by ShaneCotter** [comment]
> `"@ionic-native/google-maps": "^4.21.0"` is incorrect.
> 
> Use `@ionic-native/google-maps@5.x` for ionic4

Hi, I have the same issue but when I try to install the latest version using: 
npm install --save @ionic-native/core@latest @ionic-native/google-maps@latest
It still installs 4.21.0

**Comment by kapilSoni101** [comment]
@wf9a5m75  sir i have used  "@ionic-native/google-maps": "^5.5.0" but got error after launch applicaiton?

**Comment by Heckthor** [comment]
> @wf9a5m75 sir i have used "@ionic-native/google-maps": "^5.5.0" but got error after launch applicaiton?

Did you figure it out? If you're still using Ionic v3 you actually **NEED** version 4.21.0

**Comment by kapilSoni101** [comment]
@heckthor : i have above issue after 2nd day the comment.i have remove plugin amd used javascript map sdk instead of plugin.

**Comment by lilhamad** [comment]
It once happened to me and I solve it by adding @beta when installing the dependency.
e.g
npm install @ionic-native/google-maps@beta
instead of 
 npm install @ionic-native/google-maps@5.x
