### ISSUE TITLE
 addEventListener is not a function on Marker

### ISSUE THREAD

**Issue by stefdelec** [ionic-team/ionic-native-google-maps#188]
- [ x ] question
- [ x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

cordova-background-geolocation-lt 2.14.2 "BackgroundGeolocation"
cordova-ios-plugin-no-export-compliance 0.0.5 "iOS No Export Compliance"
cordova-plugin-background-fetch 5.4.1 "CDVBackgroundFetch"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-orientation 2.0.1 "Device Orientation"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.5.2 "cordova-plugin-googlemaps"
cordova-plugin-insomnia 4.3.0 "Insomnia (prevent screen sleep)"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.5 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-vibration 3.1.0 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.5.2 "Cordova sqlite storage plugin"

    
"@ionic-native/google-maps": "^4.21.0",

When I create a Marker, there is no addEventListener property.

```
new Marker(this.map,{})).addEventListener('click')
// Error addEventListener is not a function
```

**Comment by wf9a5m75** [comment]
Please study before using this plugin.

https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.p

**Comment by stefdelec** [comment]
Thanks.
I look directly at typescript, and it was misleading.
