### ISSUE TITLE
Will be blank screen with TileOverlay in case the map page is loaded as a main page by lazy loading

### ISSUE THREAD

**Issue by JeongJun-Lee** [ionic-team/ionic-native-google-maps#190]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/core": "4.14.0",
"@ionic-native/google-maps": "^4.21.0",

**Current behavior:**

Will be blank screen with TileOverlay in case the map page is loaded as a main page by lazy loading
This issue is similar to https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2396  

**Expected behavior:**

 the map page is loaded as a main page by lazy loading should be seen well, not a blank.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository.

**Comment by JeongJun-Lee** [comment]
https://github.com/JeongJun-Lee/ionic3-gmap-overlay

**Comment by wf9a5m75** [comment]
ping

**Comment by JeongJun-Lee** [comment]
@wf9a5m75 I already shared my repo. Still I can't solve this issue. Could you give a comment to solve it?

**Comment by wf9a5m75** [comment]
Sorry for long waiting. I was busy.

I checked your code. First, you specify `"assets/tiles/" + zoom + "/" + x + "/" + y + ".png"`, 
https://github.com/JeongJun-Lee/ionic3-gmap-overlay/blob/master/src/pages/map/map.ts#L56

but there is no file at https://github.com/JeongJun-Lee/ionic3-gmap-overlay/tree/master/src/assets

Please example tile files.

**Comment by JeongJun-Lee** [comment]
Thank you for you help even you're busy.

I pushed the tiles just now.

**Comment by JeongJun-Lee** [comment]
It'll happen only at real device, not browser.

**Comment by wf9a5m75** [comment]
![Screen Shot 2019-04-16 at 2 00 03 PM](https://user-images.githubusercontent.com/167831/56243761-3ab37380-6050-11e9-900d-21005c594d93.png)
![Screen Shot 2019-04-16 at 2 00 09 PM](https://user-images.githubusercontent.com/167831/56243762-3ab37380-6050-11e9-9671-398c58e18f76.png)

**Comment by wf9a5m75** [comment]
```css
page-map {   <--- This should be `page-map` instead of `page-home`
  #map_canvas {
    height: 100%;
  }
}
```
![capture](https://user-images.githubusercontent.com/167831/56243882-7f3f0f00-6050-11e9-80f7-0e11e10e93df.png)


https://github.com/JeongJun-Lee/ionic3-gmap-overlay/blob/a28e1cf4ad897a4de2e87c3bdae359cd12ef4abf/src/pages/map/map.scss

**Comment by wf9a5m75** [comment]
Also you should use `addTileOverlaySync` instead of `addTileOverlay` because you don't wait the MAP_READY event.

https://github.com/JeongJun-Lee/ionic3-gmap-overlay/blob/a28e1cf4ad897a4de2e87c3bdae359cd12ef4abf/src/pages/map/map.ts#L50-L58

**Comment by wf9a5m75** [comment]
I'm further inspecting.

**Comment by JeongJun-Lee** [comment]
Thanks. I changed page-home to page-map and addTileOverlaySync also. But still shows blank.

**Comment by wf9a5m75** [comment]
Okay, I got the reason why your app can't display the tile images.
Because the index.html is hosted on `file:` protocol.
Most of cases, ionic runs on `http:` protocol.
I tested a lot (maybe on `http:` protocol). That's why other people works.
But for the code for `file:` does not work well with ionic3.

I changed this plugin's code. So, please reinstall `cordova-plugin-googlemaps` from the `multiple_maps` branch.

![capture](https://user-images.githubusercontent.com/167831/56247737-aa2e6080-605a-11e9-8ac6-3e725386df2e.png)

**Comment by JeongJun-Lee** [comment]
Wow thanks a lat. I am really happy. OK. it's last question. How can i get a branch(mutiple_maps) by npm install?

**Comment by wf9a5m75** [comment]
https://stackoverflow.com/a/49230481/697856

**Comment by JeongJun-Lee** [comment]
Oh. I am sorry, I have a still problem with the git branch. I think the branch was installed rightly. THen how can I debug more?

**Comment by wf9a5m75** [comment]
What are you asking?

**Comment by JeongJun-Lee** [comment]
Still I have same problem even though I reinstalled the plugin with multiple_maps branch which you require to reinstall.

**Comment by wf9a5m75** [comment]
Did you update your repo?

**Comment by JeongJun-Lee** [comment]
Yes, I updated my repo now.

**Comment by wf9a5m75** [comment]
Regarding of the `package-lock.json` file, you installed the plugin from `https://github.com/mapsplugin/cordova-plugin-googlemaps.git#ec8dbfa8a72bb2557f10fe3b3b131fc7219843fd`.

```
    "cordova-plugin-googlemaps": {
      "version": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps.git#ec8dbfa8a72bb2557f10fe3b3b131fc7219843fd"
    },
```
https://github.com/JeongJun-Lee/ionic3-gmap-overlay/blob/17a0f31505ad278b9d5bd54082324f228870795c/package-lock.json#L1789-L1791

--------

Then access to https://github.com/mapsplugin/cordova-plugin-googlemaps.git#ec8dbfa8a72bb2557f10fe3b3b131fc7219843fd with browser.

And check the plugin.xml file. The file has been updated 29 days ago.

![Screen Shot 2019-04-16 at 4 54 01 PM](https://user-images.githubusercontent.com/167831/56251388-4317a880-6068-11e9-8469-d5528f64cf77.png)


--------

Let's check the `multiple_maps` branch.

https://github.com/mapsplugin/cordova-plugin-googlemaps/tree/ec8dbfa8a72bb2557f10fe3b3b131fc7219843fd

![Screen Shot 2019-04-16 at 4 55 01 PM](https://user-images.githubusercontent.com/167831/56251418-65112b00-6068-11e9-855e-74690c426678.png)

**Comment by wf9a5m75** [comment]
Can you show me the output of `cordova plugin list`?

**Comment by JeongJun-Lee** [comment]
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-googlemaps 2.5.4-beta-20190416-1514 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"

**Comment by wf9a5m75** [comment]
Thanks. And also can you show me the output of `cordova platform list`?

**Comment by JeongJun-Lee** [comment]
nstalled platforms:
  android 6.3.0
  browser 5.0.4

**Comment by wf9a5m75** [comment]
Yeah, the `android` platform is old.

**Comment by JeongJun-Lee** [comment]
Yes, I want to go forward @7 at least but fcm plugin requires old play-google-services 10.+

**Comment by wf9a5m75** [comment]
This plugin requires `15.1.0` or above.
https://github.com/mapsplugin/cordova-plugin-googlemaps#install-optional-variables

**Comment by wf9a5m75** [comment]
I just cloned your repo, and run it.
![capture](https://user-images.githubusercontent.com/167831/56252303-02ba2980-606c-11e9-97b8-1761673250cf.png)

**Comment by wf9a5m75** [comment]
Please try to reinstall the platform:

```
$> ionic cordova platform rm android
$> ionic cordova platform add android
```

**Comment by JeongJun-Lee** [comment]
I cannot build error below. 

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> unable to create new native thread

**Comment by wf9a5m75** [comment]
Please past (or link) to all log instead of two lines. I can't guess the reason with only two lines.

**Comment by JeongJun-Lee** [comment]
Running command: /Users/comseong/dev/ionic3/ionic3-gmap-overlay/platforms/android/gradlew cdvBuildDebug -b /Users/comseong/dev/ionic3/ionic3-gmap-overlay/platforms/android/build.gradle -Dorg.gradle.daemon=true -Dorg.gradle.jvmargs=-Xmx2048m

**Comment by wf9a5m75** [comment]
The cordova-plugin-googlemaps v2.6.0 has been released, which fixes the original problem.

**Comment by JeongJun-Lee** [comment]
I succeeded finally the build by cordova-android 8.0 and cordova-plugin-googlemaps v2.6.0, but the map is not shown like before. It shows only blank screen. From which part could I debug it by break- point in the source code?

**Comment by JeongJun-Lee** [comment]
In Ionic4, I still have same problem so I opened new issue(https://github.com/ionic-team/ionic-native-google-maps/issues/215) with new repo.
