### ISSUE TITLE
 Add multiple colors to the polyline

### ISSUE THREAD

**Issue by wuilmerj24** [ionic-team/ionic-native-google-maps#191]
**I'm submitting a ...**  (check one with "x")
- [] question
- [ ] any problem or bug report
- [x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

I explain, I have a polyline and that polyline I would like to add multiple colors at the same time. Similiar when placed in true show traffic.
Is it possible to do that?

**Comment by wf9a5m75** [comment]
Google Maps SDK for Android does not support the feature.

**Comment by wf9a5m75** [comment]
Make multiple polyline for each colors.

**Comment by wuilmerj24** [comment]
@wf9a5m75 Thank you.

if it could be added in the native SDK?

**Comment by wf9a5m75** [comment]
Nope.

**Comment by wf9a5m75** [comment]
The goal of this plugin is to reproduce Google Maps JavaScript v3.
So, the feature you requested is not implemented in Google Maps JavaScript v3, I wont implement it.
