### ISSUE TITLE
Compatibility with @ionic-native/core@5.0.0

### ISSUE THREAD

**Issue by husseinelhussein** [ionic-team/ionic-native-google-maps#192]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [X ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-clipboard 1.2.1 "Clipboard"
cordova-plugin-android-permissions 1.0.0 "Permissions"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-filechooser 1.2.0 "File Chooser"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova.plugins.diagnostic 4.0.12 "Diagnostic"
ionic-plugin-deeplinks 1.0.17 "Ionic Deeplink Plugin"
phonegap-plugin-barcodescanner 8.0.1 "BarcodeScanner"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/core": "^5.0.0"
"@ionic-native/google-maps": "^5.0.0-beta.27",
**Current behavior:**

I'm trying to install the latest ionic-google-maps, but it's not compatible with `@ionic-native/core@5.0.0` or above 
**Expected behavior:**

i'm expecting it to work with `@ionic-native/core@5.0.0` or above
**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
`$ npm install @ionic-native/google-maps@beta
+-- UNMET PEER DEPENDENCY @ionic-native/core@5.0.0
`-- @ionic-native/google-maps@5.0.0-beta.27`
```

**Comment by wf9a5m75** [comment]
Please send a pull request.

**Comment by wf9a5m75** [comment]
Thank you for sending the PR. I will check it today

**Comment by wf9a5m75** [comment]
@ionic-native/google-maps (v5.5.0) has been released.
