### ISSUE TITLE
And you can NOT use this plugin in a modal.

### ISSUE THREAD

**Issue by Benkracker** [ionic-team/ionic-native-google-maps#195]
And you can NOT use this plugin in a modal.

_Originally posted by @wf9a5m75 in https://github.com/ionic-team/ionic-native-google-maps/issues/169#issuecomment-460756552_

WILL YOU PLEASE ADD THIS TO YOUR README!? I just wasted 2 days before finally finding this comment in a closed issue...

**Comment by wf9a5m75** [comment]
Please read all documents before using this plugin.
https://github.com/mapsplugin/cordova-plugin-googlemaps/#how-does-this-plugin-work-android-ios

https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g3e207b82bf_886_16
