### ISSUE TITLE
The application closes when trying to load the map on iOS with ionic 3

### ISSUE THREAD

**Issue by MariaC15** [ionic-team/ionic-native-google-maps#196]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-android-support-gradle-release 2.1.0 "cordova-android-support-gradle-release"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-dialogs 2.0.1 "Notification"
cordova-plugin-facebook4 3.2.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.5.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.4.1 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-toast 2.7.2 "Toast"
cordova-sqlite-storage 2.6.0 "Cordova sqlite storage plugin"

```

`@ionic-native/core: ^4.20.0` and `@ionic-native/google-maps: ^4.21.0`

**Current behavior:**

I have an application where I need to load the map, but it happens that when trying to load the map, the application stops

**Expected behavior:**

You must load the map and show the current location, without stopping the application
**Screen capture or video record:**
![WhatsApp Video 2019-04-01 at 6 23 22 PM](https://user-images.githubusercontent.com/24502186/55447206-65012d80-5588-11e9-813e-2e756c5d582a.gif)

**Related code, data or error log (please format your code or data):**

Ionic info
![ionic-info](https://user-images.githubusercontent.com/24502186/55447350-04bebb80-5589-11e9-8e91-49d8880c2eae.png)

Error
![error](https://user-images.githubusercontent.com/24502186/55447381-21f38a00-5589-11e9-86c4-eaaa31f88c21.png)
 
[https://Mariac15@bitbucket.org/trabajodesarrolladores/user-yugo.git](url)

**Comment by wf9a5m75** [comment]
You didn't install cocoapod

**Comment by MariaC15** [comment]
also install pod and it still does not work

**Comment by wf9a5m75** [comment]
Okay, if you want me to help, please share your project files on GitHub repository. Otherwise please debug by yourself.

**Comment by MariaC15** [comment]
the project is in bitbucket
[https://Mariac15@bitbucket.org/trabajodesarrolladores/user-yugo.git](url)
, if it serves you there? Or you need it on GitHub

**Comment by battika** [comment]
Like I wrote yesterday on a different ticket upgrade Cordova IOS to version
5.0.0. For some reason this plugin no longer works with Cordova IOS version
4.5.5. Masashi any idea why that is?

**Comment by wf9a5m75** [comment]
@MariaC15 please add me to your repo. I was declined due to permission.

@battika I haven't checked Cordova iOS v5 yet. I was so busy. Sorry, I think I miss your comment. Is the same error message as @MariaC15?

**Comment by MariaC15** [comment]
@wf9a5m75  Done, and add the repository to GitHub  [https://github.com/MariaC15/yugo-cliente.git](url)

**Comment by wf9a5m75** [comment]
@battika I tried very [simple code](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/hello-world-phonegap-build/README.md#understanding-the-code) with Cordova v9 & Cordova iOS v5, but it works perfectly.

<img width="469" alt="Screen Shot 2019-04-03 at 11 22 13 PM" src="https://user-images.githubusercontent.com/167831/55533812-5b9ac280-5667-11e9-8311-524812df94f1.png" width="250">

**Comment by wf9a5m75** [comment]
@MariaC15 Please provide test account information. Since I don't know your country phone number, I can't register to your app.

**Comment by MariaC15** [comment]
User  mariacastillop15@gmail.com
Pass 1234

**Comment by battika** [comment]
Masashi, I actually have problems the other way around. This plugin works OK for Cordova-IOS 5.0.0 and no longer working with Cordova-IOS 4.5.5.

See this issue as well where bumping IOS version to 5.0.0 helped:

https://github.com/ionic-team/ionic-native-google-maps/issues/189

**Comment by wf9a5m75** [comment]
Um, as far as I test, no problem.

<img width="300" alt="Screen Shot 2019-04-04 at 11 52 20 PM" src="https://user-images.githubusercontent.com/167831/55609117-ccf47700-5734-11e9-85fd-63a272823feb.png">
<img width="300" alt="Screen Shot 2019-04-04 at 11 52 46 PM" src="https://user-images.githubusercontent.com/167831/55609118-ccf47700-5734-11e9-959a-25a9e5f90e20.png">

**Comment by battika** [comment]
Thanks for testing, let me create a test project and see where it fails.

**Comment by MariaC15** [comment]
Hello, I did tests with cordova ios 5.0.0 load the map, but if I add the
location service does not work, it stays in black

**Comment by wf9a5m75** [comment]
@MariaC15 I will test your app tomorrow. It's midnight in the US. Thank you for waiting.

**Comment by MariaC15** [comment]
Take your time, thank you very much

**Comment by wf9a5m75** [comment]
@MariaC15 I can't log in to your app with your ID/PW.
![196](https://user-images.githubusercontent.com/167831/55666148-27f2a080-57ff-11e9-9fa3-da74b2bfcc3f.gif)

**Comment by MariaC15** [comment]
@wf9a5m75 Sorry, can you try again?
Restart the server

**Comment by MariaC15** [comment]
Hi, you could have reviewed my app?

**Comment by Rejiz** [comment]
Ionic 4 Same problem do you resolve it?

**Comment by wf9a5m75** [comment]
@MariaC15 For some reason, I can't enter your ID/PW at the login page on simulator. Keyboard does not work. Please confirm your code.

**Comment by MariaC15** [comment]
Greetings, press CMD + K

**Comment by wf9a5m75** [comment]
Sometimes work, sometimes does not work.

**Comment by wf9a5m75** [comment]
![ezgif-2-fb02dd3733f9](https://user-images.githubusercontent.com/167831/56513346-0ffd6b00-64e7-11e9-9e9e-39db02c29f32.gif)

**Comment by MariaC15** [comment]
I do not understand why you pass that, my work on the emulator and on the
cell phone, you can try on a cell phone? Or check the emulator configuration

**Comment by wf9a5m75** [comment]
I don't have my iPhone today. I will test your code tomorrow.

**Comment by MariaC15** [comment]
Ok, thanks

**Comment by wf9a5m75** [comment]
I tried on real iPhone SE, but I can't log in.
![Screen Shot 2019-04-23 at 2 57 30 PM](https://user-images.githubusercontent.com/167831/56618668-26cfba80-65d8-11e9-94d9-669ab056d6f5.png)

**Comment by wf9a5m75** [comment]
ping

**Comment by MariaC15** [comment]
Hi I'm checking the app, because I do not generate that mistake that later
I infid you

**Comment by wf9a5m75** [comment]
So, is this problem no longer existed?

**Comment by MariaC15** [comment]
That problem was not there, I still do not solve it, are you compiling as
livereload?

**Comment by wf9a5m75** [comment]
>are you compiling as livereload?

No.

**Comment by MariaC15** [comment]
You know that I work well, it does not give that error, if you can erase
the data from the app and uninstall it and install again?

**Comment by MariaC15** [comment]
Compile with Ionic from the terminal

**Comment by wf9a5m75** [comment]
The problem I asked is I can't log in to your app because of your app bug.
https://user-images.githubusercontent.com/167831/56618668-26cfba80-65d8-11e9-94d9-669ab056d6f5.png

Is this fixed, or not?
I haven't seen the map page in your app yet.

**Comment by MariaC15** [comment]
No, it's not fixed, it's the first time you go with you anything else,
because I've already tried and I work it's well

**Comment by wf9a5m75** [comment]
Is there any update? If no, I would close this thread.

**Comment by MariaC15** [comment]
No, there is no update, I decided to use javascript, close the thread, thanks
