### ISSUE TITLE
pantalla en blanco en Play Store

### ISSUE THREAD

**Issue by jeancarlos2020** [ionic-team/ionic-native-google-maps#199]
A white screen is produced only in this game store, but in debug and in release it works perfectly therefore I do not have a KEY error. (already reviewed the REGISTRY)
the strange thing is that the launch works. What is this problem? any bright idea?

- [x] question
- [x ] any problem or bug report
- [x] feature request

- [x ] **Android**
- [ ] **iOS**
- [ ] **Browser**

cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 2.0.5 "Google Firebase Plugin"
cordova-plugin-googlemaps 2.5.3 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.4.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**Comment by wf9a5m75** [comment]
Please describe in English.

**Comment by jeancarlos2020** [comment]
please help me

**Comment by wf9a5m75** [comment]
So, please explain your issue. I can't read your Language.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this issue.
