### ISSUE TITLE
ionic-googlemaps-quickdemo does not work with default settings

### ISSUE THREAD

**Issue by whitecat** [ionic-team/ionic-native-google-maps#2]
I cloned ionic-googlemaps-quickdemo.

Replaced (REPLACE WITH YOUR APK KEY) in config.xml and package.json files with my Google Maps API keys.

Then I did the following commands:

1. `npm i`
2. `ionic serve`

I got a console error `Native: tried accessing the GoogleMaps plugin but Cordova is not available. Make sure to include cordova.js or run in a device/simulator` 

Which is unexpected as this is a native ionic item. 

I tried again using this command:

1. `ionic cordova run browser -lcs`

But with that the loaded browser gave the following error. `Native: tried accessing the GoogleMaps plugin but it's not installed.`

How can I get native google maps loading?

**Comment by wf9a5m75** [comment]
`ionic serve` and `browser platform` are not supported. And you also need to generate api key before installing.

**Comment by whitecat** [comment]
Yes I generated the API keys.

How does one debug generated code using `android platform`?

**Comment by wf9a5m75** [comment]
https://forum.ionicframework.com/t/android-debug-on-real-device/89261/2

**Comment by whitecat** [comment]
Sadly that does not give you the ability to breakpoint and run console commands. To see the data one is working with.

**Comment by whitecat** [comment]
@wf9a5m75 Thank you for your help though. I will need to use something else to program and test to get my app running then convert it back to use `ionic-native-google-maps`.

I think this repo https://github.com/BrunoAlencar/ionic3-google-maps-examples gives similar functionality and allows me to use browser.  I can port that back to `ionic-native-google-maps` once I am finished.
