### ISSUE TITLE
Map freezes on iOS after touch event 

### ISSUE THREAD

**Issue by communicationbreakdown01** [ionic-team/ionic-native-google-maps#20]
On Android everything works fine but on iOS the screen freezes after the first touch event within the map div. 

> cli packages: (/usr/local/lib/node_modules)
> 
>     @ionic/cli-utils  : 1.19.2
>     ionic (Ionic CLI) : 3.20.0
> 
> global packages:
> 
>     cordova (Cordova CLI) : 8.0.0
> 
> local packages:
> 
>     @ionic/app-scripts : 3.1.8
>     Cordova Platforms  : android 6.4.0 ios 4.5.4
>     Ionic Framework    : ionic-angular 3.9.2
> 
> System:
> 
>     Android SDK Tools : 26.1.1
>     ios-deploy        : 1.9.2
>     Node              : v8.9.4
>     npm               : 5.6.0
>     OS                : macOS High Sierra
>     Xcode             : Xcode 9.3 Build version 9E145
> 
> Environment Variables:
> 
>     ANDROID_HOME : /Users/jlaxa/Library/android/sdk
> 
> Misc:
> 
>     backend : pro

The XCode Debugger shows some timeouts after the touch event, while other interactions with the view are not possible.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this thread.
