### ISSUE TITLE
Modifying MarkerCluster Icon

### ISSUE THREAD

**Issue by Binitronics** [ionic-team/ionic-native-google-maps#200]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [x ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-custom-config 5.0.2 "cordova-custom-config"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.5.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.5 "cordova-plugin-ionic-webview"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/core": "~4.15.0",
 "@ionic-native/google-maps": "^4.21.0"
**Current behavior:**

**Expected behavior:**

    Is there any way to set the icon of the markerclusterer base on other conditions besides min and max? For instance, The MarkerClusterer library of Javascript API has a method know us setCalculator that enable us to modify the icon of the cluster based on other conditions. 
**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
>Is there any way to set the icon of the markerclusterer base on other conditions besides min and max? For instance, The MarkerClusterer library of Javascript API has a method know us setCalculator that enable us to modify the icon of the cluster based on other conditions. 


no.
