### ISSUE TITLE
Not able to set fillOpacity of polygon

### ISSUE THREAD

**Issue by maxakash** [ionic-team/ionic-native-google-maps#201]
I have added fillcolor to my polygon but while fillopacity is not working.
I looked into the plugin and fillopacity doesn't even seem to be a variable or function.
Please help me how to set opacity of fillcolor in polygon.
Thanks

**Comment by wf9a5m75** [comment]
How do you write your code?

**Comment by maxakash** [comment]
this.polygon = this.map.addPolygonSync({
                    points: this.points[item],
                    strokeColor: '#ffd00a',
                    fillColor: 'red',
                    fillOpacity: 0.1,
                    strokeWidth: 6,
                    clickable: true
                });

**Comment by wf9a5m75** [comment]
Where did you find `fillOpacity` property in this document page?
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.3.0/class/Polygon/README.md

**Comment by maxakash** [comment]
I googled it and found it in offical google maps SDK, so i thought maybe it could work.
So, is there any way from your side to set opacity?

**Comment by wf9a5m75** [comment]
This plugin does not provide `fillOpacity` property.

Instead of that, you can specify opacity as `#RRGGBBAA`, or other ways.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v1.4.0/Available-HTML-colors
