### ISSUE TITLE
White screen on iOS 12.2

### ISSUE THREAD

**Issue by fakerLinXiao** [ionic-team/ionic-native-google-maps#202]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "4.18.0",
"@ionic-native/google-maps": "^4.7.0",
```

**Current behavior:**

White screen on iOS 12.2 device.

**Screen capture or video record:**

iOS 
![iOS 10 3](https://user-images.githubusercontent.com/25616054/56269544-7456ae00-6126-11e9-9533-3f05cd60085f.png)

![ios 12 2](https://user-images.githubusercontent.com/25616054/56269557-7b7dbc00-6126-11e9-8b90-a8cb5d29a291.png)

**Comment by wf9a5m75** [comment]
`cordova-plugin-googlemaps 2.3.8 ` is old.
Please use the latest version.
I tested on iOS 12.2 yesterday, but no problem.

**Comment by fakerLinXiao** [comment]
Hi, @wf9a5m75 
Thank you for your replay.

I use the latest version ``` cordova-plugin-googlemaps 2.5.3 ```, but occur new issue: camera is  a frame, the map outside the camera is not displayed.
Like screenshot:

![image](https://user-images.githubusercontent.com/25616054/56350510-835c5f80-61fd-11e9-96c6-80d143bafffa.png)

**Comment by fakerLinXiao** [comment]
All right.  I try the version ``` cordova-plugin-googlemaps 2.5.2, it's work fine.

**Comment by paneb84** [comment]
I have the same problem but i do not resolve yet 
![Simulator Screen Shot - iPhone X - 2019-04-30 at 14 19 14](https://user-images.githubusercontent.com/16491772/56961130-378dac80-6b53-11e9-9dce-b68622ea008a.png)
ios 12.2

no problem in browser:
![browser](https://user-images.githubusercontent.com/16491772/56961434-111c4100-6b54-11e9-8240-5955e7cd2ce3.png)

"@ionic-native/core": "^5.0.0",
"@ionic-native/google-maps": "^5.0.0-beta.27",

cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"


please help me :-)

**Comment by battika** [comment]
I had the same problem with webview 4.0.1 for some reason it does not work with googlemaps for me, but I am still on Ionic 3.

Can you try with "cordova-plugin-ionic-webview": "^2.4.1" ? It already has the IOS 12.2 bug fix in it...

**Comment by Itokoyamato** [comment]
For those still having issues with iOS 12.2, the following worked for us:

`document.body.style.transform = 'rotateZ(0deg)';`

Seems like using transform forces some sort of hardware update
