### ISSUE TITLE
How can i send data from InfoWindow to another page

### ISSUE THREAD

**Issue by Serranosoft** [ionic-team/ionic-native-google-maps#204]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

How can i send data from infoWindow when i click and get that data on another page? I tried to do a forEach for every marker that i have then addEventListener(GoogleMapsEvent.INFO_CLICK) on every marker on that loop where i call a method where i get the data and send to another page but it doesnt work, i did something wrong? sorry for my bad english im using Ionic 4

**Comment by wf9a5m75** [comment]
How did you write your code?

**Comment by Serranosoft** [comment]
Im using Event listeners for every marker where im calling a method which uses events to publish the data and the another page subscribe the data im getting the right data which is an array in console but cant display it i get some help on stackoverflow but nothing works and i suppose that maybe using events to pass data from googlemaps to another page is not correct

you can see some code that i post on stackoverflow [https://stackoverflow.com/questions/55607741/ionic-angular-html-doesnt-display-information-from-ts-file](url)

**Comment by wf9a5m75** [comment]
Unfortunately, I'm not an expert of ionic. Please create a simple project , then share it on Github repository.

**Comment by Serranosoft** [comment]
Oh ok i dont know if its right to do another question but im having troubles with using custom icons on markers 
`if (marker.ic_ruta == null) {
            icon = 'assets/imgs/icono_bebir_mapa_bares.png';
          } else {
            icon = 'http://52.210.18.168/bebir/php/archivos_subidos/' + marker.ic_ruta;
          }`
marker.ic_ruta in this case is _1555935240.png and if you open that url you can see an image why it display like the default icon?(red marker) im using that icon variable here

`map.addMarker({
            'position': coordenadas,
            'title': marker.b_nombre,
            'snippet': marker.b_direccion,
            'icon': icon`

**Comment by wf9a5m75** [comment]
It's various reasons, such as can not access to the image url.

**Comment by Serranosoft** [comment]
http://52.210.18.168/bebir/php/archivos_subidos/_1555935240.png you cant access here?

**Comment by Serranosoft** [comment]
I dont know why but if i use an public image hosting like http://imagizer.imageshack.com/img921/4412/cSxaZ5.png it works but if i use http://52.210.18.168/bebir/php/archivos_subidos/_1555935240.png it doesn't work how can i make it work with my own server

**Comment by Serranosoft** [comment]
Maybe it was very stupid but it worked using my own domain instead ip thanks
