### ISSUE TITLE
Ionic Googlemaps API key for IOS not registered issue

### ISSUE THREAD

**Issue by schagani** [ionic-team/ionic-native-google-maps#208]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
cordova-open-native-settings 1.5.2 "Native settings"
cordova-plugin-camera 4.0.3 "Camera"
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-keyboard 1.2.0 "Keyboard"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 3.2.1-dev "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
I am trying to install the plugin and it shows that the plugin has been installed. However, I am unable to see the entry of the plugin in config.xml
After running it on IOS, it shows me error saying "The variable GOOGLE-MAPS_IOS_API_KEY is not registered"

**Expected behavior:**
The native google maps should work and to be shown in the screen.
<img width="232" alt="Screen Shot 2019-04-26 at 11 43 04 am" src="https://user-images.githubusercontent.com/19252008/56778204-81eff000-6818-11e9-9b5c-a70b2a9e8122.png">

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#api-key-android-and-ios-platforms

**Comment by wf9a5m75** [comment]
I think you forgot to execute `ionic cordova prepare`

**Comment by Corovino** [comment]
i have  a similar few  issues
 1. when i try to install  cocoapods to use  native google maps  y get this error : 
     
![Screen Shot 2019-04-26 at 4 26 53 PM](https://user-images.githubusercontent.com/5142742/56837498-37826980-6840-11e9-99dc-84eff71afbca.png)
2. and other times . y get de api  key error 
![Screen Shot 2019-04-24 at 3 21 47 PM](https://user-images.githubusercontent.com/5142742/56837555-7ca69b80-6840-11e9-8a6e-836d218a0484.png)

Now I'm stuck jumping between pods error and api key error,I do not know what to do. 
Some suggestion thanks

**Comment by wf9a5m75** [comment]
Pod error is not similar error at all.
The reason of `pod error` might be that you don't install cocoapod.
Try to install/upgrade the latest cocoapod, and also upgrade `cordova` and `ionic` cli, then `ionic cordova platform remove ios` and `ionic cordova platform add ios`.

**Comment by wf9a5m75** [comment]
And please write your description in English. I don't know your language.

**Comment by wf9a5m75** [comment]
After trying, even you can't solve the problem, please share your project files on github repository. I will inspect it.

**Comment by schagani** [comment]
Hi follow following steps to run google maps plugin on my ionic project.
The google maps IOS api key error is due to recent changes by plugin. From now on you have to mention api key using preferences tag in config file. Also the key names have been changed. Please refer below link
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#api-key-android-and-ios-platforms

Further more I also updates the Cocoapod using below command
gem install cocoapod

After that I build my iOS platform and then inside that buIld iOS project folder I used below command
pod install

Regards

**Comment by wf9a5m75** [comment]
@schagani Did you solve your problem?

**Comment by Corovino** [comment]
i have cocoapods installed, but  xcode no  can't link the pods-debug.xconfig. 
im stuck and running crazy

**Comment by schagani** [comment]
> @schagani Did you solve your problem?

yes

**Comment by Corovino** [comment]
@schagani  how do u solved u bug, u can give me a hand i´m stuck

**Comment by wf9a5m75** [comment]
As I said above, `After trying, even you can't solve the problem, please share your project files on github repository. I will inspect it.`.

**Comment by Corovino** [comment]
@wf9a5m75  this is the repo :
https://github.com/Corovino/lookapp

**Comment by wf9a5m75** [comment]
Please include the all files from top, not `platforms/ios` only.

**Comment by Corovino** [comment]
sorry, i don´t  get it, i include  all files  and only work whit ios platform

**Comment by wf9a5m75** [comment]
Ok, the file structure is storage at least. Please give me the writing access permission to modify your code. I will commit the files to different branch.

**Comment by Corovino** [comment]
@wf9a5m75  ok check now, i invite u to collaborate

**Comment by wf9a5m75** [comment]
I fixed your project, but because you remove me from collaborate, I don't push them.

**Comment by Corovino** [comment]
@wf9a5m75  what was the problem, until now i can fixed that

**Comment by wf9a5m75** [comment]
File structure is wrong.

**Comment by Corovino** [comment]
which  file ?

**Comment by wf9a5m75** [comment]
First of all, putting Pods at the top is wrong, and also putting `contents.xcworkspacedata` file at the top is wrong.

**Comment by wf9a5m75** [comment]
I'm not your friend or teacher, I don't want to spend my time to teach what's wrong one by one. If you re-add access permission, I can push it, otherwise, I will throw away the files and please try to fix by yourself.

At least this is not this plugin's problem.

**Comment by Corovino** [comment]
@wf9a5m75  i appreciate so much your time. I dont know what happened  whit the project cuz i have  a versión in production  which works fine.
this is te repo:
https://github.com/Corovino/lookapp
And  again  thanks  for your time

**Comment by gopinathnelluri** [comment]
Add bellow preferences tags under widget tag in your context.xml and update ***your api key here*** with your google maps api key.

```
<widget ...>
  <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="***your api key here***" />
  <preference name="GOOGLE_MAPS_IOS_API_KEY" value="***your api key here***" />
</widget>
```

**Comment by gopinathnelluri** [comment]
Add below preferences tags under widget tag in your context.xml and update ***your api key here*** with your google maps api key.

```
<widget ...>
  <preference name="GOOGLE_MAPS_ANDROID_API_KEY" value="***your api key here***" />
  <preference name="GOOGLE_MAPS_IOS_API_KEY" value="***your api key here***" />
</widget>
```

<img width="935" alt="Screen Shot 2019-06-28 at 2 47 40 PM" src="https://user-images.githubusercontent.com/9353385/60364466-41495a00-99b4-11e9-85b9-da42e642e7b1.png">
