### ISSUE TITLE
iOs Plugin not installed

### ISSUE THREAD

**Issue by murilo3m** [ionic-team/ionic-native-google-maps#21]
Im using Maps to add some Markers, at Android it's perfectly working, but now in iOs Im getting a problem, after call the `GoogleMaps.create()` I receive a Warning: `Native: tried accessing the GoogleMaps plugin but it's not installed.`.

Ionic Info:
`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 7.0.1

local packages:

    @ionic/app-scripts : 3.1.5
    Cordova Platforms  : android 6.3.0 ios 4.4.0
    Ionic Framework    : ionic-angular 3.9.2

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2
    Node              : v8.11.1
    npm               : 2.15.12
    OS                : macOS High Sierra
    Xcode             : Xcode 9.3 Build version 9E145

Environment Variables:

    ANDROID_HOME : /Users/irroba/Library/Android/sdk/

Misc:

    backend : pro`

My map.ts file:

```
...
ionViewDidLoad() {
	this.platform.ready().then(() => {
		this.loading = this.loadingCtrl.create({
			content: 'Aguarde...',
			dismissOnPageChange: true
		});
		this.loadMap();
		
	});
}

loadMap() {
		let z = 0;
		if(this.functions.latitude && this.functions.latitude){
			z = 13;
		}
		let mapOptions: GoogleMapOptions = {
			camera: {
				target: {
					lat: this.functions.latitude,
					lng: this.functions.longitude
				},
				zoom: z
			}
		};

		let element = this.mapElement.nativeElement;
		this.map = GoogleMaps.create(element, mapOptions);
...
```

I already checked my Google `API_KEY_FOR_IOS` and its the same for `API_KEY_FOR_ANDROID`, btw I already checked in Google Console and both Maps SDK for Android and Maps SDK for iOs are enabled.

**Comment by wf9a5m75** [comment]
Please share your project files on github.

**Comment by murilo3m** [comment]
@wf9a5m75 I have to share all project or just some files?

**Comment by wf9a5m75** [comment]
In order to reproduce your issue, I need all project files.

**Comment by wf9a5m75** [comment]
Okay, please create a reproduce project.

I bet you would find what the problem is during creating the project.

**Comment by murilo3m** [comment]
@wf9a5m75 unfortunately I've faced the same problem, I think u can reproduce with this project
https://github.com/murilo3m/mapsMarkers/tree/master

**Comment by wf9a5m75** [comment]
You installed the maps plugin for Android only.
https://github.com/murilo3m/mapsMarkers/blob/master/package.json#L51-L53

**Comment by murilo3m** [comment]
Hmm ok, so what's the right way to add for iOs too?

**Comment by wf9a5m75** [comment]
```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova platform add ios

// confirm
$> cordova -v
8.0.0 

// confirm
$> cordova platform list
Android ...
iOS ...

$> cordova plugin add cordova-plugin-googlemaps --variable API_KEY_FOR_ANDROID="..." --variable API_KEY_FOR_IOS="..."
```

**Comment by murilo3m** [comment]
Ok, I will try and tell you if worked!

**Comment by murilo3m** [comment]
@wf9a5m75 I tried this and it's working fine now, thanks!
