### ISSUE TITLE
[Request] Polygons opacity

### ISSUE THREAD

**Issue by n0minal** [ionic-team/ionic-native-google-maps#212]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x] feature request

**Feature Request**: It's not yet possible to change polygons opacity with this plugin, please add it, it's important for my and many project, Google Maps API supports it natively.
```

**Comment by wf9a5m75** [comment]
you can specify opacity as #RRGGBBAA, or other ways.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v1.4.0/Available-HTML-colors
