### ISSUE TITLE
I can`t build ios xcode project with new cordova-plugin-googlemaps 2.6.2

### ISSUE THREAD

**Issue by worldboss1227** [ionic-team/ionic-native-google-maps#214]
cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.
Failed to install 'cordova-plugin-googlemaps': undefined

CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:29:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)

Please help me

**Comment by Algoru** [comment]
Same here.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/64fff8a30a13b026526d927fb7511c76dbea64a6/plugin.xml#L2

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/64fff8a30a13b026526d927fb7511c76dbea64a6/package.json#L3

**Comment by nombrekeff** [comment]
I had a similar problem, I finally fixed it today, although its not clear what was the issue and maybe its not exactly your same problem.

This is what I ended up doing, check if it helps: https://github.com/ionic-team/ionic-native-google-maps/issues/213#issuecomment-492628530
