### ISSUE TITLE
Geocoder returns empty array [] and catches error on android build

### ISSUE THREAD

**Issue by ramioooz** [ionic-team/ionic-native-google-maps#216]
Hello developers,

Geocoder works fine on web,
but not working in android builds,

```
Geocoder.geocode({
      position: { lat: 11.62104266, lng: 22.46397197 }
    }).then((results: GeocoderResult[]) => {
      console.log(results);
}).catch(error => {
console.log("geocoder error : ", JSON.stringify(error))});
```

I am getting empty results array []
I used google dev tools to read error message catched by console log, this is what I got : 

`{"__zone_symbol__currentTask":{"type":"microTask","state":"notScheduled","source":"Promise.then","zone":"<root>","cancelFn":null,"runCount":0}}`

I am using the followings  : 

- Iconic v3.20.1
- cordova-plugin-googlemaps v2.6.2
- @ionic-native/core v4.20.0
- @ionic-native/google-maps v4.21.0
- cordova-android v7.1.4
- cordova-browser v5.0.4

Any suggestions,
Thank you

**Comment by wf9a5m75** [comment]
`empty results array []` is the result of Google, not this plugin's bug.

**Comment by ramioooz** [comment]
Hello @wf9a5m75 ,
thank you for your fast reply,

the position, i posted up  is a dummy co-ordinates,
the Geocoder is working just fine in browser, but when running on android It is not . I tested it using the same position.

Thanks

**Comment by wf9a5m75** [comment]
Unfortunately, I have no further information. The maps plugin returns just the results.

**Comment by ramioooz** [comment]
@wf9a5m75 
did you try to test Geocoder fetching a position on android build ?

**Comment by wf9a5m75** [comment]
No, I'm busy.

**Comment by ramioooz** [comment]
@wf9a5m75  
OK , lets see if someone faced the same issue and solved it.

**Comment by wf9a5m75** [comment]
Please try on emulator or other phones by yourself at least.

**Comment by ramioooz** [comment]
@wf9a5m75 
I surely will and post it here..

**Comment by ramioooz** [comment]
Hello @wf9a5m75 

I did some further tests on the app and I noticed that Geocoder works fine on my android device when I connect through vpn..
I think this has something to do with where I live. I live in Africa - Sudan, and some of google api services are not working here...

I will let you know if I found a work around. for now I will close this issue.
Thank you
