### ISSUE TITLE
setBackgroundColor doesn't work in browser

### ISSUE THREAD

**Issue by imedvedev75** [ionic-team/ionic-native-google-maps#219]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/core": "^5.5.0",
  "@ionic-native/google-maps": "^5.5.0",

**Current behavior:**
adding the following line:
Environment.setBackgroundColor("grey");

in the test application, in:
 initializeApp() {
    this.platform.ready().then(() => {
      Environment.setEnv({...   });
      Environment.setBackgroundColor("grey");
      this.statusBar.styleDefault();
      this.splashScreen.hide();
    });
  }

does not change the background color in the browser, but does on device (Android).

**Expected behavior:**
Expected background color change (grey instead of while).

**Comment by wf9a5m75** [comment]
`setBackgroundCokor()` works only for Android and iOS.

**Comment by imedvedev75** [comment]
Will it be also supported for browser in the future? If not - what workaround shall be used?

Thanks and Regards

**Comment by wf9a5m75** [comment]
>Will it be also supported for browser in the future?

no. Implementations of Android/ios ans browser are different.

MapView is displayed under browser on Android/ios.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#how-does-this-plugin-work-android-ios

However the map element is displayed in HTML on browser platform.
