### ISSUE TITLE
GoogleMapsMapTypeId.TERRAIN combined with custom styles does not work

### ISSUE THREAD

**Issue by aceArt-GmbH** [ionic-team/ionic-native-google-maps#221]
**I'm submitting a ...** 
- [ ] question
- [X] any problem or bug report
- [ ] feature request

- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 3.1.2 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

```
"@ionic-native/core": "^5.0.0",
"@ionic-native/google-maps": "^5.0.0-beta.27",
```

**Current behavior:**
When choosing  GoogleMapsMapTypeId.TERRAIN and setting custom styles via the style property of GoogleMapOptions, either styling or terrain type will be removed. I get a styled basic map or a non styled terrain map, but not both.

This is how I try to style a terrain map:
```
this.map = GoogleMaps.create('map-canvas', {
   mapType: GoogleMapsMapTypeId.TERRAIN,       
   styles: this.mapStyles,
})
```
The styled terrain map works when trying to achieve the same appearance with the browser. 

**Expected behavior:**
A styled terrain map should appear.

**Comment by wf9a5m75** [comment]
If it does not work, Google does not support it.

**Comment by aceArt-GmbH** [comment]
Google does support it. It does not work with ionic-native-google-maps (as I wrote in this issue).

**Comment by wf9a5m75** [comment]
Google does support it. 

Please provide the evidence.
