### ISSUE TITLE
NPE when using native-maps on Android

### ISSUE THREAD

**Issue by BennyKirschner** [ionic-team/ionic-native-google-maps#222]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**

When exporting and loading the app via ng build -> ionic capacitor add android -> npx cap open android, the app crashes instantly and throws [this NPE](https://i.stack.imgur.com/n7IwX.png) for some reason.

**Expected behavior:**

App should boot without failing after being installed.

**Comment by wf9a5m75** [comment]
This plugin does not support capacitor yet.

**Comment by BennyKirschner** [comment]
Alright, gonna try it with Cordova then and see if that works.

**Comment by BennyKirschner** [comment]
Alright, figured it out. Can be closed.

**Comment by xahanix** [comment]
Is it in planning to make this plugin support capacitor?

**Comment by rosnaib11** [comment]
Is that mean it will not work when using `ionic capacitor run android`?
