### ISSUE TITLE
Google Play App Crashes java.lang.NegativeArraySizeException at plugin.google.maps.PluginMarker$3.run

### ISSUE THREAD

**Issue by saleemi** [ionic-team/ionic-native-google-maps#223]
Hi there,

During the last 30 days I have received more than 120 crashes on my Android App Google Maps plugin. Please find below the details of the crashes. I am willing to donate if you can fix the underlying issue(s) which are causing the App to crash.

java.lang.NegativeArraySizeException: 
  at plugin.google.maps.PluginMarker$3.run (PluginMarker.java:149)
  at android.os.Handler.handleCallback (Handler.java:873)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:201)
  at android.app.ActivityThread.main (ActivityThread.java:6806)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:547)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:873)

![image](https://user-images.githubusercontent.com/4964322/59160788-c2fb4580-8ae2-11e9-9a1e-784f2b587b70.png)

Please feel free to ask me if you need more information.

Regards,
Fiaz Ali Saleemi

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
This problem has been already fixed in v2.6.2.

**Comment by saleemi** [comment]
I have published it after upgrading the map to v2.6.2 more than one month ago, but still the crashes are appearing. I will be great if you can check it again.

**Comment by wf9a5m75** [comment]
ping. Any updates?

**Comment by saleemi** [comment]
The error resolved, I no longer see it in my App crash reports. Thanks a
lot for your help.
