### ISSUE TITLE
Cordova can't install Google Maps for iOS

### ISSUE THREAD

**Issue by jolortegui98** [ionic-team/ionic-native-google-maps#225]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
call-number 0.0.2 "Cordova Call Number Plugin"
cordova-plugin-datepicker 0.9.3 "DatePicker"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-facebook4 4.2.1 "Facebook Connect"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.3.3 "cordova-plugin-ionic-webview"
cordova-plugin-request-location-accuracy 2.3.0 "Request Location Accuracy"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-x-socialsharing 5.4.3 "SocialSharing"
es6-promise-plugin 4.2.2 "Promise"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.11.0",
"@ionic-native/google-maps": "^4.21.0",
```

**Current behavior:**
Cordova can't install the GoogleMaps plugin. I know this is happening due to my cordova version, but, if i upgrade it, will not it break my project?

```
╰> ionic cordova platform add ios

> cordova platform add ios --save
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: py.com.infoparaguay.infoparaguay
	Name: infoParaguay
iOS project created with cordova-ios@4.5.5
Installing "call-number" for ios
Installing "cordova-plugin-datepicker" for ios
Installing "cordova-plugin-device" for ios
Installing "cordova-plugin-facebook4" for ios
Installing "cordova-plugin-geolocation" for ios
Installing "cordova-plugin-googlemaps" for ios
Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.5, failed version requirement: >=5.0.0
Skipping 'cordova-plugin-googlemaps' for ios
Installing "cordova-plugin-inappbrowser" for ios
Installing "cordova-plugin-ionic-keyboard" for ios
Installing "cordova-plugin-ionic-webview" for ios
Installing "cordova-plugin-request-location-accuracy" for ios
Installing "cordova-plugin-splashscreen" for ios
Installing "cordova-plugin-statusbar" for ios
Installing "cordova-plugin-whitelist" for ios
Installing "cordova-plugin-x-socialsharing" for ios
Plugin dependency "es6-promise-plugin@4.2.2" already fetched, using that version.
Installing "es6-promise-plugin" for ios
Dependent plugin "es6-promise-plugin" already installed on ios.
Discovered plugin "mx.ferreyra.callnumber" in config.xml. Adding it to the project
Plugin "call-number" already installed on android.
Plugin "call-number" already installed on browser.
Plugin "call-number" already installed on ios.
Adding call-number to package.json
Saved plugin info for "call-number" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
> ionic cordova resources ios --force
✔ Collecting resource configuration and source images - done!
✔ Filtering out image resources that do not need regeneration - done!
(node:37646) ExperimentalWarning: The http2 module is an experimental API.
✔ Uploading source images to prepare for transformations: 2 / 2 complete - done!
✔ Generating platform resources: 32 / 32 complete - done!
✔ Modifying config.xml to add new image resources - done!
```

I'll be thankful if someone can help me with this problem.
Thanks in advance, sorry if i have a bad English.
Greetings from Paraguay!

**Comment by wf9a5m75** [comment]
Please remove cordova-ios, then reinstall cordova-ios@5

**Comment by jolortegui98** [comment]
It works! Thank you so much.

**Comment by 2diegoduque** [comment]
Hello, if Cordova is updated to the latest version
"npm install -g cordova @ latest" the application builds success, but when it runs it does not leave the SplashScreen. can not google maps be used for lower versions of cordova 9.0.0?

`Ionic:

   Ionic CLI          : 5.2.1 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.2
   @ionic/app-scripts : 3.2.4

Cordova:

   Cordova CLI       : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms : ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-webview 2.5.1, (and 23 other plugins)

Utility:

   cordova-res : 0.3.0 (update available: 0.5.2)
   native-run  : 0.2.5 (update available: 0.2.7)

System:

   Android SDK Tools : 26.1.1
   ios-deploy        : 1.9.4
   ios-sim           : 8.0.1
   NodeJS            : v10.16.0 (/usr/local/bin/node)
   npm               : 6.9.2
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001`

**Comment by suryakvm** [comment]
> It works! Thank you so much.

Hey I am also having the same problem. 
Ionic Version - 3.9.2
Cordova Version - 8.0.0

Now to update cordova-ios what i did is 
npm uninstall cordova-ios
npm install cordova-ios@5.0.0

and still when i do cordova platform list. I am getting ios@4.5.5

**Comment by battika** [comment]
Try 
ionic cordova platform remove ios
followed by
ionic cordova platform add ios
or
ionic cordova platform add ios@5.0.0

if you really want to specify cordova-ios version

**Comment by mjamshidy** [comment]
@wf9a5m75 I have latest `cordova(9.0.0)` and `cordova-ios (5.1.1)` and I can install plugin version `2.6.2`. But when I try the `2.7.1` for iOS, it just hangs there. (ionic 3 project). Do you have any suggestion?

`"dependencies": {
    "@angular/animations": "7.2.15",
    "@angular/common": "7.2.15",
    "@angular/compiler": "7.2.15",
    "@angular/compiler-cli": "7.2.15",
    "@angular/core": "7.2.15",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "7.2.15",
    "@angular/http": "7.2.15",
    "@angular/platform-browser": "7.2.15",
    "@angular/platform-browser-dynamic": "7.2.15",
    "@ionic-native/camera": "^5.25.0",
    "@ionic-native/core": "^5.25.0",
    "@ionic-native/date-picker": "^5.25.0",
    "@ionic-native/device": "^5.25.0",
    "@ionic-native/dialogs": "^5.25.0",
    "@ionic-native/facebook": "^5.25.0",
    "@ionic-native/firebase": "^5.25.0",
    "@ionic-native/google-maps": "^5.5.0",
    "@ionic-native/google-nearby": "^5.25.0",
    "@ionic-native/http": "^5.25.0",
    "@ionic-native/ionic-webview": "^5.25.0",
    "@ionic-native/keyboard": "^5.25.0",
    "@ionic-native/native-geocoder": "^5.25.0",
    "@ionic-native/native-page-transitions": "^5.25.0",
    "@ionic-native/native-storage": "^5.25.0",
    "@ionic-native/network": "^5.25.0",
    "@ionic-native/push": "^5.25.0",
    "@ionic-native/splash-screen": "^5.25.0",
    "@ionic-native/sqlite": "^5.25.0",
    "@ionic-native/status-bar": "^5.25.0",
    "@ionic-native/wheel-selector": "^5.25.0",
    "@ionic/storage": "2.2.0",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "@types/google-maps": "^3.2.1",
    "@types/googlemaps": "^3.39.4",
    "ajv": "^6.10.0",
    "angular": "^1.7.9",
    "angularfire2": "^5.2.1",
    "bson": "^4.0.2",
    "com.telerik.plugins.nativepagetransitions": "^0.6.5",
    "cordova-android": "^8.1.0",
    "cordova-browser": "^6.0.0",
    "cordova-common": "^4.0.0",
    "cordova-ios": "^5.1.1",
    "cordova-plugin-add-swift-support": "^2.0.2",
    "cordova-plugin-advanced-http": "^2.4.1",
    "cordova-plugin-datepicker": "^0.9.3",
    "cordova-plugin-device": "^2.0.3",
    "cordova-plugin-dialogs": "^2.0.2",
    "cordova-plugin-facebook4": "^6.4.0",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-file-transfer": "^1.7.1",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-googlemaps": "^2.7.1",
    "cordova-plugin-ionic": "^5.4.7",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.2.1",
    "cordova-plugin-nativegeocoder": "^3.4.1",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-plugin-network-information": "^2.0.2",
    "cordova-plugin-splashscreen": "^5.0.3",
    "cordova-plugin-statusbar": "^2.4.3",
    "cordova-plugin-whitelist": "^1.3.4",
    "cordova-sqlite-storage": "^5.0.0",
    "cordova-support-android-plugin": "^1.0.2",
    "cordova-support-google-services": "^1.4.0",
    "cordova-wheel-selector-plugin": "^1.1.7",
    "date-fns": "^1.30.1",
    "firebase": "^7.14.2",
    "fsevents": "^1.2.9",
    "grpc": "^1.24.2",
    "hoek": "^6.1.3",
    "iod": "^1.1.1",
    "ionic-angular": "3.9.6",
    "ionic-plugin-deeplinks": "^1.0.20",
    "ionicons": "^5.0.1",
    "node-gyp": "^6.1.0",
    "node-pre-gyp": "^0.14.0",
    "node-sass": "^4.14.0",
    "phonegap-plugin-multidex": "^1.0.0",
    "phonegap-plugin-push": "^2.3.0",
    "rxjs": "^6.5.2",
    "rxjs-compat": "^6.5.2",
    "rxjs-tslint": "^0.1.7",
    "shelljs": "^0.5.3",
    "socket.io-client": "^2.2.0",
    "sshpk": "^1.16.1",
    "sw-toolbox": "3.6.0",
    "tough-cookie": "^2.5.0",
    "updates": "^8.1.0",
    "workbox-sw": "^4.3.1",
    "zone.js": "^0.8.29"
  },`

**Comment by wf9a5m75** [comment]
No longer support for `ionic 3`, because Google Maps SDK for iOS requires iOS10 at least.
