### ISSUE TITLE
Ionic 4: Standard components and fit issues 

### ISSUE THREAD

**Issue by services4smb** [ionic-team/ionic-native-google-maps#226]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ x] **Android**
- [ ] **iOS**
- [ x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.0.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^5.5.1",
"@ionic-native/google-maps": "^5.5.0",
```

**Current behavior:**
I have build a Google Maps Demo app, but are struggling with Google Maps together with standard Ionic components. I'm running the app on the device using the following command:
$ ionic cordova run android

1). Clicking on button 'open map page' will open Google Maps perfectly. 
  - Map is 100% of screen, o.k.
  - My location is shown and location button works, o.k.
  - Zoom in/out works, o.k.

2). Clicking on button 'open map (a-b) page' doesn't work as expected.
  - Map is 100% of screen, o.k.
  - My location is shown and location button works, o.k.
  - Zoom in/out works, o.k.
  - Custom map button doesn't work (works in browser) and should show a custom list, NOT o.k.
  - Click on the map sets an Green marker, o.k.
  --- Calculation of distance between Blue/Green marker works, but footer isn't updated, NOT o.k.
  - Long click to move markers works, o.k.
Question: how to add custom buttons to Google Maps?

3). Clicking on button 'open map (size) doesn't work as expected.
  - Map is NOT 100% of screen, NOT o.k.
Question: how to use ion-segments and at the same time show Google Maps 100% of the remaining space?

**Expected behavior:**
Please see steps above.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
https://bitbucket.org/nicedevice/googlemaps/
```

**Comment by wf9a5m75** [comment]
At the first, you need to understand how this plugin works.
The map views on Android and iOS are NOT html element.

![](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/raw/master/v1.4.0/class/Map/mechanism.png)

I have never used `ion-segment` with this plugin.
But tab page works with this plugin.
