### ISSUE TITLE
Ionic 3 demo not working

### ISSUE THREAD

**Issue by omkarkhalipe** [ionic-team/ionic-native-google-maps#227]
I am trying to use the plugin for Ionic 3, but it doesn't work. I tried to clone sample ionic 3 app provided but same issue,
I get this error in xcode

> GoogleMaps quick demo WARN: 'Ionic Native: tried accessing the GoogleMaps plugin but it's not installed.

**Comment by wf9a5m75** [comment]
As the error message says, you don't install the plugin, or Cordova failed to install (you ignored error message during installation).

**Comment by omkarkhalipe** [comment]
I found the solution after going through other issues, I had to use latest cordova ios
