### ISSUE TITLE
IOS Crash when try to use kml

### ISSUE THREAD

**Issue by uiktiomasfeliz** [ionic-team/ionic-native-google-maps#229]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-advanced-http 2.1.1 "Advanced HTTP plugin"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-camera 4.1.0-dev "Camera"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-facebook4 5.0.0 "Facebook Connect"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.6.2 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 7.0.2 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-splashscreen 5.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-telerik-imagepicker 2.3.2 "ImagePicker"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-x-socialsharing 5.4.7 "SocialSharing"
cordova-sqlite-storage 3.2.1 "Cordova sqlite storage plugin - cordova-sqlite-storage plugin version"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-mobile-accessibility 1.0.5-dev "Mobile Accessibility"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^4.20.0",
"@ionic-native/google-maps": "^4.21.0",
```

**Current behavior:**

Crash when map open

**Expected behavior:**

Draw kml like android.

**Related code, data or error log (please format your code or data):**

The app crash when try to execute line 196 from `PluginKmlOverlay.m`
```
NSMutableDictionary *root = [parser parseXml:tbxml rootElement:tbxml.rootXMLElement];
```
The url from where i load the kml file is: ``` @"ionic://localhost/assets/config/overlay.kml" ```

I use kml files generated from this web: https://global.mapit.mysociety.org

**Comment by wf9a5m75** [comment]
This plugin supports only limited kml tags

**Comment by uiktiomasfeliz** [comment]
I tried adding the server url and it works, apparently the problem is related to the local path, the ios can not find the file
