### ISSUE TITLE
 custom marker

### ISSUE THREAD

**Issue by aligassan** [ionic-team/ionic-native-google-maps#230]
**I'm submitting a ...**  (check one with "x")
- [x ] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

I am currently working on ionic native google maps building weather map . l wondering how can  i custom marker like this image below ? 

[
![image](https://user-images.githubusercontent.com/12250051/61206327-5687ed80-a703-11e9-8efa-59d7cc2615cf.png)
](url)

any idea please ?

**Comment by wf9a5m75** [comment]
You need to generate custom image your way, such as canvas or server side. This plugin accepts base64 encoded string as icon image.

**Comment by aligassan** [comment]
> You need to generate custom image your way, such as canvas or server side. This plugin accepts base64 encoded string as icon image.

Thank you for replying . Do you have any example code ?

**Comment by wf9a5m75** [comment]
https://www.google.com/search?q=canvas+base64
