### ISSUE TITLE
When I open htmlInfoWindow as soon as adding marker, it'll be not displayed with wrong css.

### ISSUE THREAD

**Issue by JeongJun-Lee** [ionic-team/ionic-native-google-maps#231]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
"@ionic-native/core": "^5.5.0",
"@ionic-native/google-maps": "^5.5.0"

**Current behavior:**

When I open htmlInfoWindow as soon as adding marker, it'll be not displayed with wrong css.

**Expected behavior:**

When I open htmlInfoWindow as soon as adding marker, it'll be displayed well.

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**
Like https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2657, I applied to MARKER_CLICK's trigger to open htmlInfoWindow as soon as adding marker. Actually it works. But it'll not shown correctly like screenshot below.

![image](https://user-images.githubusercontent.com/11474775/61536974-5d8a6500-aa4f-11e9-9645-73fd42469527.png)

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository. I guess your CSS affects to the plugin program
