### ISSUE TITLE
duplicate polyline of google map

### ISSUE THREAD

**Issue by aligassan** [ionic-team/ionic-native-google-maps#234]
**I'm submitting a ...**  (check one with "x")
- [x ] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ x] **Android**
- [ ] **iOS**
- [ ] **Browser**

I am trying to get latitude and longitude of flight route from data json api . While updating points of flight path using setInterval l get duplicate of flight path .

Before data refresh

https://i.stack.imgur.com/SiaE1.png
enter image description here

After refresh data

https://i.imgur.com/0CDnDcD.png

my code

```
async ngOnInit() {
    await this.platform.ready();
    await this.loadmap()
    await this.getmarker()

}

loadmap(){
    this.map = GoogleMaps.create('map_canvas')

    if(GoogleMapsEvent.MAP_READY){

        setInterval(()=>{
            this.getmarker()


        },5)
    }
}

async getmarker() {

        this.http.get('xxxxxxxxxxxxxx=' + this.id + '', {}, {})
        .then(data => {
            console.log(data.data+'My data')



            // Track aircraft 

            for (let datas of JSON.parse(data.data).result.response.data.flight['track']) {

                this.points.push({ lng: datas.longitude, lat: datas.latitude });

            }



    ////////// aircraft Polyline path /////


    let polyline: Polyline = this.map.addPolylineSync({
            points: this.points,
            color: '#AA00FF',
            width: 4,
            geodesic: true,

        });


        });

}

```

**Comment by wf9a5m75** [comment]
It's because you don't remove the previous polyline.

**Comment by aligassan** [comment]
> It's because you don't remove the previous polyline.
How can i remove it ? do have example ?

**Comment by wf9a5m75** [comment]
Please read the documents.

**Comment by aligassan** [comment]
> Please read the documents.

l readed the doc , but l still don't know how to get on main path not duplicate path . can you please modify my code ?
