### ISSUE TITLE
duplicate polyline of google map

### ISSUE THREAD

**Issue by aligassan** [ionic-team/ionic-native-google-maps#235]
Please read the documents.

_Originally posted by @wf9a5m75 in https://github.com/ionic-team/ionic-native-google-maps/issues/234#issuecomment-513570106_

l am sorry l clicked by mistake one close comment . l readed the doc , but l still don't know how to get on main path not duplicate path . can you please modify my code ?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/Polyline/remove/README.md
