### ISSUE TITLE
ion-menu-button not showing on top left of ionic native google map and neither allow map to work properly

### ISSUE THREAD

**Issue by ZubairHasan96** [ionic-team/ionic-native-google-maps#238]
I want to show the menu-button on google map top left, but when I tried to use it appears in middle of the map and doesn't allow any functionality of map to work, wherever you click it will open the menu. html is as follows:

```
<div id="map_canvas">
    <ion-menu-button></ion-menu-button>
  </div>
```

But when I use a simple button it works fine but I want menu icon to. The Html is shown below:

```
<div id="map_canvas">
    <button (click)="OpenMenu()" >Start Demo</button>
</div>

```
CSS for both cases is same and as follows:

```
#map_canvas {
    height: 100%;
}
```

**Comment by wf9a5m75** [comment]
Please inspect your application css using either Google Chrome Developer Tool or Safari Web Inspector.
