### ISSUE TITLE
marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() not fired (4.20)

### ISSUE THREAD

**Issue by alexdragneel** [ionic-team/ionic-native-google-maps#239]
*I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.5.0 "Google Maps SDK for iOS"
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-plugin-add-swift-support 1.7.0 "AddSwiftSupport"
cordova-plugin-app-event 1.2.1 "Application Events"
cordova-plugin-appavailability 0.4.2 "AppAvailability"
cordova-plugin-calendar 5.0.0 "Calendar"
cordova-plugin-camera 2.4.1 "Camera"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-document-viewer 0.9.7 "SitewaertsDocumentViewer"
cordova-plugin-email-composer 0.8.11 "EmailComposer"
cordova-plugin-facebook4 1.9.1 "Facebook Connect"
cordova-plugin-file 5.0.0 "File"
cordova-plugin-filechooser 1.0.1 "File Chooser"
cordova-plugin-filepath 1.0.2 "FilePath"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-globalization 1.0.8 "Globalization"
cordova-plugin-googlemaps 2.1.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 1.7.2 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-linkedin 1.2.1 "LinkedIn"
cordova-plugin-nativegeocoder 2.0.4 "NativeGeocoder"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
cordova-plugin-x-socialsharing 5.4.4 "SocialSharing"
de.appplant.cordova.plugin.local-notification 0.8.5 "LocalNotification"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-push 2.1.2 "PushPlugin"
twitter-connect-plugin 0.6.0 "Twitter Connect"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
    "@ionic-native/core": "^4.20.0",
    "@ionic-native/google-maps": "^4.20.0",

**Current behavior:**
marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(() => {
    if (marker.isInfoWindowShown())
        this.navCtrl.push(ProfilPage, { userProfil: this.navParams.get('userProfil'), member: user });
});

The "marker.on(GoogleMapsEvent.MARKER_CLICK).subscribe(()" method are not fired when i click on marker.

**Comment by wf9a5m75** [comment]
https://github.com/ionic-team/ionic-native-google-maps/issues/237
