### ISSUE TITLE
Feature Request : Fallback to Javascript map for browser testing

### ISSUE THREAD

**Issue by juliusbangert** [ionic-team/ionic-native-google-maps#24]
**_This is not a bug or issue but a feature request..._**
I would love to be able to use your google maps plugin while testing in ionic lab. Would it be possible for you to add in a fallback where the javascript google maps implementation is served when the app is being run on the browser or on the dev app? I realise that there are some native features that are not available in the javascript api but some kind graceful degradation would be extremely useful for quicker testing. Thank you for the great work.

**Comment by wf9a5m75** [comment]
Time is money.

If you donate $1,000usd to the cordova-plugin-googlemaps,  I would like to implement it.

HTMLInfoWindow, and MarkerCluster have been implemented by donations. Then I spent ton's of time.

I always ask to the people who want to implement new feature.
