### ISSUE TITLE
Please can we start a discussion for supporting capacitor.

### ISSUE THREAD

**Issue by stevebrowndotco** [ionic-team/ionic-native-google-maps#241]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [X] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**
- [ ] **Browser**

Hello, this is a brilliant plugin. I am using it in production on a Cordova app. Please can we discuss supporting ionic capacitor/iOS with ionic google maps?

It works on Android, however it does not work on iOS, (I know that this is not new information) I have researched the author of this plugin's posts and I know that he is aware. Also, capacitor appears to be the future for Ionic.

Many developers whom are using capacitor are following this [article](https://www.joshmorony.com/using-google-maps-and-geolocation-in-ionic-with-capacitor/) to instead use the js sdk. This is an inferior solution because it does not support offline, which is essential for many apps, such as mine.

So please can I ask, what is the progress for supporting capacitor/iOS?

Thank you.

**Comment by wf9a5m75** [comment]
I tested the modified version of `cordova-plugin-googlemaps`, which is core plugin of `ionic-native/googlemaps` worked on capacitor.
But I stopped development, because run out of my motivation.

**Comment by stevebrowndotco** [comment]
Hi, thank you for your reply. Which modified version are you speaking of?

**Comment by wf9a5m75** [comment]
`cordova-plugin-googlemaps` but code is not public available.

**Comment by stevebrowndotco** [comment]
Do you know how I can use it in my project, if it works?

**Comment by wf9a5m75** [comment]
As I said, not public available.

**Comment by stevebrowndotco** [comment]
I hope you don't mind me asking, but if you have worked on a version of the plug-in that supports capacitor, and it works, can the Ionic company not provide a donation or some renumeration to help assist? Surely that will help everyone.

**Comment by THEDOWNCOUNTRY** [comment]
I get this error "cordova-plugin-googlemaps is not installed or not ready yet" on iOS android works fine. What should I do?

**Comment by dupiesdupreez** [comment]
For any one wanting to use google maps with Capacitor, you can follow this tutorial. 
It works for both android and IOS, tested it myself.

[Using Google Maps and Geolocation in Ionic with Capacitor
](https://www.joshmorony.com/using-google-maps-and-geolocation-in-ionic-with-capacitor/)

**Comment by hellokingdom** [comment]
It's worth noting that using the JavaScript API is charged ($7 per 1000) whilst using the native SDK's is free:

https://cloud.google.com/maps-platform/pricing/

**Comment by menosprezzi** [comment]
@THEDOWNCOUNTRY you need to setup cocoapods to run with the plugin on iOS

**Comment by tepafril** [comment]
@menosprezzi does it work on ionic capacitor?

**Comment by wf9a5m75** [comment]
I made a fundraising to implement the code for supporting Capacitor iOS.
Please join and support the project!

[Fundraising: Support for Capacitor iOS platform](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781)
