### ISSUE TITLE
can't get it work in iOS platform - conflicts with GoogleMaps@~> 3.1.0

### ISSUE THREAD

**Issue by leabdalla** [ionic-team/ionic-native-google-maps#244]
I'm trying to use GoogleMaps on Ionic but it seems impossible to get it working in iOS.

In browser and Android it works good.

After several times trying different ways, I've just forked the quick-example and it's not working for me as well.

So, here is how to reproduce:

    $ git clone https://github.com/leabdalla/ionic-googlemaps-quickdemo-v4
    $ cd ionic-googlemaps-quickdemo-v4
    $ npm install
    $ ionic cordova platform add ios --verbose

    Installing plugin "cordova-plugin-googlemaps" following successful platform add of ios
    Found variables for "cordova-plugin-googlemaps". Processing as cli_variables.
    Installing "cordova-plugin-googlemaps" for ios
    Running command: /Users/myuser/dev/ionic-googlemaps-quickdemo-v4/platforms/ios/cordova/version
    Command finished with error code 0: /Users/myuser/dev/ionic-googlemaps-quickdemo-v4/platforms/ios/cordova/version
    Running command: /Users/myuser/dev/ionic-googlemaps-quickdemo-v4/platforms/ios/cordova/version
    Running command: /Users/myuser/dev/ionic-googlemaps-quickdemo-v4/platforms/ios/cordova/apple_xcode_version
    Running command: /Users/myuser/dev/ionic-googlemaps-quickdemo-v4/platforms/ios/cordova/apple_ios_version
    Command finished with error code 0: /Users/myuser/dev/ionic-googlemaps-quickdemo-v4/platforms/ios/cordova/version
    Command finished with error code 0: /Users/myuser/dev/ionic-googlemaps-quickdemo-v4/platforms/ios/cordova/apple_xcode_version
    Command finished with error code 0: /Users/myuser/dev/ionic-googlemaps-quickdemo-v4/platforms/ios/cordova/apple_ios_version
    Finding scripts for "before_plugin_install" hook from plugin cordova-plugin-googlemaps on ios platform only.
    Executing script found in plugin cordova-plugin-googlemaps for hook "before_plugin_install": plugins/cordova-plugin-googlemaps/src/ios/check_sdk_version.js
    Install start for "cordova-plugin-googlemaps" on ios.
    Beginning processing of action stack for ios project...
    Action stack processing complete.
    pods.json found in platforms/ios
    Podfile found in platforms/ios
    Adding pods since the plugin contained <podspecs>
    Set pods.json for `sources` - `https://github.com/CocoaPods/Specs.git`
    Added source line for `https://github.com/CocoaPods/Specs.git`
    Set pods.json for `libraries` - `GoogleMaps`
    Added pod line for `GoogleMaps`
    "framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
    Adding pods since the plugin contained <framework>(s) with type="podspec"
    cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.
    Wrote to pods.json.
    Wrote to Podfile.
    Running `pod install` (to install plugins)
    Failed to install 'cordova-plugin-googlemaps': undefined
    CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
        at cli.catch.err (/Users/myuser/.nvm/versions/node/v10.16.3/lib/node_modules/cordova/bin/cordova:29:15)
        at process._tickCallback (internal/process/next_tick.js:68:7)
    [ERROR] An error occurred while running subprocess cordova.

So I try to install pods:

    $ cd platforms/ios
    $ pod install

Then get back and try create iOS platform again

    $ ionic cordova platform remove ios
    $ ionic cordova platform add ios

But it shows the same error message:

    cordova-plugin-googlemaps depends on GoogleMaps@~> 2.7.0, which conflicts with another plugin. GoogleMaps@~> 3.1.0 is already installed and was not overwritten.

My environment has:

    node -v      = v10.16.3
    ionic -v     = npm 5.2.6
    npm -v       = 6.9.0
    cordova -v   = 9.0.0 (cordova-lib@9.0.1)

Any help?

**Comment by battika** [comment]
Have you also tried running `pod repo update` in the platforms/ios directory after it failed followed by `pod install`? Another very useful new Ionic command is `ionic repair` you could try, it takes care of removing all node_modules, platforms and reinstalls everything. I find it very useful often times.
