### ISSUE TITLE
app crash on android 9 and above

### ISSUE THREAD

**Issue by Bhagirath123** [ionic-team/ionic-native-google-maps#246]
Hi

i am using google-maps plugin in ionic 3 project
in my cash map working in android 8.1.0
but when i am open map in my android 9 and above version device my app close

plz help

**Comment by wf9a5m75** [comment]
As I said at [here](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2675), please share your project files on github if you can't debug by yourself.

**Comment by Bhagirath123** [comment]
thanks for you support
problem is resolved for update plugin version

**Comment by taofik-nos** [comment]
Do you mind sharing what version you ended up using @Bhagirath123 ? Thanks!
