### ISSUE TITLE
Add gestureHandling: 'cooperative' to the options

### ISSUE THREAD

**Issue by ivobrands** [ionic-team/ionic-native-google-maps#249]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [X] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-plugin-advanced-http 2.0.9 "Advanced HTTP plugin"
cordova-plugin-appcenter-push 0.3.6 "App Center Push for Cordova"
cordova-plugin-appcenter-shared 0.3.6 "App Center shared code for Cordova"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.3 "Device"
cordova-plugin-document-viewer 0.9.10 "SitewaertsDocumentViewer"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-opener2 2.2.0 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-googlemaps 2.6.3-20190808-1526 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 3.1.0 "InAppBrowser"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-whitelist 1.3.4 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

    "@ionic-native/google-maps": "^5.0.0-beta.27",

**Current behavior:**
When i'm scrolling through my page, in want to scroll the page instead of the map, currently the map is scrolled.

**Expected behavior:**
When i'm scrolling through my page, in want to scroll the page instead of the map.

Is this possible?

**Comment by wf9a5m75** [comment]
```js
map.setOptions({
    'gestures': {
      'scroll': true or false
    }
});
```
