### ISSUE TITLE
Cannot set property 'marker_703732314972' of undefined

### ISSUE THREAD

**Issue by ugoconsonni** [ionic-team/ionic-native-google-maps#25]
Hi,
Today i reinstall module cause ios don't find it and i have this error in IOS and Android after call
 ```
let latLng:LatLng  = new LatLng(lat, lng);
    // create new marker
    let markerOptions: MarkerOptions = {
      position: latLng,
      title: titre,
    }
    this.map.addMarker(markerOptions)
```
my code work before reinstall in android , after reinstall i have this error:

![capture d ecran 2018-05-14 a 16 46 49](https://user-images.githubusercontent.com/13661702/40004913-05b34de4-5797-11e8-8267-791bca4b8983.png)

Thanks for read / help

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub.

**Comment by ugoconsonni** [comment]
Ty for your answer, I shared my project with you. The project name is **Spotyride_Ionic** .
Sorry for the french in the code.
Let me know when you find something.

**Comment by ugoconsonni** [comment]
you can pass this step with click on "Passer cette étape"

**Comment by wf9a5m75** [comment]
Thanks, I confirmed the error, but you don't coding rule at all.

**DO NOT ** create map instance with `new GoogleMap()`;

Use `GoogleMaps.create('map', {})`, then all errors are gone.

**Comment by wf9a5m75** [comment]
Before using this plugin, please check out this slides.
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.p

**Comment by wf9a5m75** [comment]
![capture](https://user-images.githubusercontent.com/167831/40149825-ce482394-592a-11e8-80ec-1a0f59dc8a83.png)

**Comment by wf9a5m75** [comment]
Thank you for considering to support the activity of `@ionic-native/google-maps` and `cordova-plugin-googlemaps`
https://github.com/mapsplugin/cordova-plugin-googlemaps#buy-us-a-beer

**Comment by ugoconsonni** [comment]
Thank for you help @wf9a5m75
