### ISSUE TITLE
Q: keys stored in config.xml

### ISSUE THREAD

**Issue by blahblehblah** [ionic-team/ionic-native-google-maps#251]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

**Current behavior:**
Read keys only from config.xml

**Expected behavior:**
Able to read keys from code instead of config.xml

--

I would like to know if its a MUST to store keys in config.xml, instead of simply providing them before instantiating a map? as we host the app code externally and do not store anything on app but the bootstrapping of it.
Can we simply use the Environment.setEnv for sdk's key instead of config.xml

**Comment by wf9a5m75** [comment]
API key is necessary before building application for Android.
