### ISSUE TITLE
Animations are not show after call a setDiv(). 

### ISSUE THREAD

**Issue by zarelint** [ionic-team/ionic-native-google-maps#253]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [X] **iOS**
- [ ] **Browser**

**Current behavior:**
On ionic project, we call setDiv() to get out of the page,for deattach de map. From a commit post below it can not be seen the out of page transition anymore it means the page don't slide to left. (see video)

**Expected behavior:**
After call a setDiv(), we expect the plugin dont do hard dom refresh and let run the animations transitions again as before the commit

This commit has broken it, forcing a complet redraw dom
https://github.com/mapsplugin/cordova-plugin-googlemaps/commit/4ef4e5ce68716f1a916f5138ff745d7ed9523f76

i've try a more conservative approach removing these lines:

    div.style.display = 'none';
    div.offsetHeight;
    div.style.display = '';

for this one:

`   document.body.style.transform = 'rotateZ(0deg)';`
I see the animations again but the screen is in black si need other approach

**Screen capture or video record:**
[
[demo.mp4.zip](https://github.com/ionic-team/ionic-native-google-maps/files/3647203/demo.mp4.zip)
]

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository, not zip file

**Comment by zarelint** [comment]
sorry i upload here by error i open on googlemaps repo i close here the issue
