### ISSUE TITLE
Help: I would like to know if I can use directions with this plugins

### ISSUE THREAD

**Issue by devfelipereis** [ionic-team/ionic-native-google-maps#26]
Like this one: https://developers.google.com/maps/documentation/javascript/examples/directions-simple

Thank you!

**Comment by devfelipereis** [comment]
I found that is not possible. Sorry.

**Comment by newtmex** [comment]
Did you try combining it with googlemaps script?
`  <script src="http://maps.google.com/maps/api/js"></script>
`
