### ISSUE TITLE
Wrong Error when no map target can be found

### ISSUE THREAD

**Issue by de-robat** [ionic-team/ionic-native-google-maps#260]
https://github.com/ionic-team/ionic-native-google-maps/blob/e7bf28c157e17323cd4c5a37e2fecb4d19440e76/src/%40ionic-native/plugins/google-maps/index.ts#L2493

the last "OR" is probably not intentionally written without parenthisis. It gets evaluated even if targets are of length 0 this way and hides the correct error message. Or am i missing something here?

**Comment by wf9a5m75** [comment]
If you find something, please send a pull request
