### ISSUE TITLE
Cannot show myLocation bearing 

### ISSUE THREAD

**Issue by omkarkhalipe** [ionic-team/ionic-native-google-maps#263]
I want to show maker with current direction user is facing. like this https://i.stack.imgur.com/sACLT.png
I am using current code, and it works on 1-2 phones in Android but does not work on other is Android and iOS
```
let mapOptions: GoogleMapOptions = {
          camera: {
             target: {
               lat:this.lat,
               lng: this.lon
             },
             zoom: 22,
             tilt: 80
           },
           compass: true,
          myLocation: true,
          myLocationButton: true,
          mapToolbar: true,
          
        };
```

Is there a way to make it work?
I am using Ionic 3

**Comment by wf9a5m75** [comment]
The location icon is under the Google Maps native API, not this plugin. It means no way to control it.

**Comment by omkarkhalipe** [comment]
I don't want to change the location icon but show the direction use is facing along with the icon. If that is not possible, can we do it with custom marker?

**Comment by wf9a5m75** [comment]
As I said, that is out of control.
