### ISSUE TITLE
Marker doesnot rotate properly

### ISSUE THREAD

**Issue by developuser** [ionic-team/ionic-native-google-maps#266]
In ionic cordova google map the native marker has been rotated sucessfully based on the input rotation angle, but if i use customized image instead of marker was not rotating properly.here i had used a png image format, kindly help to solve this issue

**Comment by wf9a5m75** [comment]
Rotate property works only default marker.

**Comment by developuser** [comment]
if i use a customized marker image how can i rotate it

**Comment by wf9a5m75** [comment]
You need to rotate the image by yourself, such as using canvas.

**Comment by developuser** [comment]
can i have a sample code for it

**Comment by wf9a5m75** [comment]
Please google it.

**Comment by developuser** [comment]
i am new to ionic, but i had tried did you have any reference kindly share it will be helpful for me.

**Comment by wf9a5m75** [comment]
It's not related with ionic. It's JavaScript problem.

This plugin does not provide the rotation feature for custom marker. That's all.
Beyond that point, you need to implement by yourself.
