### ISSUE TITLE
How to customize info window border? 

### ISSUE THREAD

**Issue by shebinkoshy123** [ionic-team/ionic-native-google-maps#267]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**

How to apply corner radius to info window?
How to change arrow with my own style?

### **Actual:**
![IMG_0583](https://user-images.githubusercontent.com/46756662/68882434-27c36780-0735-11ea-9bae-a721237af14d.jpg)

### **Expected:**
![Expected](https://user-images.githubusercontent.com/46756662/68882485-3dd12800-0735-11ea-9a11-a59e61e40443.png)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/Marker/README.md#base64-encoded-icon

**Comment by wf9a5m75** [comment]
```
let marker: Marker = map.addMarkerSync({
    'position': latLng,
    'title': canvas.toDataURL()
  });
```

**Comment by shebinkoshy123** [comment]
> https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/class/Marker/README.md#base64-encoded-icon

This image is showing info window with square border. we need corner radius.
Note: My question is not about customising marker icon or content inside info-window.

**Comment by wf9a5m75** [comment]
Google Maps Android/iOS infoWindow as bitmap, not HTML.

**Comment by wf9a5m75** [comment]
Alternatively you can choose HTMLInfoWindow class, which is not actual infoWindow, but works like  infoWindow.

**Comment by shebinkoshy123** [comment]
> Alternatively you can choose HTMLInfoWindow class, which is not actual infoWindow, but works like infoWindow.

I tried HTLMInfoWindow and infoWindow as bitmap, but both cases not giving a way to customise the border of the popup.

**Comment by wf9a5m75** [comment]
Since this plugin is **open source**, please look at the code before asking.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/www/HtmlInfoWindow.js

**Comment by lalalalaluk** [comment]
@shebinkoshy123
here is the answer
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2177#issuecomment-375925750

note that css should be in global
if you put in the component css it will not work because of scope problem
