### ISSUE TITLE
Different version of play services

### ISSUE THREAD

**Issue by piernik** [ionic-team/ionic-native-google-maps#271]
In Ionic project I have two plugins: Yours which is dependent on `PLAY_SERVICES_VERSION@15.0.1` and `cordova-plugin-admobpro` (or `cordova-plugin-admobplus`) which is dependent on `PLAY_SERVICES_VERSION@16.0.0`.
When I add both plugins it doesn't compile. I suppose due to play service.

Can I use Your plugin with `16.0.0` ? If yes, how to change it? Have to delete plugin and install once more?

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/README.md#install-optional-variables

**Comment by battika** [comment]
Yes, you need to reinstall the plugin with the variable mentioned in the link above

**Comment by piernik** [comment]
It worked - thanks
