### ISSUE TITLE
TypeError: Cannot read property '_privateInitialize' of undefined (Ionic-Native - Google Map) 

### ISSUE THREAD

**Issue by Fresh-Dev-zunairzakir** [ionic-team/ionic-native-google-maps#272]
As @Ghayyas reported earlier: 
I am also facing same issue
https://github.com/ionic-team/ionic-native-google-maps/issues/148#issue-393233698

Please guide me to resolve this issue.

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by Fresh-Dev-zunairzakir** [comment]
I can't because it's so much private for client. please do some other way, thanks.

**Comment by ztickm** [comment]
> I can't because it's so much private for client. please do some other way, thanks.

You can take out the "private" parts or preferably just change them to placeholders.

**Comment by Binitronics** [comment]
Any solution to this issue? This is how my code runs
    1. Bounds changed (Camera stop moves)
    2. Load data from database based on a given bounds
    3. Clear the map
    4. Add the new markers
My Observation:
1.  If I remove the _map.clear()_ function no problem occurs
2.  The problem occurs if I change the zoom level or drag the map very quickly. 
My project folder setup:
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "^5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "^4.15.0",
    "@ionic-native/device": "^4.20.0",
    "@ionic-native/diagnostic": "^4.20.0",
    "@ionic-native/geolocation": "^4.20.0",
    "@ionic-native/globalization": "^4.20.0",
    "@ionic-native/google-maps": "^4.8.2",
    "@ionic-native/native-storage": "^4.20.0",
   "@ionic-native/sqlite": "^4.20.0",

    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-globalization": "^1.11.0",
    "cordova-plugin-googlemaps": "^2.6.2",
    "cordova-plugin-nativestorage": "^2.3.2",
    "cordova-sqlite-storage": "^4.0.0",
    "cordova.plugins.diagnostic": "^4.0.10",
Console result:
`TypeError: Cannot read property '_privateInitialize' of undefined
__zone_symbol__currentTask:e {_zone: r, runCount: 0, _zoneDelegates: null, …}
message:"Cannot read property '_privateInitialize' of undefined"
stack:"TypeError: Cannot read property '_privateInitialize' of undefined\n    at Map.<anonymous> (http://localhost/plugins/cordova-plugin-googlemaps/www/Map.js:1339:12)\n    at http://localhost/plugins/cordova-plugin-googlemaps/www/commandQueueExecutor.js:63:21\n    at t.invoke (http://localhost/build/polyfills.js:3:14976)\n    at r.run (http://localhost/build/polyfills.js:3:10143)\n    at http://localhost/build/polyfills.js:3:20242\n    at t.invokeTask (http://localhost/build/polyfills.js:3:15660)\n    at r.runTask (http://localhost/build/polyfills.js:3:10834)\n    at o (http://localhost/build/polyfills.js:3:7894)"
__proto__:Error {constructor: , name: "TypeError", message: "", …}
TypeError: Cannot read property '_privateInitialize' of undefined
    at Map.<anonymous> (http://localhost/plugins/cordova-plugin-googlemaps/www/Map.js:1339:12)
    at http://localhost/plugins/cordova-plugin-googlemaps/www/commandQueueExecutor.js:63:21
    at t.invoke (http://localhost/build/polyfills.js:3:14976)
    at r.run (http://localhost/build/polyfills.js:3:10143)
    at http://localhost/build/polyfills.js:3:20242
    at t.invokeTask (http://localhost/build/polyfills.js:3:15660)
    at r.runTask (http://localhost/build/polyfills.js:3:10834)
    at o (http://localhost/build/polyfills.js:3:7894)`

**Comment by Binitronics** [comment]
I wish I know your dress to send you a beer :).

**Comment by maximilianloy** [comment]
Same here

  "dependencies": {
    "@angular/animations": "8.2.14",
    "@angular/common": "8.2.14",
    "@angular/core": "8.2.14",
    "@angular/forms": "8.2.14",
    "@angular/platform-browser": "8.2.14",
    "@angular/platform-browser-dynamic": "8.2.14",
    "@angular/router": "8.2.14",
    "@auth0/cordova": "0.4.0",
    "@ionic-native/app-version": "5.19.1",
    "@ionic-native/barcode-scanner": "5.19.1",
    "@ionic-native/camera": "5.19.1",
    "@ionic-native/core": "5.19.1",
    "@ionic-native/file": "5.19.1",
    "@ionic-native/firebase-x": "5.19.1",
    "@ionic-native/google-maps": "5.5.0",
    "@ionic-native/http": "5.19.1",
    "@ionic-native/in-app-browser": "5.19.1",
    "@ionic-native/native-audio": "5.19.1",
    "@ionic-native/network": "5.19.1",
    "@ionic-native/open-native-settings": "^5.20.0",
    "@ionic-native/social-sharing": "5.19.1",
    "@ionic-native/splash-screen": "5.19.1",
    "@ionic-native/status-bar": "5.19.1",
    "@ionic/angular": "4.11.7",
    "@ionic/storage": "2.2.0",
    "@mapbox/polyline": "1.1.0",
    "@ngx-progressbar/core": "5.3.2",
    "@ngx-translate/core": "11.0.1",
    "@ngx-translate/http-loader": "4.0.0",
    "auth0-js": "9.12.2",
    "cordova-android": "8.1.0",
    "cordova-browser": "6.0.0",
    "cordova-ios": "5.1.1",
    "cordova-open-native-settings": "^1.5.2",
    "cordova-plugin-advanced-http": "^2.3.1",
    "cordova-plugin-androidx": "1.0.2",
    "cordova-plugin-androidx-adapter": "1.1.0",
    "cordova-plugin-app-version": "0.1.9",
    "cordova-plugin-camera": "^4.1.0",
    "cordova-plugin-customurlscheme": "5.0.0",
    "cordova-plugin-device": "2.0.3",
    "cordova-plugin-file": "6.0.2",
    "cordova-plugin-firebasex": "7.0.1",
    "cordova-plugin-geolocation": "4.0.2",
    "cordova-plugin-googlemaps": "2.6.2",
    "cordova-plugin-inappbrowser": "3.2.0",
    "cordova-plugin-ionic-keyboard": "2.2.0",
    "cordova-plugin-ionic-webview": "4.1.3",
    "cordova-plugin-nativeaudio": "3.0.9",
    "cordova-plugin-network-information": "2.0.2",
    "cordova-plugin-safariviewcontroller": "1.6.0",
    "cordova-plugin-splashscreen": "5.0.3",
    "cordova-plugin-statusbar": "2.4.3",
    "cordova-plugin-whitelist": "1.3.4",
    "cordova-plugin-wkwebview-inject-cookie": "1.0.2",
    "cordova-plugin-x-socialsharing": "^5.6.3",
    "core-js": "2.6.9",
    "es6-promise-plugin": "^4.2.2",
    "file-saver": "2.0.2",
    "gps-to-gpx": "1.4.0",
    "hammerjs": "2.0.8",
    "he": "1.2.0",
    "ion-bottom-drawer": "2.0.0",
    "moment": "2.24.0",
    "ng2-tooltip-directive": "2.8.17",
    "pdfmake": "0.1.65",
    "phonegap-plugin-barcodescanner": "8.1.0",
    "rxjs": "6.5.4",
    "sentry-cordova": "0.17.0",
    "tslib": "1.10.0",
    "web-animations-js": "2.3.2",
    "zone.js": "0.9.1"
  }

**Comment by Binitronics** [comment]
Is this issue resolved?

**Comment by wf9a5m75** [comment]
Please use the multiple_maps branch code
