### ISSUE TITLE
Route playback

### ISSUE THREAD

**Issue by developuser** [ionic-team/ionic-native-google-maps#277]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Expected behavior:** how to combine the list of gps coordinates with respective time to create a route playback, for the past one hour where the vehicle has travelled

**Comment by wf9a5m75** [comment]
This is not for Q&A forum :)
