### ISSUE TITLE
Error Plugin GoogleMaps Create map

### ISSUE THREAD

**Issue by matheusCMendes** [ionic-team/ionic-native-google-maps#279]
Hey,

Good morning, I have a problem with the plugin because, i try using it and give these problems:

ERROR TypeError: Cannot read property 'constructor' of undefined
    at checkAvailability (vendor.js:82250)
    at Function.GoogleMaps.create (vendor.js:64728)
    at HomePage.webpackJsonp.249.HomePage.loadMap (main.js:77)
    at HomePage.webpackJsonp.249.HomePage.ionViewDidLoad (main.js:62)
    at ViewController._lifecycle (vendor.js:22625)
    at ViewController._didLoad (vendor.js:22508)
    at NavControllerBase._didLoad (vendor.js:53925)
    at t.invoke (polyfills.js:3)
    at Object.onInvoke (vendor.js:5396)
    at t.invoke (polyfills.js:3)

you can help me?  
[Home.zip](https://github.com/ionic-team/ionic-native-google-maps/files/4026898/Home.zip)

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub, don't attach a zip file.
Since I mostly check user code from mobile (because super busy), I can't open it.

**Comment by matheusCMendes** [comment]
My repository is this : https://github.com/matheusCMendes/TestGoogleMaps

**Comment by matheusCMendes** [comment]
Do you can help me ?

**Comment by wf9a5m75** [comment]
Thank you for sharing your project.
The reason is `ionic-native/core` is mismatched.

```
    "@ionic-native/core": "^4.20.0",
    "@ionic-native/google-maps": "^5.5.0",
```

**Comment by matheusCMendes** [comment]
Thanks :)

**Comment by Donaldmag** [comment]
> Thank you for sharing your project.
> The reason is `ionic-native/core` is mismatched.
> 
> ```
>     "@ionic-native/core": "^4.20.0",
>     "@ionic-native/google-maps": "^5.5.0",
> ```

This helped me alot thanks but now white screen on the #map region.

**Comment by wf9a5m75** [comment]
@Donaldmag please write your situation with more information
