### ISSUE TITLE
ionic-native google maps

### ISSUE THREAD

**Issue by KazimAgha** [ionic-team/ionic-native-google-maps#28]
Even i run this command 
npm install @ionic-native/google-maps
and on command prom it shows @ionic-native/google-maps@4.8.2 updated
Still when in app.module.ts.. I code `import { GoogleMaps } "@ionic-native/google-maps"` its says component not found. Any suggestion where would i be wrong or any other solution

**Comment by wf9a5m75** [comment]
Please share your project files on github. Without checking your code, how can I help you?

**Comment by wf9a5m75** [comment]
ping

**Comment by battika** [comment]
Version 4.8.2 works for me, really wondering what went wrong here

**Comment by wf9a5m75** [comment]
Since no response from @KazimAgha, I close this thread.
