### ISSUE TITLE
cordova-plugin-googlemaps is not installed or ready yet IONIC 4 & Capacitor ios

### ISSUE THREAD

**Issue by THEDOWNCOUNTRY** [ionic-team/ionic-native-google-maps#283]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

It gives me the error [GOOGLEMAPS] cordova-plugin-googlemaps is not installed or ready yet when I try to open the map page.

**Expected behavior:**

To start the map

![IMG_6992](https://user-images.githubusercontent.com/7623461/72653584-9a310d80-3959-11ea-89bc-51059e63d259.PNG)

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Capacitor is not supported yet

**Comment by wf9a5m75** [comment]
```
$> ionic cordova plugin add cordova-plugin-googlemaps

$> ionic cordova run android
```

**Comment by THEDOWNCOUNTRY** [comment]
It also did not work for ionic 4 with cordova it said. We need to run ionic cordova run browser or something. Could you provide support private support for ios capacitor?

**Comment by wf9a5m75** [comment]
> Could you provide private support for ios capacitor?

I have no time to develop this.

**Comment by THEDOWNCOUNTRY** [comment]
My next question is that. Should this plugin work on ionic 4 for iOS? because it does not it have an error saying that should not run on ionic serve.

**Comment by wf9a5m75** [comment]
This plugin works with cordova.
`ionic serve` runs only web part.
That's why you need to use `ionic cordova run iOS/android`.

You can add `-l` option to live reload.

**Comment by dupiesdupreez** [comment]
Does the whole of the internet not contain an answer for this question?

**Comment by ksouthworth** [comment]
> This plugin works with cordova.
> `ionic serve` runs only web part.
> That's why you need to use `ionic cordova run iOS/android`.
> 

ionic cordova run ios 

Does not work, though, on my machine it skips the build step for this plugin thinking it’s not a compatible iOS plugin for some reason?

**Comment by ndrake** [comment]
The plugin doesn't currently support iOS when using Capacitor. It works find on iOS if you are using Cordova.

**Comment by ksouthworth** [comment]
> The plugin doesn't currently support iOS when using Capacitor. It works find on iOS if you are using Cordova.

Thanks for the response, is there anyone working on iOS Capacitor support?  Is it a small, medium, or large task to get Capacitor working with this plugin?

**Comment by unrealmach** [comment]
I have tested the implementation added to the BROWSER platform and it works excellent even if you have implemented Capacitor. But unfortunately, I failed to compile the Android app with this error: failed linking references.

**Comment by wf9a5m75** [comment]
In order to support Capacitor iOS, I need to make a big change for three platforms, and unfortunately I have no time to work for that

**Comment by moplin** [comment]
Is there any way to help with those changes, there's a lot of bright people here. Maybe if you can share the idea of the problem and what would be required, the community could help.
I understand that if you are completely busy, you won't be able. But here are a few ones that need it, we might be able to put some time and pull the fix, of course, if we understand what's required.

**Comment by wf9a5m75** [comment]
Thanks, but do you understand how does this plugin manage internally?
In general Cordova plugin, only one instance is available. But this plugin generates many instances as you know.
I need to make a big change for this internal implementation. This is not only for iOS but also Android and web platforms as well

**Comment by stevebrowndotco** [comment]
@THEDOWNCOUNTRY  I have extensive experience with this plugin, YES it is possible to run ionic cordova in all three: ios, android, and iOS for ionic versions 3,4, and now 5. @wf9a5m75 has designed it that way, and the docs explain that. What are you having trouble with exactly?

**Comment by wf9a5m75** [comment]
I made a fundraising of this topic.
If you really want to use this plugin on Capacitor iOS, please support my activity.

[Fundraising : support for Capacitor iOS](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781)
