### ISSUE TITLE
Google Maps does not render on certain devices.

### ISSUE THREAD

**Issue by Fresh-Dev-zunairzakir** [ionic-team/ionic-native-google-maps#290]
Just like same issue as mentioned here:
https://github.com/ionic-team/ionic-native-google-maps/issues/150
I am fresh dev, please help me in this! Thanks.

**Comment by wf9a5m75** [comment]
If you run your app does not show the map on all Android devices, it's your API key problem.

If only one device does not show, the device problem. Just give up.

**Comment by Fresh-Dev-zunairzakir** [comment]
@wf9a5m75 I don't think so since It is working fine for platform browser as well as ionic serve.

`<div _ngcontent-kbs-c35="" class="ps-form-map _gmaps_cdv_" id="google-map-canvas" __pluginmapid="map_0_476520398831" __plugindomid="pgm220196381411" style="overflow: hidden;"><div style="position: absolute; left: 0px; top: 0px; width: 0px; height: 0px; overflow: visible; z-index: 1;" __plugindomid="pgm395663358831"></div></div>`

This is the last element that has '0px' height and width.

Please tell me confirm issue and how to resolve, Thanks for quick reply :)

**Comment by wf9a5m75** [comment]
Implementation of browser and Android/iOS are different.

**Comment by Fresh-Dev-zunairzakir** [comment]
Yes for Browser I have implemented separate implementation and for Android I did same as mentioned in your presentation.
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.p

And I was working before but I don't know why it suddenly stop working.
Please understand the scenario.

**Comment by Fresh-Dev-zunairzakir** [comment]
Any response?

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub repository. You can share your code in private/public repository, or please create a small project that reproduce your issue.

**Comment by Fresh-Dev-zunairzakir** [comment]
![Map On Portrait mode](https://drive.google.com/open?id=1k4aNqDSO0g7E-akBpGf3xTXS3oldmkPQ)

**Comment by wf9a5m75** [comment]
I asked "please share on GitHub repository" not Google drive. I can't see it from mobile device ( I'm super busy, so I don't have enough time to check your code with setting on a chair, that's why)

Please share your code on GitHub repository

**Comment by Fresh-Dev-zunairzakir** [comment]
@wf9a5m75 It's not the code they are just images which I am not able to attach in comments. Kindly check If you can.
