### ISSUE TITLE
ionic native before page load broken image

### ISSUE THREAD

**Issue by semihertugrul** [ionic-team/ionic-native-google-maps#297]
<img width="456" alt="Screen Shot 2020-04-01 at 14 54 20" src="https://user-images.githubusercontent.com/39457284/78134889-8c076f00-7429-11ea-803b-456a50c9b6bd.png">

hi,
i have a problem. Broken image appears while loading the page. Actually this problem is also your demo application( https://mapsplugin.github.io/ionic-googlemaps-quickdemo-v4/home ). 
What is the solution to this? can you help me?

**Comment by wf9a5m75** [comment]
That's just lauch image . Ignore it

**Comment by semihertugrul** [comment]
the same exists in my project, so it's important to me. what is its parameter or usage? I could not find.

**Comment by wf9a5m75** [comment]
That's not this plugin part.

**Comment by wf9a5m75** [comment]
Why don't you open the devtools of chrome, and check what image is missing?

**Comment by semihertugrul** [comment]
I checked and think it is related to ionic map. because the same problem exists in your demo application. So I think it's relevant to you.

**Comment by wf9a5m75** [comment]
Ok, please point out the location of the code. The problem is not related with this plugin at all. All source code is open. Please find who display the broken image

**Comment by wf9a5m75** [comment]
This plugin controls **only** Google maps, not launching image.
