### ISSUE TITLE
Can't use marker.remove() or map.clear() functions

### ISSUE THREAD

**Issue by Gabplay** [ionic-team/ionic-native-google-maps#3]
I'm pushing markers to this array 'temp1' shown in the console, but I cant use .remove() function. I tested .getPosition() and .getId() functions and they worked.

Same problem with map.clear();

`TypeError: Right-hand side of 'instanceof' is not an object`

![cbxe2](https://user-images.githubusercontent.com/12158575/38177999-a5adc830-35df-11e8-8a57-02e7ee943d0d.png)

**Comment by wf9a5m75** [comment]
Please share the project files that reproduce your issue 100% onto the GitHub

**Comment by wf9a5m75** [comment]
Please invite me to the bitbucket. My email address is open in my profile page.

**Comment by Gabplay** [comment]
Thank you for the help, this is the correct branch https://bitbucket.org/Gabcoder/tcctestes/src/e84f14e909f0ce90314c49d114bce5584ab77602/?at=nativemap

**Comment by wf9a5m75** [comment]
Could you indicate the steps how to reproduce your issue in your app?
![capture](https://user-images.githubusercontent.com/167831/38207106-865f6272-3661-11e8-9c83-e81166e38045.png)

**Comment by Gabplay** [comment]
Yes, if you tap on the blue arrow it will open a popover, then tap the first option it will open the map with some bus markers, but I can't remove them to update the markers array.

**Comment by wf9a5m75** [comment]
So how to update the array from UI?

**Comment by wf9a5m75** [comment]
And the map page is `main_map.ts` or `cartao_map.ts`?

**Comment by wf9a5m75** [comment]
Confirmed your issue.

**Comment by wf9a5m75** [comment]
Okay, please reinstall the `@ionic-native/google-maps@4.6.2`.

```
$> npm uninstall \@ionic-native/google-maps
$> npm install \@ionic-native/google-maps@4.6.2
```

**Comment by Gabplay** [comment]
Reinstalled it with 4.6.2 but my project says "Cannot find module '@ionic-native/google-maps'".

Any idea?

**Comment by wf9a5m75** [comment]
You didn't install `ionic-native/google-maps@4.6.2.` yet.

**Comment by wf9a5m75** [comment]
https://www.npmjs.com/package/@ionic-native/google-maps

**Comment by Gabplay** [comment]
![capturar](https://user-images.githubusercontent.com/12158575/38218565-98efa356-36a8-11e8-9efc-08996f714915.PNG)

**Comment by wf9a5m75** [comment]
That's your environment problem, not plugin's bug.
My recommendation is to remove the `node_modules` folder, then reinstall all plugins again.

**Comment by Gabplay** [comment]
I'm not sure but it seems that 4.6.2 is not installing/compiling correctly because it shows the whole folders structure, while 4.6.1 shows only some js files...

**Comment by wf9a5m75** [comment]
Umm.

**Comment by wf9a5m75** [comment]
I updated `4.6.3`. Try again please.

**Comment by Gabplay** [comment]
Thanks, now it's working!!!

**Comment by collindutter** [comment]
I'm experiencing a similar issue on 5.0.0-beta.20. Getting this error when trying to call any remove or clear method.
`ERROR Error: Uncaught (in promise): TypeError: plugin.constructor.getPluginRef is not a function`

Any idea what might be causing this?

**Comment by wf9a5m75** [comment]
Please create a new issue instead of communicating in an old thread.
