### ISSUE TITLE
Google map does not load on Huawei P9 Lite

### ISSUE THREAD

**Issue by olliadri** [ionic-team/ionic-native-google-maps#30]
**Problem**
Map is blank when deployed on Huawei P9 Lite.

**Versions plugin**
```
@ionic-native/core: 5.2.10
@ionic-native/google-maps: 4.8.2
cordova-plugin-googlemaps: 2.3.1
```
**Versions phone**
Android: 7.0
Play services: 12.6.73

**Repo**
https://github.com/olliadri/test-maps

**Observations**
Working on Moto G5s.
Would downgrading be a solution here?

**Comment by wf9a5m75** [comment]
Ah, yes. Please reinstall the `cordova-plugin-googlmaps` from the multiple_maps branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...

```

**Comment by olliadri** [comment]
Thanks for the quick response.
Reinstalled with the given command, still a blank map.
Updated the repository to reflect the changes.

**Comment by lobnazrelli** [comment]
i have the same problem, when i add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ... i can't run, 
there is the log : 
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by wf9a5m75** [comment]
@lobnazrelli Your's one is different problem.

**Comment by lobnazrelli** [comment]
my problem is : google maps is working fine in samsung and iphone but Map is blank when deployed on Huawei GR3, when i was done : 
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
the project not building

**Comment by battika** [comment]
Funnily enough I have the same exact problem. I did not want to believe my
own eyes it is only the huawei p9 lite affected. It used to work with
version 2.2.8 for sure. I perform additional tests tonight and try to
figure out when it got broken.

**Comment by wf9a5m75** [comment]
@lobnazrelli Due to `Unable to merge dex` log, your project contains different Google Play Services SDK versions.

**Comment by wf9a5m75** [comment]
@olliadri I just built your project and run it on Android 4.4.4.

<img src="https://user-images.githubusercontent.com/167831/40132801-a3903098-58f2-11e8-9bd7-1a03e56fe4ca.png" width="250">

**Comment by battika** [comment]
Actually, Huawei P9 lite is running Android 7.0. I start testing now

**Comment by olliadri** [comment]
Indeed, it runs on Android 7.0 as I stated in the issue.

**Comment by battika** [comment]
Hmmm, it is getting even more interesting. I went back to version 2.2.8 which I am sure it used to work as my primary testing device is a Huawei P9 Lite and the map no longer works. Same exact code runs happily on Nexus 5 and SGS7. I also switched back to Cordova Android 6.4 with no difference. I keep on testing...

**Comment by wf9a5m75** [comment]
@lobnazrelli https://github.com/ionic-team/ionic-native-google-maps/issues/5#issuecomment-380693358

**Comment by wf9a5m75** [comment]
@olliadri Try v2.3.2

```
$> cordova plugin rm  cordova-plugin-googlemaps

$> cordova plugin add  cordova-plugin-googlemaps@2.3.2
```

**Comment by battika** [comment]
Huawei clients not only P9 lite users but others have started reporting errors. I give this new version a go come back to you

**Comment by battika** [comment]
![playservices](https://user-images.githubusercontent.com/1209088/40158483-11d062c8-59a5-11e8-8559-666e639752fe.jpg)

@wf9a5m75 unfortunately, it does not work on P9 Lite either. You left a debug message in the code when putting the HTML element, it is not disturbing or anything, just FYI...

Guys, I have just downgraded Play Services to the version 12.5.18 released in March (see in the screenshot) and the sample app works on my P9 Lite. Can anyone else check this for me? I grabbed the play services APK from apkmirror.com

**Comment by wf9a5m75** [comment]
>You left a debug message in the code when putting the HTML element, it is not disturbing or anything, just FYI...

Oh, sorry.

**Comment by wf9a5m75** [comment]
@battika I published v2.3.3 (just only comment out the debug code)

**Comment by battika** [comment]
Thanks a lot for your quick action.
In the meantime what I did was removed play services from my cell phone and reinstall them from scratch. I used the latest version in the Google play store. To my surprise it started working OK on my P9 Lite. I removed and reinstalled play services couple of times and I never got the problem back. So probably the latest play services update screwed up something on Huawei Devices but reinstalling play services helps. As I cannot replicate the problem any longer I am wondering if someone with the same problem can test this process and revert back to us. Thank you in advance.

**Comment by olliadri** [comment]
I will test the reinstalling play services case and the case of downgrading the plugin. I'll report back soon.

**Comment by battika** [comment]
Thanks a lot I really look forward to it

**Comment by olliadri** [comment]
@battika How did you force it to update, or dit it update automatically? It seems I need to restart my device to make updates happen. Did you also uninstall Instant Apps?

**Comment by olliadri** [comment]
The issue is indeed the version of Google Play Services. Google is looking into this issue at the moment.
https://issuetracker.google.com/issues/79405933

A temporary workaround for this was commented on the issue:
https://issuetracker.google.com/issues/79405933#comment19

I could reproduce the problem if I restarted my device. And could make it work again with the workaround. You will need to clear all data from Google Play Services after a reboot of the device.

**Comment by battika** [comment]
I did not uninstall Instant Apps, only Google Play Services. I downloaded a small free utility called Google Services Info to monitor what's currently running on my system.
