### ISSUE TITLE
Ionic 4: Icon markers not shown correctly on Android

### ISSUE THREAD

**Issue by eviv3k** [ionic-team/ionic-native-google-maps#300]
**I'm submitting a...**
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:** 
- [x] Android
- [ ] iOS

**Cordova Information:**

> cordova-background-geolocation-lt 3.4.2 "BackgroundGeolocation"
> cordova-open-native-settings 1.5.2 "Native settings"
> cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
> cordova-plugin-background-mode 0.7.3 "BackgroundMode"
> cordova-plugin-badge 0.8.8 "Badge"
> cordova-plugin-camera 4.1.0 "Camera"
> cordova-plugin-camera-preview 0.11.1 "cordova-plugin-camera-preview"
> cordova-plugin-compat 1.2.0 "Compat"
> cordova-plugin-device 2.0.3 "Device"
> cordova-plugin-dialogs 2.0.2 "Notification"
> cordova-plugin-file 6.0.2 "File"
> cordova-plugin-file-transfer 1.7.1 "File Transfer"
> cordova-plugin-flashlight 3.2.0 "Flashlight"
> cordova-plugin-googlemaps 2.7.0 "cordova-plugin-googlemaps"
> cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
> cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
> cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
> cordova-plugin-network-information 2.0.2 "Network Information"
> cordova-plugin-save-image 0.3.0 "SaveImage"
> cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
> cordova-plugin-splashscreen 5.0.3 "Splashscreen"
> cordova-plugin-statusbar 2.4.3 "StatusBar"
> cordova-plugin-vibration 3.1.1 "Vibration"
> cordova-plugin-whitelist 1.3.4 "Whitelist"
> cordova.plugins.diagnostic 5.0.1 "Diagnostic"

**Current behavior:**
**I use `@ionic-native/google-maps` and `cordova-plugin-googlemaps@2.7.0`**
When the marker icon should be shown, it will shown as the default red marker instead, when I use:
`this.map.addMarker({
   icon: { url: '/assets/icon/startDrive.png' },
   position: latLng
});`

Marker Icons not shown correctly `url:  '/assets/icon/startDrive.png'`

What is the solution to this?

Thanks

**Comment by wf9a5m75** [comment]
Hey, could you check demo, documents, or more test before asking?
https://mapsplugin.github.io/ionic-googlemaps-quickdemo-v4/

**Comment by eviv3k** [comment]
Thank you! :) 
I used: `url: './assets/icon/startDrive.png`

**Comment by wf9a5m75** [comment]
If the path start with `/`, it means the file path on the device. Start with `./` or without anything (i.e, `assets/icon/startDrive.png`), means relative path from the url.

**Comment by eviv3k** [comment]
I used url: `assets/icon/startDrive.png`. not correctly for android but iOS only.
Also used url: `./assets/icon/startDrive.png`. it correctly Android.
