### ISSUE TITLE
There are any UiWebView reference in this plugin ?

### ISSUE THREAD

**Issue by ulver2812** [ionic-team/ionic-native-google-maps#303]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

- "@ionic-native/core": "4.20.0"
- "@ionic-native/google-maps": "^4.21.0"

I'm asking this because the App Store will no longer accept new apps using UIWebView as of April 2020 and app updates using UIWebView as of December 2020. Instead of UIWebView Apple requires WKWebView. 

Here the Apple announcement:
https://developer.apple.com/news/?id=12232019b

**Comment by wf9a5m75** [comment]
No

**Comment by HansKrywaa** [comment]
I removed them, and the PR was merged. There are no References anymore!

**Comment by ulver2812** [comment]
@HansKrywaa which version of the plugin ? I'm using the 4.21.0

**Comment by HansKrywaa** [comment]
No 4.21.0 is the Version of the Ionic Wrapper not the Cordova Plugin. This is this one: https://github.com/mapsplugin/cordova-plugin-googlemaps - Latest Version is **2.7.1**

**Comment by ulver2812** [comment]
@HansKrywaa ok I understand, since I need to use the google maps plugin with iOS 9 can I use the latest version of 'cordova-plugin-googlemaps' v2.7.1 and this plugin latest version 5.5.0 ?

Alternatively can I use the 'cordova-plugin-googlemaps' v2.7.1 with this plugin wrapper version 4.21.0 ?

Where I can find a compatibility table that show which version of this plugin wrapper is compatible with specific version of 'cordova-plugin-googlemaps' and iOS version ?

Thanks a lot

**Comment by wf9a5m75** [comment]
Could you tell me why do you start need to still support iOS9?
Even the Google's SDK drops the support it

**Comment by ulver2812** [comment]
@wf9a5m75 I wouldn't want to do it but I'm developing an app for a specific business client that has 25 iPad with iOS 9.3.5 and I can't ask him to buy 25 brand new iPad so I'm trying to find a solution to work with ios 9.

**Comment by wf9a5m75** [comment]
If I create an enterprise support plan, will your company pay the amount?
Such as support older versions, or private support.
