### ISSUE TITLE
Can't build using capacitor + cordova integration.

### ISSUE THREAD

**Issue by guibulator** [ionic-team/ionic-native-google-maps#304]
**I'm submitting a ...**
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
> npx cap ls
  Found 0 Capacitor plugins for android:
  Found 1 Cordova plugin for android
    cordova-plugin-googlemaps (2.7.1)
```

I'm using these versions
`"@capacitor/core": "2.0.1",
    "@ionic-native/core": "^5.24.0",
    "@ionic-native/google-maps": "^5.5.0"`

**Current behavior:**

I have setup a project using ionic + capacitor and set it up to work also with cordova integration since I want to use the native google map sdk for android. When I try to build the project, I always get errors with missing packages from ANDROID_SUPPORT_V4_VERSION (PermissionChecker, NonNull, annotation). I tried a lot of different things but nothing seems to work. I did try to setup the example using cordova  [HelloMap project](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/hello-world/README.md) and it works both with `cordova run android` or if I build it using Android Studio. The same cordova-plugin-googlemaps is used in both projects. It looks like a Gradle build sequence isssue. I do see the output from the build mentionning the preferences & ANDROID_SUPPORT and looks like it's successful. Much of the example I see on the web are not related to capacitor + cordova integration.

**Expected behavior:**

Being able to build and deploy on my android phone.

**Screen capture or video record:**
![image](https://user-images.githubusercontent.com/5513740/80626574-a6c70680-8a1c-11ea-9411-c658fa8f8cd0.png)
![image](https://user-images.githubusercontent.com/5513740/80626795-fb6a8180-8a1c-11ea-9a92-66847b27d97d.png)

**Related code, data or error log (please format your code or data):**

1. [Access to my demo project](https://github.com/guibulator/planIt/tree/googlePluginQuestion)
2. Outpout when running `gradle build --scan` ->
[Gradle scan](https://scans.gradle.com/s/ymmwxla3okwgo)

Thanks for your time!

**Comment by wf9a5m75** [comment]
`Capacitor` platform is not supported at this time.

**Comment by guibulator** [comment]
Ok sorry, I had the impression it was supported only for Android and not IOS. I'll start with the v3 API for now. Thanks for your quick response.

**Comment by wf9a5m75** [comment]
In order to support Capacitor (especially iOS), I need to make a big change internal code of the maps plugin, but I have no enough time to work around that.

Sorry about that.

**Comment by wf9a5m75** [comment]
I made a fundraising to implement the code for supporting Capacitor iOS.
Please join and support the project!

[Fundraising: Support for Capacitor iOS platform](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2781)
