### ISSUE TITLE
Not working in ipad ios version 13.4.1

### ISSUE THREAD

**Issue by kokulansk** [ionic-team/ionic-native-google-maps#308]
On ipad  ios version 13.4.1 the google map appears blank

**Comment by wf9a5m75** [comment]
I have no problem the same condition

**Comment by kokulansk** [comment]
what is the version google map version on pod file

**Comment by wf9a5m75** [comment]
Plugin or SDK?

**Comment by wf9a5m75** [comment]
Current Google maps plugin uses https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk

We don't use CocoaPod anymore, because many beginners fail to compile.
I use Google Maps SDK for iOS

**Comment by kokulansk** [comment]
Actually Location service is failing on ipad ios version 13.4.1

**Comment by wf9a5m75** [comment]
I have no problem. If everyone faces the problem, I should get more reports.

Please share your project files (not past your code or zip file) on GitHub repository.
I will check your code
