### ISSUE TITLE
Ionic Android StreetViewPanorama Build Fails

### ISSUE THREAD

**Issue by ecomunicarte** [ionic-team/ionic-native-google-maps#31]
Using Ionic and compiling for android with the configurations and details I'll write below, builds fails due to StreetViewPanorama Class with an "Execution failed for task ':compileDebugJavaWithJavac'. " error.

Details and the trace error are about StreetViewPanoramaClass inside the clases:
- PluginStreetViewPanorama.java
- CordovaGoogleMaps.java
- MyPlugin.java

Ionic cordova plugin ls outputs:

> cordova plugin ls
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-plugin-admobpro 2.31.5 "AdMob Plugin Pro"
cordova-plugin-camera 4.0.2 "Camera"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-extension 1.5.4 "Cordova Plugin Extension"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-file-opener2 2.0.19 "File Opener2"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.1.16 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.4.1 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.2.1 "Cordova sqlite storage plugin"
ionic-plugin-keyboard 2.2.1 "Keyboard"
mx.ferreyra.callnumber 0.0.2 "Cordova Call Number Plugin"
onesignal-cordova-plugin 2.4.0 "OneSignal Push Notifications"

Ionic cordova platform ls outputs:

> cordova platform ls
Installed platforms:
  android 6.4.0
Available platforms: 
  browser ~5.0.1
  ios ~4.5.4
  osx ~4.0.1
  windows ~5.0.0
  www ^3.12.0

I have installed the plugin with the command:
>ionic cordova plugin add cordova-plugin-googlemaps@latest \
    --variable API_KEY_FOR_ANDROID="myapikey" \
    --variable API_KEY_FOR_IOS="myapikey" \
    --variable PLAY_SERVICES_VERSION="11.8.0" \
    --variable ANDROID_SUPPORT_V4_VERSION="24.1.0" \
    --variable LOCATION_WHEN_IN_USE_DESCRIPTION="mymessage" \
    --variable LOCATION_ALWAYS_USAGE_DESCRIPTION="mymessage"

and next:
>npm install --save @ionic-native/core@latest @ionic-native/google-maps@latest

If i downgrade the plugin to 2.9, I obtain a blank page in place of a map.

I have tried to follow the trace of the error and modify the code in order to obtain a succesfull build. Finally, it builds successfully modifying the classes I mentioned before in the next way:

-  **PluginStreetViewPanorama.java**: I have delete all code. I have emptied the class.
- **CordovaGoogleMaps.java**: In the line 468 starts the function getgetPanorama(...){...}, I have deleted all lines related with PluginStreetViewPanorama. The final result is:

```
@TargetApi(Build.VERSION_CODES.HONEYCOMB)
  public void getPanorama(final JSONArray args, final CallbackContext callbackContext) throws JSONException {
    //------------------------------------------
    // Create an instance of PluginStreetView class.
    //------------------------------------------
    JSONObject meta = args.getJSONObject(0);
    String mapId = meta.getString("id");
    Log.d(TAG, "---> mapId = " + mapId);

  }
```
- **MyPlugin.java**:  Over the line 82 there is a condition that if true, references StreetViewPanorama. I have deleted that reference. The result is:

```
...
              } else if (TAG.startsWith("streetview")) {

              }
...

```

After these steps, build android command has finally succeed. And after run on device, all works fine.

But I don't want to do these changes each time I have to build an app or a new version, or re-add this plugin. What is really happening? How can I fix it?

**Comment by battika** [comment]
You need to use Google play services version 15.0 where  these missing
methods are implemented.

Probably one of your plug-ins define an earlier version of Google play
services that you will need to override. For example one signal Plug-in is
using version 11.8 which is Incompatible with the current version of Google
maps plug-in. If for some reason you are not able to Use the latest version
of Google play services you need to make the change that you highlighted
above.

**Comment by wf9a5m75** [comment]
`--variable PLAY_SERVICES_VERSION="15.0.1" `

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since this is not this plugin's bug and OneSignal-Cordova-SDK has solved this issue, I close this thread.
