### ISSUE TITLE
Google Maps plugin does not install, remains in install mode

### ISSUE THREAD

**Issue by pclr0120** [ionic-team/ionic-native-google-maps#311]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ X] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ X] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.20",
    "@angular/cli": "~8.3.23",
    "@angular/compiler": "~8.2.14",
    "@angular/compiler-cli": "~8.2.14",
    "@angular/language-service": "~8.2.14",
    "@capacitor/cli": "2.0.0",
    "@ionic/angular-toolkit": "^2.1.1",
    "@ionic/lab": "3.1.3",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-ionic-keyboard": "^2.2.0",
    "cordova-plugin-ionic-webview": "^4.1.3",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-statusbar": "^2.4.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  },
```
iOS project created with cordova-ios@5.1.1
Installing "cordova-plugin-googlemaps" for ios
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by pclr0120** [comment]
![Captura de Pantalla 2020-05-13 a la(s) 12 28 43](https://user-images.githubusercontent.com/23533313/81850740-a434d880-9515-11ea-9743-98f9b0a16911.png)

**Comment by wf9a5m75** [comment]
Did you install with `ionic cordova plugin add cordova-plugin-googlemaps`?

**Comment by iChristosK** [comment]
Can confirm! Facing the same issue.

**Comment by wf9a5m75** [comment]
Please share your project files on git repository.
I have no idea how you guys install this plugin.

**Comment by wf9a5m75** [comment]
Please try with `ionic-native/core` v5.5.0

**Comment by wf9a5m75** [comment]
And make sure you installed xcode 11

**Comment by ceroideas** [comment]
I'm facing the same issue... any solution? I've tried everything I can.

**Comment by ceroideas** [comment]
I'm facing the same issue... any solution? I've tried everything I could.

**Comment by wf9a5m75** [comment]
I said `Please share your project files on git repository.
I have no idea how you guys install this plugin.`

**Comment by wf9a5m75** [comment]
I always recommend for the first user of this plugin, please try with simple tutorial.
https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/blob/master/v2.6.0/hello-world/README.md

**Comment by iChristosK** [comment]
@wf9a5m75  I follow your tutorial but I cannot complete the installation of google maps no matter what I do or which version I use. I tried native core version 5.5.0 as you suggested but nothing. And yes I sure use the latest version of Xcode.  Below I attach my ionic info on my machine. 

Please clone and try to install google maps. 

Here is my repo: https://github.com/iChristosK/maps 

![Screenshot 2020-05-16 at 13 54 13](https://user-images.githubusercontent.com/16455384/82117993-cda36d80-977c-11ea-94a3-ab85301ec9db.png)

**Comment by ceroideas** [comment]
I have tried the following

I install version 2.7 (.0 or .1), if the ios platform is not added it installs normal in the plugins directory, but when I try to add the ios platform, it stays on installing.

If I install version 2.6.2 and add the ios platform, it installs without problems, if the platform is already added and I install version 2.6.2, it adds normal.

This on a MAC ...

I have tried to add the ios platform on a windows pc, and if I install version 2.6.2 it installs without problems, even adding the ios platform before or after installing the plugin.

If I try to install version 2.7 (.0 or .1) it throws me this message and it stays there indefinitely:

apple-xcode version check failed (C: \ Users \ MyUser \ projects \ wass \ platforms \ ios \ cordova \ apple_xcode_version), continuing anyways.
apple-ios version check failed (C: \ Users \ My User \ projects \ wass \ platforms \ ios \ cordova \ apple_ios_version), continuing anyways.

My repository: https://github.com/ceroideas/app-wass

**Comment by wf9a5m75** [comment]
Thank you guys. Could you tell me the version number of `git` command?

**Comment by wf9a5m75** [comment]
Please try `ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk` before `ionic cordova plugin add cordova-plugin-googlemaps`

**Comment by ceroideas** [comment]
It didn't work ... it stays in cordova plugin add https: // ... and it doesn't respond, I left it like this for 10 minutes

**Comment by wf9a5m75** [comment]
Ok, please try to upgrade the `git` command version

**Comment by ceroideas** [comment]
![image](https://user-images.githubusercontent.com/49728029/82130353-ab1f4d80-9798-11ea-938a-7ef78e8c993a.png)

:c

**Comment by wf9a5m75** [comment]
Umm. This is completely `cordova` problem itself.
Please report to `Apache Cordova` issue tracker.
https://issues.apache.org/jira/projects/CB/issues/CB-13200?filter=allopenissues

I don't have Windows PC, so I can't reproduce the problem.

-------------

Temporally solution:
Please try like this:

```
$> git clone git@github.com:mapsplugin/cordova-plugin-googlemaps-sdk.git
$> ionic cordova plugin add (path to)/cordova-plugin-googlemaps-sdk
$> ionic cordova plugin add cordova-plugin-googlemaps
```

**Comment by ceroideas** [comment]
I think this is not normal

![image](https://user-images.githubusercontent.com/49728029/82131796-1839df80-97a7-11ea-8e9a-0fdf170ac19e.png)

**Comment by ceroideas** [comment]
In the end it was installed following the steps that you tell me, the problem is the weight of the repository at the time of download, it gives the feeling that it stays on installing because cordova does not have a progress bar. Curiously, com.googlemaps.ios is installed but when installing cordova-plugin-googlemaps this plugin is removed. Anyway thank you very much

**Comment by iChristosK** [comment]
> Umm. This is completely `cordova` problem itself.
> Please report to `Apache Cordova` issue tracker.
> https://issues.apache.org/jira/projects/CB/issues/CB-13200?filter=allopenissues
> 
> I don't have Windows PC, so I can't reproduce the problem.
> 
> Temporally solution:
> Please try like this:
> 
> ```
> $> git clone git@github.com:mapsplugin/cordova-plugin-googlemaps-sdk.git
> $> ionic cordova plugin add (path to)/cordova-plugin-googlemaps-sdk
> $> ionic cordova plugin add cordova-plugin-googlemaps
> ```

Thank you very much. This worked!
