### ISSUE TITLE
Is there any information is collecting by GoogleMaps SDK?

### ISSUE THREAD

**Issue by hemangshah** [ionic-team/ionic-native-google-maps#314]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 3.8.0 "Google Maps SDK for iOS"
cordova-android-play-services-gradle-release 1.4.6 "cordova-android-play-services-gradle-release"
cordova-android-support-gradle-release 3.0.1 "cordova-android-support-gradle-release"
cordova-clipboard 1.3.0 "Clipboard"
cordova-custom-config 5.1.0 "cordova-custom-config"
cordova-opentok-android-permissions 1.0.0 "Cordova Opentok/WebRTC Android Permissions"
cordova-plugin-add-swift-support 2.0.2 "AddSwiftSupport"
cordova-plugin-android-permissions 1.0.2 "Permissions"
cordova-plugin-buildinfo 4.0.0 "BuildInfo"
cordova-plugin-compat 1.2.0 "Compat"
cordova-plugin-cordovaHelpers 4.1.0 "CordovaHelpers"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-inappbrowser 4.0.0-dev "InAppBrowser"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-iroot 0.8.1 "iRoot"
cordova-plugin-ms-adal 0.10.1 "ADAL for Cordova"
cordova-plugin-ms-speech-service 0.0.1 "MicrosoftSpeechService"
cordova-plugin-nativegeocoder 3.4.1 "NativeGeocoder"
cordova-plugin-network-information 2.0.2 "Network Information"
cordova-plugin-opentok 3.4.3 "OpenTokCordovaPlugin"
cordova-plugin-screen-orientation 3.0.2 "Screen Orientation"
cordova-plugin-secure-storage-echo 5.0.1 "SecureStorage"
cordova-plugin-speechrecognition 1.1.2 "Speech Recognition"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-statusbar 2.4.3 "StatusBar"
cordova-plugin-theme-detection 1.2.1 "ThemeDetection"
cordova-plugin-tts 0.2.3 "TTS"
cordova-plugin-whitelist 1.3.4 "Whitelist"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
es6-promise-plugin 4.2.2 "Promise"
ionic-plugin-deeplinks 1.0.20 "Ionic Deeplink Plugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "4.4.0"
"@ionic-native/google-maps": "^4.8.2"
```

**Current behavior:**
```
Security scrutiny team found this kind of logs 
```

_User's account information : account "com.microsoft.workaccount" sent over the network - Destination:-  Google Maps_ 

**Expected behavior:**
```
What information Google Maps SDK collects?
```

**Screen capture or video record:**
```
Not available.
```

**Related code, data or error log (please format your code or data):**
```
Not available.
```

**If answer to this question is Yes, is there any way to stop this collection**.

**Comment by wf9a5m75** [comment]
Please ask to Google. This plugin does not collect any information, but Google Maps SDK might collect some information.
If you don't like that, you can make contact with Google. There is paid plan of Google Maps SDKs (Please ask to Google, not me)

https://developers.google.com/maps/documentation/ios-sdk/intro

**Comment by hemangshah** [comment]
I didn't asked you buddy specifically! 
You just showed up from your team :) Thanks for your reply btw. 
Reply politely to your framework users/customers.
Hope you're having good days.
@wf9a5m75

**Comment by hemangshah** [comment]
I didn't knew that I can't ask it here. Thanks for your reply. Yeah I don't like anyone collects any information without my consent. Could you spend some time on mention this in your read me files as well so next time you won't get questions like this?
