### ISSUE TITLE
SUBSCRIPTIONS_ID is not defined.

### ISSUE THREAD

**Issue by bykeat** [ionic-team/ionic-native-google-maps#315]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [z] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [z] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```
G:\Project\ionic-prebooking> cordova plugin list
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.8.0-20200601-1013 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
    "@ionic-native/core": "^5.26.0",
    "@ionic-native/google-maps": "^5.5.0",

**Current behavior:**

Empty white map without Google logo. 
Stack error:
ERROR ReferenceError: SUBSCRIPTIONS_FIELD is not defined
    at Map.remove (Map.js:855)
    at index.js:1140
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41632)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at invokeTask (zone-evergreen.js:480)
    at ZoneTask.invoke (zone-evergreen.js:469)
    at timer (zone-evergreen.js:2552)
**Expected behavior:**

It should display Google Map like the demo? https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4/blob/master/src/app/home/home.page.ts
**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
Please share your project files on Github repository (not zip file or Google Drive etc)
I think you do some mistakes

**Comment by bykeat** [comment]
> Please share your project files on Github repository (not zip file or Google Drive etc)
> I think you do some mistakes

https://github.com/bykeat/ionic-angular-booking.git

Yes, I am new to Angular and Ionic. I might probably messed up with the package.json or something. Thank you very much for your help in advance.

**Comment by gaetan224** [comment]
i'm having the same error:

9110 ERROR ReferenceError: SUBSCRIPTIONS_FIELD is not defined
    at Map.remove (Map.js:855)
    at index.js:1125
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:34182)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)
    at invokeTask (zone-evergreen.js:465)
    at ZoneTask.invoke (zone-evergreen.js:454)
    at timer (zone-evergreen.js:2650)

**Comment by chris-cornwall** [comment]
Same issue here. It works fine in the browser but throws the above error when I try to run it on my Android device.

**Comment by chandraahmad** [comment]
> **I'm submitting a ...** (check one with "x")
> 
> * [ ]  question
> * [z] any problem or bug report
> * [ ]  feature request
> 
> **If you choose 'problem or bug report', please select OS:** (check one with "x")
> 
> * [ ]  **Android**
> * [ ]  **iOS**
> * [z] **Browser**
> 
> **cordova information:** (run `$> cordova plugin list`)
> 
> ```
> insert the output from the command here
> ```
> 
> G:\Project\ionic-prebooking> cordova plugin list
> cordova-plugin-device 2.0.2 "Device"
> cordova-plugin-googlemaps 2.8.0-20200601-1013 "cordova-plugin-googlemaps"
> cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
> cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
> cordova-plugin-splashscreen 5.0.2 "Splashscreen"
> cordova-plugin-statusbar 2.4.2 "StatusBar"
> cordova-plugin-whitelist 1.3.3 "Whitelist"
> 
> **If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
> "@ionic-native/core": "^5.26.0",
> "@ionic-native/google-maps": "^5.5.0",
> 
> **Current behavior:**
> 
> Empty white map without Google logo.
> Stack error:
> ERROR ReferenceError: SUBSCRIPTIONS_FIELD is not defined
> at Map.remove (Map.js:855)
> at index.js:1140
> at ZoneDelegate.invokeTask (zone-evergreen.js:399)
> at Object.onInvokeTask (core.js:41632)
> at ZoneDelegate.invokeTask (zone-evergreen.js:398)
> at Zone.runTask (zone-evergreen.js:167)
> at invokeTask (zone-evergreen.js:480)
> at ZoneTask.invoke (zone-evergreen.js:469)
> at timer (zone-evergreen.js:2552)
> **Expected behavior:**
> 
> It should display Google Map like the demo? https://github.com/mapsplugin/ionic-googlemaps-quickdemo-v4/blob/master/src/app/home/home.page.ts
> **Screen capture or video record:**
> 
> **Related code, data or error log (please format your code or data):**
> 
> ```
> The person who share your project files on Github (or other git repository) is in faster lane than other people.
> Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
> If you don't want to share your project files, please create a demo project, then share it.
> 
> Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.
> 
> Giving much information, you are waiting time is less.
> Thank you for your cooperation.
> ```

remove this.map.clear(); method, actually is not solution but this.map.clear(); method there is bug, and if you want to remove marker just remove a map and show map again if you want to show new marker

**Comment by wf9a5m75** [comment]
This problem has been fixed in another commit. Please reinstall the plugin from the multiple_maps branch

```
$ npm uninstall @ionic-native/google-maps
$ ionic cordova plugin rm cordova-plugin-googlemaps

$ npm install @ionic-native/google-maps@5.27.0-beta-20200630
$ ionic cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps
```

**Comment by Zer0ne83** [comment]
Great work, @wf9a5m75 - absolute legend!
