### ISSUE TITLE
Bug with SideMenu

### ISSUE THREAD

**Issue by Xulthes** [ionic-team/ionic-native-google-maps#32]
I have a problem with this plugin, normally it happens when I return to the view or I go back from the menu, the responsive map stop working as it should be. This problem also happens in your example, so I think that it isn't something that I did, you can check installing the demo in a clean project:
https://github.com/mapsplugin/ionic-googlemaps-quickdemo

**Comment by wf9a5m75** [comment]
```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by wf9a5m75** [comment]
![compress](https://user-images.githubusercontent.com/167831/40459395-f91d921c-5eb5-11e8-9d07-d325d5db2c63.gif)

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no response, I close this thread.
