### ISSUE TITLE
setMyLocationEnabled(true) doesn't display the blue dot on Android, only on iOS

### ISSUE THREAD

**Issue by danieltanasec** [ionic-team/ionic-native-google-maps#324]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-fetch 5.6.1 "CDVBackgroundFetch"
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-badge 0.8.8 "Badge"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-orientation 2.0.1 "Device Orientation"
cordova-plugin-dialogs 2.0.2 "Notification"
cordova-plugin-geolocation 4.0.2 "Geolocation"
cordova-plugin-globalization 1.11.0 "Globalization"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.1.3 "cordova-plugin-ionic-webview"
cordova-plugin-local-notification 0.9.0-beta.2 "LocalNotification"
cordova-plugin-nativegeocoder 3.2.2 "NativeGeocoder"
cordova-plugin-nativestorage 2.3.2 "NativeStorage"
cordova-plugin-pedometer 0.4.1 "Core Motion Pedometer"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-taptic-engine 2.1.0 "Taptic Engine"
cordova-plugin-vibration 3.1.1 "Vibration"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sms-plugin 1.0.0 "Cordova SMS Plugin"
cordova.plugins.diagnostic 5.0.2 "Diagnostic"
uk.co.workingedge.phonegap.plugin.launchnavigator 5.0.4 "Launch Navigator"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

    "@ionic-native/core": "^5.27.0",
    "@ionic-native/google-maps": "^5.5.0",

**Current behavior:**
setMyLocationEnabled(true) doesn't display the blue dot on Android, only on iOS. Also setting **myLocation** to **true** while generating the map behaves the same.

`let mapOptions: GoogleMapOptions = {
        camera: {
           target: myLocation.latLng,
           zoom: this.zoom,
           tilt: 30,
         },
         styles: 
            mapStyle,
         preferences: {
           zoom: {minZoom: 6, maxZoom: 20}
         },
         controls: {
           myLocation: true
         }
      };`

**Screen capture or video record:**
<img src="https://user-images.githubusercontent.com/32623221/87961104-ebaf8600-cabd-11ea-9ba7-ce41a1d1b1d0.jpg" width="300">

<img src="https://user-images.githubusercontent.com/32623221/87961106-ec481c80-cabd-11ea-88e1-7d084c7bcea4.jpg" width="300">

**Comment by wf9a5m75** [comment]
Please share your project files on GitHub

**Comment by danieltanasec** [comment]
I cannot share the project unfortunately. It is a private app.

**Comment by danieltanasec** [comment]
I can prepare a test demo to see if it behaves the same

**Comment by wf9a5m75** [comment]
I don't mind private or public repo.

**Comment by danieltanasec** [comment]
I have prepared a test demo at https://github.com/Tzuya14/test_ionic_gm_location_android. Still same issue..
The app requests location permission, the map is centered to my actual location, but no blue dot is displayed.

**Comment by danieltanasec** [comment]
I come back with an update. After I closed and opened the app multiple times I observed that once the blue dot appeared on the map, the next time I reopened the app it disappeared again.. Still this is strange.

**Comment by wf9a5m75** [comment]
I tested your code.
Your situation has been reproduced first couple of times when I tried with your API key.
(But your API key is restricted, that's why I could not see the map)

I changed to my API key, then solved the situation. I don't know why.
Even, after closing the app, launch it again, no problem at all.

<img src="https://user-images.githubusercontent.com/167831/87985445-78dbe600-ca90-11ea-929f-39e7abb81932.png" width="400">


Blue dot is displayed by Google Maps SDK for Android itself, not this plugin.
That's why I can not do anything

**Comment by danieltanasec** [comment]
I understand. So it may be an API issue. I will look into it. Thanks a lot for your help.

**Comment by danieltanasec** [comment]
I observed in the console that I get the error **E/PluginLocationService: ===> googleApiClient.isConnected() is not connected**
Could it be related in some way to this issue? I tried to renew the API with no restrictions, activated all MAPS related services, fixed all issues in Android manifest and still no luck..

**Comment by wf9a5m75** [comment]
Maybe your Google Play Services is old?

**Comment by danieltanasec** [comment]
I use a Huawei mobile for testing :). Could that be the issue?

**Comment by wf9a5m75** [comment]
Possible. Please try another Android phone which is not China maker brand.
