### ISSUE TITLE
Google maps shows blank on iOS?

### ISSUE THREAD

**Issue by jamesharvey2** [ionic-team/ionic-native-google-maps#33]
Hello guys,

Google maps native is working fine on production build of android.
However, on iOS, it's showing only beige color blank? 
It's not white blank. It shows markers correctly but the map isn't loading.

How can I fix this error? 

Thanks

**Comment by wf9a5m75** [comment]
Gray map means your api key doesn't allow to use ios map.

Make sure you enabled iOS Google map BEFORE generate api key.

**Comment by jamesharvey2** [comment]
Thanks, you're right.

I just enabled Google Maps for iOS and it gave me two API keys: server and browser.
Which one should I use on ionic iOS app?

**Comment by jamesharvey2** [comment]
![apipage](https://user-images.githubusercontent.com/34139438/40494241-624dd76a-5f42-11e8-9092-645d558d48ae.jpg)

**Comment by jamesharvey2** [comment]
It generated two APIs. I wonder what this means..

**Comment by jamesharvey2** [comment]
Cordova is web app so I guess it's relevant to use browser key API? 
https://stackoverflow.com/questions/17715572/google-api-keys-what-is-server-key-and-browser-key

**Comment by wf9a5m75** [comment]
No. This plugin DOES NOT use google maps JavaScript api v3. It's native google maps api.

**Comment by jamesharvey2** [comment]
I will test with both keys. Browser key has the same length as their previous API key. server key is a little big longer.  Thanks

**Comment by wf9a5m75** [comment]
You need to generate for application, not for browser or server.

**Comment by jamesharvey2** [comment]
Yes, I can generate a new API on top of automatically generated two apis. 
Is it possible to use the same API for both iOS and Android? because this new one is generated after iOS and android are enabled.

**Comment by wf9a5m75** [comment]
>Is it possible to use the same API for both iOS and Android?

yes.

**Comment by jamesharvey2** [comment]
Thanks, please update installation command for us so it will ask only one API key.

**Comment by Madhulika08** [comment]
Hi @jamesharvey2 ,

Did you find the solution for the maps? I am having the same trouble as you. My maps only show markers and beige background but the actual map doesn't load up.

**Comment by Madhulika08** [comment]
Hi,

There was an issue with API key in 'project'-info.plist file under Resouces folder.
Open the xcworspace file in xcode. Project -> Resources-> 'project'-info.plist and check if the API key is correct.

Also check under Cordova->Info.plist.

Delete the app from the device. Clean and build it again and then run on your device.
Also, check the network connectivity is proper.

**Comment by faizy-ahmed** [comment]
> Gray map means your api key doesn't allow to use ios map.
> 
> Make sure you enabled iOS Google map BEFORE generate api key.

It helped me right away, thanks alot.

**Comment by Fox5150** [comment]
It seems that just enabling the Google Maps API is enough.
It worked with my old Key, there is no need to create a new key before enabling Google Maps at : [https://console.cloud.google.com/google/maps-apis/](https://console.cloud.google.com/google/maps-apis/)
