### ISSUE TITLE
Maps are not visible in android device - FIXED

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [ionic-team/ionic-native-google-maps#332]
First of all i would like to thank all the contributors, maintainers of this repo. This package is really helpful.
 
**I'm submitting a ...**  (check one with "x")
- [x] any problem or bug report
- [ ] question
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-androidx-build 1.0.4 "cordova-androidx-build"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.8.0-20200709-2008 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

<img width="415" alt="Screenshot 2020-08-23 at 10 45 59 PM" src="https://user-images.githubusercontent.com/9896335/90984418-6e7ea180-e592-11ea-9588-a1daf382373a.png">

<img width="851" alt="Screenshot 2020-08-23 at 10 45 12 PM" src="https://user-images.githubusercontent.com/9896335/90984408-5149d300-e592-11ea-90f1-f3e093730279.png">

**Current behavior:**
The maps are showing properly in web browser using `ionic cordova run browser -l`. But when i run in mobile with debug mode or apk directly installed, it's not showing the maps properly. Except the map i am able to see everything like google credits zoom in, zoom out, my location button etc. It's also giving my current location as well and when i tap on the screen all the related events are also triggered. But the issue is map is not displayed at all.

When i inspect the debug apk using chrome inspect tools, i found that the content on the DOM is not rendering.

<img width="566" alt="Screenshot 2020-08-23 at 10 58 31 PM" src="https://user-images.githubusercontent.com/9896335/90984701-4db74b80-e594-11ea-88cc-d45991c20531.png">

**Expected behavior:**
Maps should be displayed properly in android as well.

**Screen capture or video record:**
<img src="https://user-images.githubusercontent.com/9896335/90984499-f9f83280-e592-11ea-81b1-4d94f77b8fdb.png" width="400"/>

**Related code, data or error log (please format your code or data):**

I am waiting till the device is ready
```
async ngOnInit() {
  await this.platform.ready();
  this.renderMap();
}
```

Here is my css
````
#map_canvas {
  height: 350px;
}
````

Here is the complete JS code.

<img width="656" alt="Screenshot 2020-08-23 at 11 09 57 PM" src="https://user-images.githubusercontent.com/9896335/90984954-23668d80-e596-11ea-8ef4-1db7dc10c254.png">

**Comment by wf9a5m75** [comment]
Gray map means always your API key problem.

In Android, this plugin does **not*" use Google Maps JavaScript v3. We use Google Maps SDK for Android

**Comment by rajeshwarpatlolla** [comment]
Thanks for the response @wf9a5m75. It's working fine after adding android sdk api to the project in google maps dashboard.
