### ISSUE TITLE
Satellite View Not Show labels

### ISSUE THREAD

**Issue by thejairana** [ionic-team/ionic-native-google-maps#333]
Normal View
![normal-view](https://user-images.githubusercontent.com/50228658/91532253-ab98ba00-e92b-11ea-8251-e3fd5afbddfa.jpeg)
Hybrid View
![hybrid-view](https://user-images.githubusercontent.com/50228658/91532267-ae93aa80-e92b-11ea-8acd-4339ba02dc9d.jpeg)
Satellite View
![satellite-view](https://user-images.githubusercontent.com/50228658/91532264-adfb1400-e92b-11ea-8dcf-a32e886d2a3f.jpeg)

Normal & Hybrid View Show locations name But satellite view not.

**Comment by wf9a5m75** [comment]
That's correct

**Comment by wf9a5m75** [comment]
Safelite displays only images
