### ISSUE TITLE
Google Maps Places API

### ISSUE THREAD

**Issue by WaseemRakab** [ionic-team/ionic-native-google-maps#334]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x ] feature request
**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

hello,
is there any Plans to support Google Maps Places API?
it's the only missing feature i need to use this plugin.
thanks.

**Comment by wf9a5m75** [comment]
If somebody pay enough amount for my working time, I will create it.
