### ISSUE TITLE
Can't install cordova-plugin-googlemaps-sdk with npm or yarn

### ISSUE THREAD

**Issue by vpankov** [ionic-team/ionic-native-google-maps#335]
Tried to run
`ionic cordova plugin add cordova-plugin-googlemaps`
it was stuck on message 
`Installing "cordova-plugin-googlemaps" for ios`

--verbose flag showed that it trying to run
`npm install https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk --production --save`

then I tried to run 
`npm install https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk`
but it stuck with message rollbackFailedOptional

then I tried to run it in empty folder with inited yarn
`yarn add https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk`
it stuck on [1/4] Resolving packages...

npm 6.14.8
git 2.9.2
yarn 1.17.3
MacOS
Tried different internet connections and devices 

**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**Comment by wf9a5m75** [comment]
I really appreciate if you search the past issues before asking.
https://github.com/ionic-team/ionic-native-google-maps/issues/320

**Comment by vpankov** [comment]
Thank you. Yarn finished in 30 minutes, npm still trying to install it, hope it will done. 
Anyway your answer will solve it fo me.
