### ISSUE TITLE
Satellite image resolution diff depending on platform which android device or browser

### ISSUE THREAD

**Issue by behindraven** [ionic-team/ionic-native-google-maps#339]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.7.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.2.0 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 4.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**Current behavior:**
Satellite Image resolution on (android) device is lower then browser.

**Expected behavior:**
Same image quality as showing browser!!

**Screen capture or video record:**
![googlemaps](https://user-images.githubusercontent.com/61071857/95840099-b9d95300-0d7e-11eb-9d1e-d1f054b9e24b.png)

**Comment by wf9a5m75** [comment]
Please ask to Google
