### ISSUE TITLE
Feature: markerCluster visibility

### ISSUE THREAD

**Issue by VersusF** [ionic-team/ionic-native-google-maps#344]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

---

Hello, thank you for your work. I suggest only a little feature that i need for a project:

I need to hide the marker cluster when the zoom level is lower than a certain amount.

Currently i use the `setVisibility` method on the markers, but the cluster is still visible and, when clicking on it, it makes the zoom but without showing anything, as the markers are hidden. I would like to have the possibility of setting the visibility of the markerCluster object too. That would be great!

Thanks again and good work!

**Comment by Apro123** [comment]
This was proposed in this issue: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2794

**Comment by VersusF** [comment]
Thanks, closing as duplicate
