### ISSUE TITLE
Exclude places from map

### ISSUE THREAD

**Issue by almaz1213** [ionic-team/ionic-native-google-maps#346]
- [x ] question

**Current behavior:**
I init map with camera option only. But it shows place markers.

**Expected behavior:**
I would like see my markers only. 

How to exclude plase markers from the map?
I couldn't find the option in docs.

**Comment by almaz1213** [comment]
option

```
styles: [
        {
          "featureType": "poi",
          "elementType": "all",
          "stylers": [
            { "visibility": "off" }
          ]
        }
      ]
```

doesn't remove them

**Comment by wf9a5m75** [comment]
Please try here

https://mapstyle.withgoogle.com/

This plugin just passes the parameters to the maps sdk

**Comment by almaz1213** [comment]
but where can i include mapId then?

**Comment by wf9a5m75** [comment]
choose "old style wizard"

**Comment by almaz1213** [comment]
do u mean retro style?

already. but enyway i need put the mapId according gmap js docs. in ur docs i cant see where can i set the mapId

**Comment by wf9a5m75** [comment]
This plugin doesn't support the cloud maps, and this plugin doesn't use Google Maps JavaScript v3 API on Android and iOS.

You need to generate JSON, and pass it to the maps plugin

**Comment by almaz1213** [comment]
mate a option 'styles' doesnt affect as well.
```
this.map = GoogleMaps.create('map_canvas', {

      camera: {
        target: {
          lat: this.lat,
          lng: this.lon
        },
        zoom: 13,
        tilt: 30
      },
      controls: {
        compass: false,
        myLocationButton: true,
        myLocation: true,   // (blue dot)
        indoorPicker: true,
        zoom: false,          // android only
        mapToolbar: false     // android only
      },

      styles: [
        {
          "featureType": "poi",
          "elementType": "all",
          "stylers": [
            { "visibility": "off" }
          ]
        }
      ],...
```

**Comment by wf9a5m75** [comment]
Please try many options. As I said, this plugin just passes the parameters to the Google Maps SDK. You need to figure out which options are good.

**Comment by almaz1213** [comment]
))) do u mean do that brutely?

**Comment by wf9a5m75** [comment]
If you use Google Maps SDK directly, you will face this problem. Because this is the problem of inside the Google Maps SDK, not this plugin.

And this is not a help forum. The issue tracker for the maps plugin.

You can specify different rules. Try and try please

**Comment by almaz1213** [comment]
got it. thanx mate
