### ISSUE TITLE
Error while trying to load map in iOS simulator

### ISSUE THREAD

**Issue by jasvindersingh-evon** [ionic-team/ionic-native-google-maps#41]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
"@ionic-native/core": "^4.7.0",
"@ionic-native/google-maps": "^4.8.2",
```
**Current behavior:**
After installing the plugin, I have written the code to display maps in HomePage. And then I ran the command ionic cordova build ios. After that I tried running it on iOS Simulator. Everytime I get the error 

WARN: 'Native: tried accessing the GoogleMaps plugin but it's not installed.

**Expected behavior:**
It should run seamlessly and Google Maps should be displayed.

**Screen capture or video record:**

iOS sample video - 
[googledemo.zip](https://github.com/ionic-team/ionic-native-google-maps/files/2116774/googledemo.zip)

**Related code, data or error log (please format your code or data):**
[Sample github Code](https://github.com/jasvindersingh-evon/IonicGoogleMapsDemo)

**Comment by wf9a5m75** [comment]
As the error message says, you didn't install the cordova-plugin-googlemaps, or you don't wait platformready event.

Please read well this slides before using this plugin.
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000

**Comment by jasvindersingh-evon** [comment]
Yes you are right the plugin was not getting installed in iOS. I tried the same on Android. And it worked fine on Android.

Why it was not getting installed on iOS?

- I had Xcode 8.2 so when i was adding iOS platform through command ```ionic cordova platform add ios```, the command skipped the installation of google maps as google maps plugin requires Xcode version 9.0 and above. 

- I think the dependency of Xcode 9.0 should be mentioned in the readme file.

**Comment by wf9a5m75** [comment]
I specified Xcode version in the plugin.xml file.
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/f868957947210957086f84bca0b6144f49a51e7c/plugin.xml#L122

If your environment use Xcode 8, cordova outputs error strings, but you just ignored.

**Comment by jasvindersingh-evon** [comment]
Right, you mentioned it in plugin.xml but who checks the plugin so deeply. Firstly every user will install it through command.

Better to mention it in Readme file so that user remains alerted before installing the plugin. Also, it got ignored because it installs quickly plugins one by one, and somehow it got missed by me. I think it should be mentioned in Readme file.
