### ISSUE TITLE
draggable:true is not working in Marker

### ISSUE THREAD

**Issue by aniruddhaacharya** [ionic-team/ionic-native-google-maps#43]
The draggable :true is not working please help . 
Thanks in advance
**I'm submitting a ...**  (check one with "x")
- [ ] question
-[x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin 
local packages:

    @ionic/app-scripts : 3.1.10
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.9.2

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
{
  "name": "googlemaps",
  "version": "0.0.1",
  "author": "Ionic Framework",
  "homepage": "http://ionicframework.com/",
  "private": true,
  "scripts": {
    "clean": "ionic-app-scripts clean",
    "build": "ionic-app-scripts build",
    "lint": "ionic-app-scripts lint",
    "ionic:build": "ionic-app-scripts build",
    "ionic:serve": "ionic-app-scripts serve"
  },
  "dependencies": {
    "@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/core": "^4.9.0",
    "@ionic-native/google-maps": "^4.8.2",
    "@ionic-native/splash-screen": "4.8.0",
    "@ionic-native/status-bar": "4.8.0",
    "@ionic/storage": "2.1.3",
    "cordova-android": "6.3.0",
    "cordova-plugin-device": "^2.0.2",
    "cordova-plugin-googlemaps": "^2.3.6",
    "cordova-plugin-ionic-keyboard": "^2.0.5",
    "cordova-plugin-ionic-webview": "^1.1.19",
    "cordova-plugin-splashscreen": "^5.0.2",
    "cordova-plugin-whitelist": "^1.3.3",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "minimist": "^1.2.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "xml2js": "^0.4.19",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "3.1.10",
    "typescript": "~2.6.2"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-googlemaps": {
        "API_KEY_FOR_ANDROID": "hidden"
      },
      "cordova-plugin-whitelist": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-ionic-webview": {},
      "cordova-plugin-ionic-keyboard": {}
    },
    "platforms": [
      "android"
    ]
  }
}
**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```
![capture](https://user-images.githubusercontent.com/20493584/42123939-038484f6-7c78-11e8-87c8-6fa5b478ba80.PNG)

**Comment by wf9a5m75** [comment]
Please share the project files that reproduce your issue 100% onto GitHub.

**Comment by aniruddhaacharya** [comment]
Here is folder i have uploaded. Which has all code related to the isseue .
[home.zip](https://github.com/ionic-team/ionic-native-google-maps/files/2151863/home.zip)

**Comment by wf9a5m75** [comment]
I don't accept any zip files. Please share the project files on GitHub.

**Comment by aniruddhaacharya** [comment]
Brother i dont know how to add project on git so please if there is any other way to go on tell me.
Thanks

**Comment by wf9a5m75** [comment]
I'm not your brother.

If you don't know how to create a git repo, please study from the following link
https://guides.github.com/activities/hello-world/

**Comment by aniruddhaacharya** [comment]
Here is the link of files which i have uploaded
https://github.com/aniruddhaacharya/googlemapsdemo

**Comment by wf9a5m75** [comment]
Thanks, but you don't include any other necessary files, such as package.json and config.xml files.

I said, please share your project files.
It means you need to include all files.

Because I will do 
```
$> git clone (your repo)
$> npm i
$> cordova prepare
$> ionic cordova run android
```

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.
