### ISSUE TITLE
 Can MarkerIcon support  using the SVG Path notation

### ISSUE THREAD

**Issue by xinfengmich** [ionic-team/ionic-native-google-maps#47]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [ ] any problem or bug report
- [x] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x ] **Android**
- [x ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.6.0 "Google Maps SDK for iOS"
cordova-background-geolocation-lt 2.11.0 "BackgroundGeolocation"
cordova-fabric-plugin 1.1.14-dev "cordova-fabric-plugin"
cordova-open-native-settings 1.5.1 "Native settings"
cordova-plugin-advanced-http 1.11.1 "Advanced HTTP plugin"
cordova-plugin-app-preferences 0.99.3 "AppPreferences"
cordova-plugin-app-version 0.1.9 "AppVersion"
cordova-plugin-background-fetch 5.3.0 "CDVBackgroundFetch"
cordova-plugin-badge 0.8.7 "Badge"
cordova-plugin-calendar 5.1.0 "Calendar"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-device-name 1.3.2 "Device-Name"
cordova-plugin-file 6.0.1 "File"
cordova-plugin-google-analytics 1.8.3 "Google Universal Analytics Plugin"
cordova-plugin-googlemaps 2.2.8 "cordova-plugin-googlemaps"
cordova-plugin-googleplus 5.3.0 "Google SignIn"
cordova-plugin-inappbrowser 3.0.0 "InAppBrowser"
cordova-plugin-ionic 4.1.6 "IonicCordova"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-nativestorage 2.3.1 "NativeStorage"
cordova-plugin-network-information 2.0.1 "Network Information"
cordova-plugin-screen-orientation 3.0.1 "Screen Orientation"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-plugin-youtube-video-player 1.0.6 "CordovaYoutubeVideoPlayer"
es6-promise-plugin 4.2.2 "Promise"
phonegap-plugin-push 2.1.3 "PushPlugin"

```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

"@ionic-native/core": "4.7.0",
"@ionic-native/google-maps": "4.7.0",

**Current behavior:**

       let stopIcon = { path: "M-20,0a20,20 0 1,0 40,0a20,20 0 1,0 -40,0",
              fillOpacity: 1,
              fillColor: "#FFFFFF",
              strokeOpacity: 1.0,
              strokeColor: routeColor,
              strokeWeight: 3,
              scale: 8 };
      
       let markerOptions: MarkerOptions = {
          icon: stopIcon,
          title: stop.name,
          position: new LatLng(stop.latitude, stop.longitude)
        };

        this.map.addMarker(markerOptions)
          .then((marker: Marker) => {
            marker.on(GoogleMapsEvent.INFO_CLICK)
              .subscribe(() => {
                this.showStopDetail(stop);
              });
          });

The stopIcon is ignored and still displays the default marker icon.  I went back to check the API document at https://github.com/ionic-team/ionic-native-google-maps/tree/master/documents/markericon
it seems not supporting  SVG icon.  Can you support SVG icon ? 

Thanks. 

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
No plan to support SVG.

**Comment by LiamKarlMitchell** [comment]
So the workarounds

Draw SVG image to canvas, get image data base64 from canvas and use that.
https://stackoverflow.com/questions/3768565/drawing-an-svg-file-on-a-html5-canvas
https://www.google.com/search?q=canvas+base64
https://jsfiddle.net/Wijmo5/h2L3gw88/

Or have a service that rasterizes the SVG to a PNG, e.g. you might send the pixel dimensions you want and the svg url and it would do its thing. Heh.

**Comment by wf9a5m75** [comment]
Pull request is welcome.
