### ISSUE TITLE
MarkerCluster does not work with error "evaluating 'Object.keys(self._markerMap)'"

### ISSUE THREAD

**Issue by centvingt** [ionic-team/ionic-native-google-maps#48]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-googlemaps 2.3.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-webview 1.2.1 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 4.1.0 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
```

**Current behavior:**

I've installed the demo of ionic googlemaps (https://github.com/mapsplugin/ionic-googlemaps-quickdemo). I ran `ionic cordova run ios -c`. All pages work well, but not the MarkerCluster page: the map does not show up anymore, and I cannot see any pin or cluster. Here is the console print the error log above. I really need to be able to show the map, the pins and the clusters for my application which is based on geolocation: could you please help me?

**Related code, data or error log (please format your code or data):**
```
Unhandled Promise rejection: undefined is not an object (evaluating 'Object.keys(self._markerMap)') ; Zone: <root> ; Task: Promise.then ; Value: [object Object] keys@[native code]
remove@http://10.0.106.10:8100/plugins/cordova-plugin-googlemaps/www/MarkerCluster.js:307:21
clearObj@http://10.0.106.10:8100/plugins/cordova-plugin-googlemaps/www/Map.js:688:26
remove@http://10.0.106.10:8100/plugins/cordova-plugin-googlemaps/www/Map.js:697:11
http://10.0.106.10:8100/plugins/cordova-plugin-googlemaps/www/CordovaGoogleMaps.js:414:34 forEach@[native code] 
removeDomTree@http://10.0.106.10:8100/plugins/cordova-plugin-googlemaps/www/CordovaGoogleMaps.js:401:19 
http://10.0.106.10:8100/plugins/cordova-plugin-googlemaps/www/CordovaGoogleMaps.js:78:38 
run@http://10.0.106.10:8100/build/polyfills.js:3:9529 
http://10.0.106.10:8100/build/polyfills.js:3:19625 
runTask@http://10.0.106.10:8100/build/polyfills.js:3:10224 o@http://10.0.106.10:8100/build/polyfills.js:3:7281 promiseReactionJob@[native code]
```

**Comment by wf9a5m75** [comment]
The error occurres when you manipulate the marker clustwr during map zooming. You can not do it.

**Comment by centvingt** [comment]
Hi, thanks very much for your prompt answer. We deeply need your help in order to fix this issue.

Starting from the ionic-native-google-maps demonstration, I have removed the zooming function during the « creation » of the map, in the `home.ts` file: 

![capture d ecran 2018-07-12 a 18 23 24](https://user-images.githubusercontent.com/10169975/42658041-6dc18106-8624-11e8-9a20-1e6098630c8f.png)

Then, I have deleted the zooming parameter, during the creation of the map, in the `marker-cluster.ts` file:

![capture d ecran 2018-07-12 a 18 23 36](https://user-images.githubusercontent.com/10169975/42658064-7de970ca-8624-11e8-9625-22b2dc4774bb.png)

The map and the cluster show up from time to time in the cluster page, but things do not remain stable and it eventually crashes, as shown in the .gif below.

![180712_cluster](https://user-images.githubusercontent.com/10169975/42658576-01e5977c-8626-11e8-91bf-fd5c916693ac.gif)

As you can see in this .gif, I neither manipulate the cluster, nor zoom. I only print the page and then it ends up with an error.

**Comment by centvingt** [comment]
Hi, indeed I have installed the application on an iPhone 5 with iOS 10.3.3, and the cluster makes the app crash too, on the iPhone.
I'm building the application with a MacBook Pro which is equipped with macOS 10.13.5.
The Node version I use is v10.4.1 and I also use NPM v6.1.0.

**Comment by wf9a5m75** [comment]
Ok, I fixed the problem. Please reinstall the `cordova-plugin-googlemaps` from the `multiple_maps` branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by wf9a5m75** [comment]
Oh, wait.. hold on.

**Comment by wf9a5m75** [comment]
Ok, I fixed the problem. Please reinstall the `cordova-plugin-googlemaps` from the `multiple_maps` branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by centvingt** [comment]
Hi, the bug seems to be fixed. Thanks very much for your quick reaction. I have sent you $100 by PayPal so that you can keep on updating this cool plugin. As things are ok now, I close the issue.

**Comment by wf9a5m75** [comment]
Thank you for your donation!
