### ISSUE TITLE
new BaseArrayClass() return null

### ISSUE THREAD

**Issue by brunnovianna** [ionic-team/ionic-native-google-maps#49]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [ ] **iOS**

**cordova information:**  (run `$> cordova plugin list`) 
```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-firebase 1.0.5 "Google Firebase Plugin"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.7 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```
**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
```
@ionic-native/core: "4.9.2"
@ionic-native/google-maps: "4.8.2"
```

**Current behavior:**

I'm trying to create multiple points by doing:
```
let points = [
   {
      lat: -23 -23.5352,
      lng: -46.6353
   }
];
let GMPoints: BaseArrayClass<ILatLng> = new BaseArrayClass(points);
```
But Ionic give me the error:
```
Cannot read property 'BaseArrayClass' of null.
```
Looking for the error, I discovered that at some point the plugin tries to GoogleMap.getPlugin(), witch is returning null.

Diggin deeper, I found (inside @ionic-native/core/util.js)
```
export var get = function (element, path) {
    var paths = path.split('.');
    var obj = element;
    for (var i = 0; i < paths.length; i++) {
        if (!obj) {
            return null;
        }
        obj = obj[paths[i]];
    }
    return obj;
};
```
The path is "plugin.google.maps"
The element is Window

But at first step (i == 0), Window["plugin"] is undefined.

**Expected behavior:**

To create the points to use as markers in GoogleMap instance.

**Related code, data or error log (please format your code or data):**
```
TypeError: Cannot read property 'BaseArrayClass' of null
    at new BaseArrayClass (http://localhost:8100/build/vendor.js:134716:58)
    at HomePage.webpackJsonp.268.HomePage.populateMap (http://localhost:8100/build/main.js:119:24)
    at SafeSubscriber._next (http://localhost:8100/build/main.js:107:19)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/vendor.js:20762:16)
    at SafeSubscriber.next (http://localhost:8100/build/vendor.js:20700:22)
    at Subscriber._next (http://localhost:8100/build/vendor.js:20644:26)
    at Subscriber.next (http://localhost:8100/build/vendor.js:20621:18)
    at MapSubscriber._next (http://localhost:8100/build/vendor.js:25267:26)
    at MapSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:20621:18)
    at http://localhost:8100/build/vendor.js:138277:112
```

**Comment by wf9a5m75** [comment]
Please share your project files on github

**Comment by brunnovianna** [comment]
See if it helps

https://github.com/brunnovianna/tarolando

**Comment by wf9a5m75** [comment]
Thanks, but where is the code in your repo?

**Comment by brunnovianna** [comment]
https://github.com/brunnovianna/tarolando/blob/master/src/pages/home/home.ts

**Comment by wf9a5m75** [comment]
```
let GMPoints: BaseArrayClass<ILatLng> = new BaseArrayClass<ILatLng>();

```

**Comment by brunnovianna** [comment]
I have tried that. I'll try again to get the error and will post here but I suspect that is the same error.

**Comment by brunnovianna** [comment]
I'll try to setup the project right from the begining, in a new folder and see what happens. I'm affraid that there's plenty of plugins outdated.

Thanks for your patience.

**Comment by wf9a5m75** [comment]
ping

**Comment by manoj529** [comment]
I'm Facing the same issue as mentioned and im using the below versions of code 👍 
"@angular/animations": "5.2.11",
    "@angular/common": "5.2.11",
    "@angular/compiler": "5.2.11",
    "@angular/compiler-cli": "5.2.11",
    "@angular/core": "5.2.11",
    "@angular/forms": "5.2.11",
    "@angular/http": "5.2.11",
    "@angular/platform-browser": "5.2.11",
    "@angular/platform-browser-dynamic": "5.2.11",
    "@ionic-native/ble": "^4.20.0",
    "@ionic-native/core": "4.19.0",
    "@ionic-native/geolocation": "^4.19.0",
    "@ionic-native/google-maps": "^4.15.0",
    "@ionic-native/ibeacon": "^4.19.0",
    "@ionic-native/splash-screen": "~4.18.0",
    "@ionic-native/status-bar": "^4.18.0",
    "@ionic/storage": "2.2.0",
    "ionic-angular": "3.9.2",
    "ionicons": "3.0.0",
    "minimist": "^1.2.0",
    "rxjs": "5.5.11",
    "sw-toolbox": "3.6.0",
    "xml2js": "^0.4.19",
    "zone.js": "0.8.26"

I guess after installing ble plugin it started giving me this error.
