### ISSUE TITLE
'Native: tried accessing the GoogleMaps plugin but it's not installed.

### ISSUE THREAD

**Issue by MasaharuKomuro** [ionic-team/ionic-native-google-maps#51]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
com.googlemaps.ios 2.7.0 "Google Maps SDK for iOS"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-geolocation 4.0.1 "Geolocation"
cordova-plugin-googlemaps 2.3.8 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.0.5 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 1.1.19 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-whitelist 1.3.3 "Whitelist"
cordova-sqlite-storage 2.3.3 "Cordova sqlite storage plugin"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.10.0"
"@ionic-native/google-maps": "^4.9.1"
```

**Current behavior:**
run command ```ionic run browser```.
So I got console error ```'Native: tried accessing the GoogleMaps plugin but it's not installed.``` and no map shown.

**Info**

My source code repositry is (https://github.com/MasaharuKomuro/virtical) and branch is **google-map-test**.
And error page is at ```http://localhost:8000/index.html#/main/spots/spots``` .

I checked @ionic-native/core/plugin.js Line:10 Fn:checkAvailability.  
In this function, Fn getPlugin is used. In Fn getPlugin, it would get plugin from Window object, but Window object dose not have plugin ```plugin.google.maps```.  (navigator.geolocation is exsists)

**Comment by wf9a5m75** [comment]
browser platform is not supported.
