### ISSUE TITLE
Multiple maps between different pages

### ISSUE THREAD

**Issue by Hanzofm** [ionic-team/ionic-native-google-maps#52]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report

What would be the correct way to integrate this plugin if have a main map screen, then when I click over a marker the app pushes to the page detail? This detail has data and a mini map.(other ubication)

-I have to create two different maps(different divs)?

Is possible to reuse the same map over two different pages(different ubications)

Thanks

**Comment by chadevans** [comment]
Maybe consider keeping the native plugin map where it is by popping up the detail page in a modal window, and in that modal use a javascript map.

**Comment by wf9a5m75** [comment]
@Hanzofm Yes, possible, this is good example.
https://github.com/battika/ionic-gmaps-test

![second_map compress](https://user-images.githubusercontent.com/167831/43217570-d8d3aa9c-8ff6-11e8-8aed-aa63b12b447b.gif)

**Comment by Hanzofm** [comment]
According to the repo the way is to create one map on each page that i need it, no?

**Comment by Hanzofm** [comment]
Thanks
