### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by GabrieleCicconetti** [ionic-team/ionic-native-google-maps#54]
Hi, i'm working with this library and i think there is an error in the MapType section.
The type road map is not present in the plugin, i found MAP_TYPE_NORMAL or MAP_TYPE_NONE instead. Hope this can help someone.

**Comment by wf9a5m75** [comment]
Thank you for reporting. I found wrong value, and fixed it. Please use `MAP_TYPE_NORMAL` 
https://github.com/ionic-team/ionic-native-google-maps/commit/1fdf808be019b48d182774ca3e2adff4bfe7a6c8
