### ISSUE TITLE
the map lose focus in case of Modal or Dialog on top of it.

### ISSUE THREAD

**Issue by kaessajidi** [ionic-team/ionic-native-google-maps#59]
I'm developping an app using ionic 3 and I have an issue with this plugin when I display a modal or a dialog on to of the map it lose the focus after it's closed.

an example of dialog is by calling the method bellow:

presentNotifications(myEvent) {
    console.log(myEvent);
    let popover = this.popoverCtrl.create(NotificationsPage);
    popover.present({
      ev: myEvent
    });
  }

There is no way to regain the focus of the map until you clici on a button or change the view.

Losing the map focus means that you can't click or zoom or move the map.

Any idea why this behavior that I don't have using the JS version of the google map ?

Regards

**Comment by wf9a5m75** [comment]
https://docs.google.com/presentation/d/e/2PACX-1vScoho1ensbR4qCI9AIuQN55BZVvK73pAjI7sumDvW3CrxxHnrmpXWUjx2-8CpFibqU1EjLKCRhuthJ/pub?start=false&loop=false&delayms=3000&slide=id.g3e207b82bf_886_16

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no update for a while, I close this thread.
