### ISSUE TITLE
myLocationButton

### ISSUE THREAD

**Issue by MikeWoots** [ionic-team/ionic-native-google-maps#6]
Hi 

Can you confirm that it is possible to set myLocationButton and myLocation separately? 

See [Issue](https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/1948) and [Release notes](https://github.com/mapsplugin/cordova-plugin-googlemaps-doc/tree/master/v2.0.0/ReleaseNotes/v2.2.0)

I have tried to implement this but setting myLocationButton to false in map controls does not remove it.

Thanks

**Comment by battika** [comment]
Which version of ionic-native/google-maps are you using?

**Comment by MikeWoots** [comment]
Hi

@ionic-native/google-maps: 4.6.3
cordova-plugin-googlemaps: 2.2.9

**Comment by battika** [comment]
It's strange. I'm still using ionic-native/google-maps version 4.6.0 and cordova-plugin-googlemaps 2.2.8 and initialize my map like this:
```
        this.maps[mapId].map = GoogleMaps.create(<mapElement>,
         {
          controls : {
            compass : false,
            myLocationButton : false,
            myLocation: true,
            indoorPicker : false,
            zoom : false,
            mapToolbar : false
          },
...
```
...and I can see the blue dot in the map but the my location button is removed. Are you trying to remove the button after the map has been initialized using the setMyLocationEnabled() and setMyLocationEnabled() functions calls?

**Comment by MikeWoots** [comment]
Amazing, thanks for the help :)

It seems to be working now. I had set my controls in this.maps.setOptions() but changed it to your example and now the button is removed.

**Comment by battika** [comment]
No worries, glad it helped. 

You might want to check my Ionic Google Maps example. I will update it soon according to the latest changes.

https://github.com/battika/ionic-gmaps-test

**Comment by wf9a5m75** [comment]
Thank you for helping other people, @battika.

**Comment by battika** [comment]
My pleasure hope I can spare some time for you :)

**Comment by kapilSoni101** [comment]
@wf9a5m75: Sir but in my case location myLocationButton is not show in the map i am using :
    <plugin name="cordova-plugin-googlemaps" spec="^2.4.4">

**Comment by ZubairHasan96** [comment]
@battika its not working for me. myLocationButton is not showing up my code is as follows:
```
controls : {
        compass : false,
        myLocationButton : true,
        myLocation: true,
        indoorPicker : false,
        zoom : false,
        mapToolbar : false
      }
```

Only zoom property seems to work

**Comment by ansonfoong** [comment]
> @battika its not working for me. myLocationButton is not showing up my code is as follows:
> 
> ```
> controls : {
>         compass : false,
>         myLocationButton : true,
>         myLocation: true,
>         indoorPicker : false,
>         zoom : false,
>         mapToolbar : false
>       }
> ```
> 
> Only zoom property seems to work

I'm having this issue too. When I set zoom to false it removes the +/- buttons, but the other options, such as the compass does not work.
