### ISSUE TITLE
[Question] Can I remove the red background when I zoom in a cluster or make it transparent?

### ISSUE THREAD

**Issue by renatoselenica** [ionic-team/ionic-native-google-maps#63]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [ ] **iOS**
- [ ] **Browser**

Just wanted to ask if there is a way to remove the red background when I zoom in a cluster or make it transparent?

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**

**Expected behavior:**

**Screen capture or video record:**

**Related code, data or error log (please format your code or data):**

```
The person who share your project files on Github (or other git repository) is in faster lane than other people.
Please share your project files on Github or others(Bitbucket, Gitlabs...etc).
If you don't want to share your project files, please create a demo project, then share it.

Screen captures, and/or native logs(such as Logcat, xcode logs) are appreciate.

Giving much information, you are waiting time is less.
Thank you for your cooperation.
```

**Comment by wf9a5m75** [comment]
`boundsDraw` property
https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/markerclusteroptions/README.md

**Comment by renatoselenica** [comment]
Awesome, thanks. I guess this work with the new `addMarkerClusterSync()` as well.

Also since I am here a very quick question without creating a new issue. If I am updating a single markers location and I want to delete the previous location based on the title of the marker, for example. Is there a feature for that or I have to do it myself?

**Comment by wf9a5m75** [comment]
The maps plugin does not have such a feature. You need to manage markers by your own role.

**Comment by renatoselenica** [comment]
Ok. thanks you very much :)
