### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by keisserdur** [ionic-team/ionic-native-google-maps#64]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **iOS**
- [ ] **Android**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-crosswalk-webview 2.4.0 "Crosswalk WebView Engine"
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.1 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.0 "cordova-plugin-ionic-webview"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

**Current behavior:**
When I create the map the screen goes blank, apparently I should not or I do not see the error, it is true that when compiling it with xcode the message `WARN:' Ionic Native: tried accessing the GoogleMaps plugin but it's not installed.`, But then in the list of installed plugins if that appears.

For example, I created an alert (alert ('Installed' + GoogleMaps.installed ());) and returns false.

In the google console I created an api key, at first I had restrictions for a Bundle identifier but I ended up removing it in case there were problems in that sense (the restriction).

**Expected behavior:**
At first to see the map, then I would be responsible for putting points, routes, places ...

**Screen capture or video record:**
![captura de pantalla 2018-08-31 a las 12 44 34](https://user-images.githubusercontent.com/15185336/44908561-341ff800-ad1c-11e8-932e-d739d8b87e55.png)

**Related code, data or error log (please format your code or data):**

```
map: GoogleMap;
  mapElement: any;

  constructor(public navCtrl: NavController) {
    setTimeout(this.loadMap.bind(this), 1000);  
  }

  loadMap(){
    alert('Installed ' + GoogleMaps.installed());
    
    this.map = GoogleMaps.create('map');
    .
    .
    .
    .
    . 
  }
 
```

[Full code](https://github.com/keisserdur/Ionic-GoogleMaps)

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread. But you can still reply anytime.

**Comment by RicardoElSabio** [comment]
Its happening the same for me, I have no thrown error. Its just simply white screen, and the map cant be loaded .
<img width="946" alt="Capture" src="https://user-images.githubusercontent.com/20213260/78151723-2cb15b00-7439-11ea-9b18-1bc3a9ade6a1.PNG">

**Comment by nikiphoros** [comment]
same for me too

**Comment by TelmoFerreira** [comment]
Me too.. Ionic 6
