### ISSUE TITLE
Dragging the map

### ISSUE THREAD

**Issue by CustomDesignBuildStudios** [ionic-team/ionic-native-google-maps#65]
**I'm submitting a ...**  (check one with "x")
- [ X] question
- [ ] any problem or bug report
- [ X] feature request

I am trying to build a drawing a polygon feature, to do it I need to freeze the maps position and capture the users touch (down, up, move) events.

Is it possible to toggle the map's draggable option?
And can I capture mousemove, mouseup, mousedown events?

**Comment by CustomDesignBuildStudios** [comment]
Great I was able to set the options to false to freeze the map.
The only problem is the only events it captures are map/camera movement events (but cant use it because I froze the map)
Maybe I will try to capture those events on a separate div.

Is it possible to get the map lat/lng from a pixel point?

**Comment by wf9a5m75** [comment]
You should use MARKER_DRAG_START, MARKER_DRAG & MARKER_DRAG_END events. There is NO mouse on Android and ios

**Comment by CustomDesignBuildStudios** [comment]
Yes I know,
I was looking to create a drawing feature, not a point/click one.
I decided to go with a different div that overlays on top and toggles on/off
