### ISSUE TITLE
Map disabled all form elements

### ISSUE THREAD

**Issue by MohamedFekry007** [ionic-team/ionic-native-google-maps#68]
Hi, 

i have used the map in form which has multiple inputs and clicked divs, but its disabled all the actions, why this happened?

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
ping

**Comment by MohamedFekry007** [comment]
Hello, Sorry for being late, i`m trying to exclude this part of the project in a new project to share it with you but i got error "TypeError: Cannot read property 'LatLngBounds' of null" however i installed the plugin and the packages

**Comment by wf9a5m75** [comment]
I recommend you start from a blank project

**Comment by MohamedFekry007** [comment]
ok, will do this, thanks for your help

**Comment by alex-polosky** [comment]
@MohamedFekry007 Hey! I'm getting a similar issue, and I'm not sure what exactly you're going through, but mine was regarding the setCameraTarget. If you're having an issue with that I've opened a ticket over at the cordova plugin here: https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2416

**Comment by wf9a5m75** [comment]
Since @alex-polosky 's problem is not the same as original questioner at all, and he resolved the issue I close @alex-polosky 's comment.

**Comment by MohamedFekry007** [comment]
ok, thanks and i used the google maps without ionic and its working.

**Comment by wf9a5m75** [comment]
Well, this plugin works on ionic with/without `@ionic-native/google-maps`.
However if you use ionic 4, you need to use `@ionic-native/google-maps@beta`.

If you decide to use this plugin without ionic, that's fine.
