### ISSUE TITLE
Detect if has Panorama

### ISSUE THREAD

**Issue by CustomDesignBuildStudios** [ionic-team/ionic-native-google-maps#69]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [X] feature request

Right now if I createPanorama with a point next to a highway then the panorama loads correctly.
If I get a point in a gated community (or where Google hasn't scanned) then the panorama is black.

Is there any way to detect if a location has a panorama?

**Comment by wf9a5m75** [comment]
Google Maps does not have the api to detect that.

**Comment by CustomDesignBuildStudios** [comment]
It does have it on creation of a panorama

`   streetView.getPanorama({
      location: this.center,
      radius: 100,
      preference: google.maps.StreetViewPreference.NEAREST,
      source: google.maps.StreetViewSource.OUTDOOR
    },
      (data, status) => {
        if (status === google.maps.StreetViewStatus.OK) {
          //streetview exists
        }
        else {
          //no streetview exists
        }
      });`

**Comment by wf9a5m75** [comment]
As I said, there is no function especially Android and iOS. If you do it mandatory, please use Google Maps JavaScript API v3 instead of this plugin

**Comment by CustomDesignBuildStudios** [comment]
Ok thank you, it wasn't a deal breaker.
