### ISSUE TITLE
[Question] Access singe marker on a cluster without an event

### ISSUE THREAD

**Issue by renatoselenica** [ionic-team/ionic-native-google-maps#73]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [ ] any problem or bug report
- [ ] feature request

Hello again.

Wanted to ask if I can access a single marker in a cluster without doing an event.

So in something like this

```javascript
this.map.addMarkerCluster(options: MarkerClusterOptions).then((markercluster: MarkerCluster) => {

});
```

can I do something like

```javascript 
marker.showInfoWindow() 
```
or 
```javascript 
marker.remove() 
```

without having to do a click event. or with some sort of map ready but have the ability to know on which marker am I doing what?

**Comment by wf9a5m75** [comment]
nop.

**Comment by renatoselenica** [comment]
k thanks
