### ISSUE TITLE
Wrong type documentation for hasPermissions

### ISSUE THREAD

**Issue by maximilianloy** [ionic-team/ionic-native-google-maps#74]
The description of LocationService.hasPermission says its returning a MyLocation promise but it should be boolean.
```
  /**
   * Return true if the application has geolocation permission
   * @return {Promise<MyLocation>}
   */
    static hasPermission(): Promise<boolean>;
```
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [x] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-googlemaps 2.4.3 "cordova-plugin-googlemaps"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

    "@ionic-native/core": "4.12.2",
    "@ionic-native/google-maps": "^4.12.0",

**Comment by wf9a5m75** [comment]
When you find a wrong something, please send a PR.

**Comment by wf9a5m75** [comment]
fixed
