### ISSUE TITLE
Unable to disable default UI

### ISSUE THREAD

**Issue by MattL-NZ** [ionic-team/ionic-native-google-maps#77]
- [x ] question
- [x ] feature request

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.3 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.2 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.1.4 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

Is there a way we can disable the default UI as outlined here: [https://developers.google.com/maps/documentation/javascript/controls](https://developers.google.com/maps/documentation/javascript/controls)

**Comment by wf9a5m75** [comment]
All available options are defined here.

https://github.com/ionic-team/ionic-native-google-maps/blob/master/documents/googlemapcontroloptions/README.md

If there is no option, you can't control it

**Comment by MattL-NZ** [comment]
Is there plans to add this as an option in the future?

**Comment by wf9a5m75** [comment]
noo
