### ISSUE TITLE
Error with Google Maps PluginPolyline

### ISSUE THREAD

**Issue by guillermo-medina** [ionic-team/ionic-native-google-maps#8]
Hi, I getting this error from yesterday:

/platforms/android/src/plugin/google/maps/PluginPolyline.java:39: error: cannot access zzbgl

        polylineOptions.add(path.get(i));
                       ^
  class file for com.google.android.gms.internal.zzbgl not found

This was working yesterday before I tried to build my Android app.

Help!!

**Comment by wf9a5m75** [comment]
The Google Play Services SDK version you installed is too old. Please use the latest version `12.0.1`.

**Comment by guillermo-medina** [comment]
I changed the Google Play Services SDK in my project.properties to 12.0.1 and the error still happen. I have all updated.

**Comment by wf9a5m75** [comment]
Please share your project files on github if you can't solve the issue by yourself.

**Comment by guillermo-medina** [comment]
> The Google Play Services SDK version you installed is too old. Please use the latest version 12.0.1.

I was using version 12.0.0 before changed to 12.0.1 and the problem presists.

Do you have any idea why I can not build my project?

**Comment by wf9a5m75** [comment]
ping

**Comment by wf9a5m75** [comment]
Since there is no reply, I close this thread.
