### ISSUE TITLE
No padding when animateCamera() or moveCamera()

### ISSUE THREAD

**Issue by bb128b** [ionic-team/ionic-native-google-maps#80]
**I'm submitting a ...**  (check one with "x")
- [x] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [x] **Android**
- [x] **iOS**
- [ ] **Browser**

**Versions installed**

"@ionic-native/core": "^4.3.3",
"@ionic-native/google-maps": "^4.3.1",
"cordova-plugin-googlemaps": "^2.3.10",
        "cordova-plugin-googlemaps-sdk": "git+https://github.com/mapsplugin/cordova-plugin-googlemaps-sdk.git#2.7.0"

**Current behavior:**

When calling animateCamera() or moveCamera() with the padding option set, it only seems to work on iOS. On Android you get a very zoomed out view (see screenshot).

iOS

![screen shot 2018-09-20 at 11 48 40](https://user-images.githubusercontent.com/2276905/45814407-6397a400-bccd-11e8-835b-18fe5bf35b24.png)

Android

![screenshot_20180920-113742](https://user-images.githubusercontent.com/2276905/45814408-6397a400-bccd-11e8-8734-d74490d870c7.png)

Code

```
        this.map
            .animateCamera({
                target: targets.length === 1 ? targets[0] : targets, // Target is object if only 1, otherwise it has to be an array.
                zoom: 13,
                duration: 1000,
                padding: 75,
            });
```

**Expected behavior:**

I'm not sure how the iOS version is working... I checked the mapsplugin/cordova-plugin-googlemaps behind the scenes and the padding option does not exist at all...

```
/********************************************************************************
 * @name CameraPosition
 * @class This class represents new camera position
 * @property {LatLng} target The location where you want to show
 * @property {Number} [tilt] View angle
 * @property {Number} [zoom] Zoom level
 * @property {Number} [bearing] Map orientation
 * @property {Number} [duration] The duration of animation
 *******************************************************************************/
var CameraPosition = function(params) {
    var self = this;
    self.zoom = params.zoom;
    self.tilt = params.tilt;
    self.target = params.target;
    self.bearing = params.bearing;
    self.hashCode = params.hashCode;
    self.duration = params.duration;
};

module.exports = CameraPosition;
```

Is this now deprecated? Or did it never exist in the first place? I'm mainly asking because if it no longer exists we need to PR and remove it from the docs.

**Comment by wf9a5m75** [comment]
`"cordova-plugin-googlemaps": "^2.3.10"` is toooooo old.
I don't support old version. I only support the latest version.

You should reinstall & test the latest version before asking.

**Comment by bb128b** [comment]
Even the latest version (2.4.4) go that plugin does not have padding as a camera option...

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/3e8879984d9224d4803d9655a1232c3deea174b3/www/CameraPosition.js

**Comment by wf9a5m75** [comment]
CameraPosition object does not contain padding property. It is use to notify the camera location

**Comment by wf9a5m75** [comment]
If you don't satisfy this plugin, please use another plugin.

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/master/src/ios/GoogleMaps/PluginMap.m#L512-L515

**Comment by bb128b** [comment]
So there is padding in this plugin? It just doesn't work? I like the plugin
and don't plan on using another. I am trying to help make this better by
raising a bug. If we both agree it is not working I will try to create a
PR.
