### ISSUE TITLE
Google Maps JavaScript API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

### ISSUE THREAD

**Issue by rajnikant307** [ionic-team/ionic-native-google-maps#82]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [X ] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ X] **Android**
- [ X] **iOS**
- [ X] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
insert the output from the command here
```

    @ionic-native/core : 4.12.2
    @ionic-native/google-maps : 4.14.0

Map load with greyscreen with message like "for development purpose only" in console i get message like 
![untitled](https://user-images.githubusercontent.com/6419219/45890362-6e8f2900-bde0-11e8-8d43-96865196ce85.png)

any help?

**Comment by wf9a5m75** [comment]
I recommend you do research before asking.
https://github.com/mapsplugin/cordova-plugin-googlemaps#api-key

**Comment by markfilan** [comment]
As the error message says, you need APIKey to remove this error while [embed Google Map](http://net-informations.com/q/web/map.html). In the google Developer documentation it says you shall add the api key as option {key:yourKey} when calling the API to create new instances. This however doesn't shush the console warning. You have to add the key as a parameter when including the api.

You can get APIKey from https://developers.google.com/maps/documentation/javascript/get-api-key#get-an-api-key

And apply that key to your code like :

<script async defer src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY&callback=initMap" type="text/javascript"></script>

The usage is free until your application reaches 25.000 calls per day on 90 consecutive days.
