### ISSUE TITLE
Is there any way to get the lines from Geocoder results?

### ISSUE THREAD

**Issue by MattL-NZ** [ionic-team/ionic-native-google-maps#84]
- [x] question

Is there a way to get the line details from the geocoder results?
I've tried `results[0].extra.lines[]` but that doesn't work
![image](https://user-images.githubusercontent.com/2846782/45935246-9a3b2a80-bffd-11e8-9e74-f61a1afade02.png)

**Comment by wf9a5m75** [comment]
https://www.npmjs.com/package/@ionic-native/native-geocoder

**Comment by MattL-NZ** [comment]
I'm testing with the browser but the app will be run on `Android` and `iOS`

**Comment by MattL-NZ** [comment]
I've tried using the link you supplied but i get the following error whenever i try and initialise it...

`constructor(private nativeGeocoder: NativeGeocoder) { }`

Get the error: `TypeError: Object(...) is not a function
    at index.js:103
    at Object../node_modules/@ionic-native/native-geocoder/index.js`

**Comment by wf9a5m75** [comment]
I confirmed `lines` filed position was incorrect in Browser platform code.
I fixed it.

Please reinstall the plugin from the `multiple_maps` branch.

```
$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable ...
```

**Comment by MattL-NZ** [comment]
Sorry how do we reinstall via the plugin from the `multiple_maps` branch? That is something I have not done before... Can you put the full command in?

**Comment by wf9a5m75** [comment]
```
$> cd (your project dir)

$> cordova plugin rm cordova-plugin-googlemaps

$> cordova plugin add https://github.com/mapsplugin/cordova-plugin-googlemaps#multiple_maps --variable API_KEY_FOR_ANDROID="(your api key)" --variable API_KEY_FOR_IOS="(your api key)"
```

**Comment by MattL-NZ** [comment]
Cool thanks. Have reinstalled and tested and its now working correctly in the browser. Thanks!
