### ISSUE TITLE
Add plugin on iOS platform

### ISSUE THREAD

**Issue by jjvillavicencio** [ionic-team/ionic-native-google-maps#93]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [ ] **Android**
- [x] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**

```
"@ionic-native/core": "^4.15.0",
    "@ionic-native/google-maps": "^4.14.0",
```

**Current behavior:**

```
Installing "cordova-plugin-googlemaps" for ios
--[cordova-plugin-googlemaps]------------------------
From version 2.4.5, the cordova-plugin-googlemaps uses CocoaPod.
No longer necessary com.googlemaps.ios plugin.
Automatic uninstalling com.googlemaps.ios plugin...
-----------------------------------------------------
Failed to install 'cordova-plugin-googlemaps': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'
    at cli.catch.err (/usr/local/lib/node_modules/cordova/bin/cordova:30:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ERROR] An error occurred while running subprocess cordova.

        cordova platform add ios --save exited with exit code 1.
```

**Screen capture or video record:**
<img width="802" alt="screen shot 2018-10-15 at 2 37 51 pm" src="https://user-images.githubusercontent.com/4654352/46973823-f129a200-d087-11e8-9434-cdebba3ae71a.png">

**Comment by wf9a5m75** [comment]
Can you see any characters in version definition? 

https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.6/plugin.xml#L2

**Comment by wf9a5m75** [comment]
I guess your cocoapod is old.

**Comment by jjvillavicencio** [comment]
> I guess your cocoapod is old.
Hi thanks for response, I have the latest version

```
MacBook-Pro-de-Quilson:prueba qbejarano$ pod --version
1.6.0.beta.1
```

**Comment by jjvillavicencio** [comment]
> Can you see any characters in version definition that matches agains the rule?
> 
> ```
> <plugin id="cordova-plugin-googlemaps" version="2.4.6" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android">
> ```
> 
> https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/v2.4.6/plugin.xml#L2

```
<?xml version='1.0' encoding='utf-8'?>
  <plugin id="cordova-plugin-googlemaps" version="2.4.6" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android">
  <name>cordova-plugin-googlemaps</name>
```

**Comment by wf9a5m75** [comment]
ping

**Comment by aahmedfouad** [comment]
@wf9a5m75 i have the same issue 
`Installing "cordova-plugin-googlemaps" for ios
--[cordova-plugin-googlemaps]------------------------
From version 2.4.5, the cordova-plugin-googlemaps uses CocoaPod.
No longer necessary com.googlemaps.ios plugin.
Automatic uninstalling com.googlemaps.ios plugin...
-----------------------------------------------------`
`cocoa pod version 1.5.3`

**Comment by wf9a5m75** [comment]
That's not error message.

**Comment by aahmedfouad** [comment]
i updated the cocoa pods and getting this error
`
The following build commands failed:
        CompileC /Users/anspireagency/Library/Developer/Xcode/DerivedData/Doctory-cswdyztwiawywbgslbeprrywufql/Build/Intermediates.noindex/Doctory.build/Debug-iphonesimulator/Doctory.build/Objects-normal/x86_64/PluginCircle.o Doctory/Plugins/cordova-plugin-googlemaps/PluginCircle.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
(node:1928) UnhandledPromiseRejectionWarning: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/anspireagency/Desktop/ahmed f/Doctory/platforms/ios/cordova/build-debug.xcconfig,-workspace,Doctory.xcworkspace,-scheme,Doctory,-configuration,Debug,-sdk,iphonesimulator,-destination,platform=iOS Simulator,name=iPhone X,build,CONFIGURATION_BUILD_DIR=/Users/anspireagency/Desktop/ahmed f/Doctory/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/anspireagency/Desktop/ahmed f/Doctory/platforms/ios/build/sharedpch
(node:1928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/issues/2434

**Comment by wf9a5m75** [comment]
ping

**Comment by schagani** [comment]
@wf9a5m75 
Are you using Ionic 4 version?
If yes then please try below command

npm install --save @ionic-native/core@beta @ionic-native/google-maps@beta

**Comment by wf9a5m75** [comment]
Are you asking me, or do you giving me a hint?

**Comment by schagani** [comment]
Its a hint

**Comment by wf9a5m75** [comment]
Thank you, but I'm the author of this plugin. It means I develop this plugin and `ionic-native/google-maps` :)

**Comment by wf9a5m75** [comment]
Since there is no response for a while, I close this thread.

**Comment by Thierry-Santos** [comment]
exactly same error here when: ionic cordova platform add ios

--[cordova-plugin-googlemaps]------------------------
From version 2.4.5, the cordova-plugin-googlemaps uses CocoaPod.
No longer necessary com.googlemaps.ios plugin.
Automatic uninstalling com.googlemaps.ios plugin...
-----------------------------------------------------
Failed to install 'cordova-plugin-googlemaps': undefined
CordovaError: Promise rejected with non-error: 'Version should contain only numbers and dots'


`<?xml version='1.0' encoding='utf-8'?>
<plugin id="cordova-plugin-googlemaps" version="2.4.6" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android">
  <name>cordova-plugin-googlemaps</name>`

MBP-de-Thierry:app-ionic trbr$ pod --version
1.6.0.beta.2

**Comment by 2diegoduque** [comment]
<img width="568" alt="Captura de pantalla 2019-06-11 22 38 12" src="https://user-images.githubusercontent.com/23130683/59321927-a9e8c500-8c99-11e9-94ed-cbc0baafa17f.png">

to date the error continues

**Comment by LautaroLorenz** [comment]
"framework" tag with type "podspec" is deprecated and will be removed. Please use the "podspec" tag.
Failed to install 'cordova-plugin-googlemaps':undefined

**Comment by Sevensnake** [comment]
this error keeps coming back with no fix over a year this is some real nonsense.

**Comment by zulkarnainshah** [comment]
I hit this error too on an ionic 4 project.
