### ISSUE TITLE
White Map with Ionic 4 

### ISSUE THREAD

**Issue by petinho** [ionic-team/ionic-native-google-maps#94]
**I'm submitting a ...**  (check one with "x")
- [ ] question
- [x] any problem or bug report
- [ ] feature request

**If you choose 'problem or bug report', please select OS:**  (check one with "x")
- [X] **Android**
- [ ] **iOS**
- [ ] **Browser**

**cordova information:**  (run `$> cordova plugin list`) 

```
cordova-plugin-device 2.0.2 "Device"
cordova-plugin-googlemaps 2.4.6 "cordova-plugin-googlemaps"
cordova-plugin-ionic-keyboard 2.1.3 "cordova-plugin-ionic-keyboard"
cordova-plugin-ionic-webview 2.2.0 "cordova-plugin-ionic-webview"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2 "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
```

**If you use `@ionic-native/google-maps`, please tell the package.json (only `@ionic-native/core` and `@ionic-native/google-maps` are fine mostly)**
`"@ionic-native/core": "5.0.0-beta.21"
"@ionic-native/google-maps": "^5.0.0-beta.23"`

**Current behavior:**

The map is showed as a white screen on an Ionic 4 Tab template. There's no errors in the console, and if I run it with `ionic cordova run browser` the maps shows. On the phone it seems to work, and if I press the Demo button the marker is created and I can even click on it, and the toast is also shown. But the screen remains white.

**Expected behavior:**

The map should appear.
**Screen capture or video record:**

![image](https://user-images.githubusercontent.com/9249768/47009080-e597b300-d13b-11e8-81ec-bb635a1fcbb6.png)

**Related code, data or error log (please format your code or data):**

I have currently no log, as no errors are shown. The repo of the complete project is:

https://github.com/petinho/ionic_ticketer_client

**Comment by BrunoGustavoChagas** [comment]
I'm having the same problem, however, I'm developing with ionic3.

It's strange because a few hours ago the application was working normally on my cell phone, but it stopped! Now it's only working in the browser!

**Comment by BrunoGustavoChagas** [comment]
similar problem here! on browser works but on my phone... white map!

**Comment by wf9a5m75** [comment]
@BrunoGustavoChagas Make sure your API key.

**Comment by BrunoGustavoChagas** [comment]
@wf9a5m75 At first, I thought the problem was the API KEY. To test I removed it and test again on the browser, then the map was marked with a watermark (with the key, there wasn't watermark)! This means that KEY was working before... so, I guess the Key is not the problem

**Comment by wf9a5m75** [comment]
API key for browser, and API keys for Android/iOS are different.
This plugin does not use Google Maps JavaScript v3 on Android and iOS.
You must be enable `Google Maps SDK for Android/iOS` **BEFORE** key generate, then you need to generate different keys for each platforms.

**Comment by wf9a5m75** [comment]
@BrunoGustavoChagas Even then if you can't solve the problem by yourself, please share your project files on github.

**Comment by petinho** [comment]
I use here the same key as for a Ionic 3 project that works. On the browse I see the gray map with the error on the console (at least I see the map). But on the mobile I see nothing.

**Comment by BrunoGustavoChagas** [comment]
@wf9a5m75 didn't work! I'm sorry, I forgot to mention that I'm developing in Ionic 3! I noticed now that even if I choose "Maps SDK for Android" on Google Cloud Platforms... the Key is the same as "Maps JavaScript API".

**Comment by wf9a5m75** [comment]
@petinho During the development, you can use the same key for all platforms because you don't set any restriction.
Without restriction, other people can be able to your api key for another project, but you need to pay for that.

**Comment by petinho** [comment]
Yes, I mean that the key is from one of my ionic projects that works

**Comment by wf9a5m75** [comment]
@petinho It seems ionic4 introduce another DOM, and it is blocked because of `background-color`.
![screen shot 2018-10-16 at 5 10 04 pm](https://user-images.githubusercontent.com/167831/47054405-7b483800-d166-11e8-96be-b02fca694aae.png)

**Comment by wf9a5m75** [comment]
Ok, I solved this problem.
You need to reinstall the maps plugin from the multiple_maps branch.

![capture](https://user-images.githubusercontent.com/167831/47056560-cf0c4e80-d171-11e8-9a8e-77e62fdc9db7.png)

**Comment by wf9a5m75** [comment]
https://github.com/mapsplugin/cordova-plugin-googlemaps/#quick-install

**Comment by petinho** [comment]
I've tested right now and seems to work! Is this branch going to be integrated in the plugin?

**Comment by wf9a5m75** [comment]
The multiple_maps branch is the next version.
